### ISSUE TITLE
Could you please provide the marvell 88w8864 80211ac chip datasheet? 

### ISSUE THREAD

**Issue by luanjinlu** [kaloz/mwlwifi#101]
Hi kaloz
 Could you please provide the marvell 88w8864 80211ac chip datasheet for me?
 Looking forward to your reply.

Best Regards
rainbowdeer@qq.com

**Comment by yuhhaurlin** [comment]
Please check with MARVELL AE.

**Comment by jbsky** [comment]
No link?
