### ISSUE TITLE
802.11ac Speed Slow when compared with Stock firmware

### ISSUE THREAD

**Issue by edwardwong80** [kaloz/mwlwifi#104]
I have my WRT1900AC v2 running OpenWRT CC 15.05.1, I've run iperf test between Macbook Pro 2014 (802.11ac 3T3R) and laptop w/gigabit ethernet on LAN side (so no NAT involved).

A single stream of data showing 125Mbps, when I shoot 5 stream altogether I get about 425-450Mbps max. (Sorry I've lost the screen capture), but on stock firmware a single stream can give me 400Mbps+ and 5 stream is giving me almost 800Mbps throughput! (See attached photo)

![iperf-wifi-1-stream](https://cloud.githubusercontent.com/assets/21307353/18048124/ef87cd34-6e12-11e6-842f-eb2f5aaac92e.jpg)
![iperf-wifi-5-stream](https://cloud.githubusercontent.com/assets/21307353/18048125/ef8bac74-6e12-11e6-998e-deb2e83dd582.jpg)

On my Mac it's saying that connectivity was 802.11ac, 80MHz, 1300Mbps (for both stock/OpenWRT) , I understand stock firmware is using proprietary driver so it should perform better, but the difference seems to be so huge (but the connectivity is stable, 8-10 ppl using together is fine), can this be improved?

P.S. My first time posting in GitHub so please tell me if I've missed something and I'll try to reply with more info if needed.

**Comment by yuhhaurlin** [comment]
Please use latest mwlwifi driver to do test. From our internal test (In shielding room), both drivers have almost the same throughput.
