### ISSUE TITLE
Temperature is reported incorrectly for the CPU (WRT1900ACS v1)

### ISSUE THREAD

**Issue by shmerl** [kaloz/mwlwifi#113]
I'm using latest DD-WRT build (10-18-2016-r3077) which uses driver 10.3.2.0-20161011 with  Marvell Armada 385 and 88W8864.

It reports CPU temperature incorrectly (0°C or even negative).

**Comment by shmerl** [comment]
Probably incorrect place to open it, since it's not WiFi related.

**Comment by shmerl** [comment]
Reopening, since it can be related to thermal monitoring in thermal.* Feel free to close it if it's not relevant.

**Comment by yuhhaurlin** [comment]
I don't think it is related to WiFi.

**Comment by BrainSlayer** [comment]
its not related to the driver. it was a bug in my firmware code which has been already resolved

**Comment by BrainSlayer** [comment]
as side node. under some conditions the cpu temperature is reported wrong. but this is related to the armada cpu and not to the wifi chipset. this happens spuriously and can only be fixed by power switching the device. its not clear why this happens.

**Comment by shmerl** [comment]
It has been happening to me pretty regularly after certain update, so it must be some regression. Also reported [here](http://svn.dd-wrt.com/ticket/5592).

**Comment by yuhhaurlin** [comment]
If stock firmware is all right, I think maybe you need to check with Belkin. This GitHub only handles WiFi problems.

**Comment by BrainSlayer** [comment]
stock firmware does not offer to monitor the cpu temperature

**Comment by BrainSlayer** [comment]
consider that im the developer of DD-WRT. i'm aware of this issue, but i dont know the reason. i just know that its working again after reboot

**Comment by BrainSlayer** [comment]
on the second hand its not the latest version of dd-wrt which you're used

**Comment by yuhhaurlin** [comment]
Maybe you can check with LEDE or OpenWrt (Someone from these two groups should work for BSP).

**Comment by shmerl** [comment]
I'm using the latest from here: ftp://ftp.dd-wrt.com/betas/2016/12-15-2016-r30949/
If there is something later, i probably have missed that.

**Comment by BrainSlayer** [comment]
just checked it again. consider this kernel log error for the sensor driver. "thermal thermal_zone0: Temperature sensor reading not valid"
root@DD-WRT:/sys/devices/virtual/hwmon/hwmon0# cat temp1_input
cat: read error: I/O error

**Comment by yuhhaurlin** [comment]
In fact, thermal function of mwlwifi does not work for 88W8864. So this problem should not be related to mwlwifi.

int mwl_thermal_register(struct mwl_priv *priv)
{
	struct thermal_cooling_device *cdev;
	struct device *hwmon_dev;
	int ret;

	if (priv->chip_type != MWL8897)
		return 0;

**Comment by shmerl** [comment]
I see it's using armada_thermal module. May be there was some update to the kernel that make the module not compatible?

**Comment by yuhhaurlin** [comment]
Basically, for 88W8897, this function is used to get temperature of WiFi chip and another function allow user to set quiet mode of 88W8897. However, 88W8864 does not support these things. So if you use 88W8864, mwlwifi does not register anything to Linux thermal framework.

**Comment by shmerl** [comment]
Yeah, it's a separate module from mwlwifi.

**Comment by BrainSlayer** [comment]
i just discovered this. should fix the issue now http://svn.dd-wrt.com/changeset/31126

**Comment by shmerl** [comment]
Ah, interesting. Thanks.
