### ISSUE TITLE
mwlwifi doesnt return a usefull channel noise value

### ISSUE THREAD

**Issue by BrainSlayer** [kaloz/mwlwifi#116]
its mainly a feature request. please implement NL80211_SURVEY_INFO_NOISE
right now it doesnt seem to be supported or at least it doesnt return a usefull value. (seem to be fixed to -95 which is incorrect as it seems) since it results in a negative SNR value sometimes

**Comment by yuhhaurlin** [comment]
I will fix it later.

**Comment by yuhhaurlin** [comment]
I modify the code to support time, time_busy and time_tx for get_servery(). ACS can work now. Noise level is optional, I remove it. Thanks.

**Comment by BrainSlayer** [comment]
are you sure your patch is correct? it seem to make wireless non operatable on 88W8964 (wrt3200acm) will check it now on 88w8864
