### ISSUE TITLE
latest git version does not seem to be compatible with 88w8964

### ISSUE THREAD

**Issue by BrainSlayer** [kaloz/mwlwifi#124]
from first point of view the hardcoded registers for channel busy time seem to be incompatible to 88w8964. the driver does work on 88w8864 but not on 88w8964. tested in client mode on wrt3200acm. will check more tomorrow after i'm back on my testbed

**Comment by yuhhaurlin** [comment]
Yes. I also find this kind of problem. I will fix it soon. Thanks.

**Comment by yuhhaurlin** [comment]
https://github.com/kaloz/mwlwifi/commit/0b66cc4eca32529c8bc959e486ae0f25030ed560 fixes this issue. Thanks.

**Comment by BrainSlayer** [comment]
perfect. thanks
