### ISSUE TITLE
Strange performance using WPA2 TKIP Encryption

### ISSUE THREAD

**Issue by ark4n631** [kaloz/mwlwifi#125]
I have a wrt1900AC, i installed (dd-wrt, openwrt CC, DD, LEDE, etc) with all this firmwares, if you put encryption wpa2 and FORCE TKIP the connection (even in 5g) drop to 54mbps max and real connection output to internet give you 20mpbs at max.

I tested almost every firmware and took me a lot of time and effort saw this strange behavior.

If you want more info i can attach you the logs, and speedtest.

Thanks in advance and good luck

**Comment by yuhhaurlin** [comment]
This is correct behavior. WiFi device does not use HT rates when using TKIP as the encryption cipher. If you want to have good performance, please use AES only. Thanks.

**Comment by ark4n631** [comment]
@yuhhaurlin Thanks for answering, could you please put that info on the Readme, i could not know that info, it might help others in the future.

Thank you.

**Comment by yuhhaurlin** [comment]
Done.
