### ISSUE TITLE
Add support for 802.11s

### ISSUE THREAD

**Issue by belzebub40k** [kaloz/mwlwifi#127]
Is it still planned to add support for 802.11s? All I could find regarding this feature is a post on a mailinglist that is one and a half year old.

```
> On 06/06/2015 6:01 AM, Alexis Green wrote:
> Are there plans to add support for 802.11s mesh point mode?
> 
Yes, it will be worked on in the future.

Thanks,
David
```
https://www.spinics.net/lists/linux-wireless/msg137528.html

**Comment by yuhhaurlin** [comment]
Previous working is pending (VHT is not supported by mac80211 at that time). There is no plan now. Thanks.

**Comment by linuskallander** [comment]
Mesh networks are becoming big. Still no plans to implement 802.11s?

**Comment by yuhhaurlin** [comment]
It is done for another chip. The code will be merged here later. However there is no plan for 8864 and 8964.

**Comment by linuskallander** [comment]
That's to bad... I hoped my linksys wrt1900acs would be future proof, but it seems I was wrong. (if I'm reading the specs correctly)  :(

**Comment by yuhhaurlin** [comment]
Where did you get the specs? I don't think that 802.11s is supported by wrt1900acs. BTW, WEB GUI of LEDE has problem to set mesh interface. It needs patches to achieve mesh setting. I wonder which product supported by LEDE has supported 802.11s now?

**Comment by linuskallander** [comment]
I found them here https://wiki.openwrt.org/toh/hwdata/linksys/linksys_wrt1900acs_v1

**Comment by yuhhaurlin** [comment]
I can't find the support for 802.11s.

**Comment by linuskallander** [comment]
No, put of the box it's not supported. I hoped the community would take care of that. But I realize I had to high hopes. Maybe it's not even technically possible?

**Comment by linuskallander** [comment]
*out of the box

**Comment by yuhhaurlin** [comment]
Mwlwifi has added code to support 802.11s and it is still under verification on another chip. I think this feature will be supported by our next chip (11ax).

**Comment by s-pimenta** [comment]
The chip does need to support that protocol, right? So the implementation will be impossible unless the chipset support's it..

**Comment by BrainSlayer** [comment]
unlikelly. i dont think its chipset related, but firmware related since the wifi protocol stack based functions are handled in the firmware.

**Comment by s-pimenta** [comment]
So... after implementing WDS, MU-MIMO, monitor mode, and next should be 802.11s... at least for 88W8964 (WRT3200ACM) it has only almost 1 year of existence

**Comment by thagabe** [comment]
@s-pimenta 
@yuhhaurlin said "there is no plan for 8864 and 8964." which is truly disappointing

**Comment by s-pimenta** [comment]
@thagabe Yeah I now... companies has objectives, new products are released and will shift focus to newer produtcs to make profit... they are not interessted in supporting the actual customers... 

This is like Android devices... 2 years max of updates... unless you install a custom ROM from the XDA community...

Unless @yuhhaurlin releases the documentation of the 88W8964, we are at the mercy of what support we can get from Marvell...

**Comment by yuhhaurlin** [comment]
It is not trivial for SC4 to support mesh. BTW, I wonder which device supported by LEDE or dd-WRT supports it.

**Comment by belzebub40k** [comment]
@yuhhaurlin Unfortunately there aren't many platforms that support 802.11s. Most devices we use to build our community mesh networks in Germany are ar71xx-*. Some ramips devices also have support for 802.11s but the connections aren't very stable.

**Comment by BrainSlayer** [comment]
@yuhhaurlin QCA chipsets and mediatek

**Comment by s-pimenta** [comment]
@yuhhaurlin Mesh networks is still relatively new, especialy in home use... so we need to start somewere...

**ath9k** and the mighty **WRT54G** is still used because of open documentation...

**Comment by yuhhaurlin** [comment]
Thanks for all your information. If some devices already support it, why the WEB GUI of LEDE still has problem to set mesh interface?

**Comment by yuhhaurlin** [comment]
Even though document is open, I don't think you can work on this driver without source code of firmware.
