### ISSUE TITLE
Hostapd error with 10.3.4.0-20170421

### ISSUE THREAD

**Issue by borkra** [kaloz/mwlwifi#146]
Started to get a lot of:

daemon.notice hostapd: ieee802_11_send_sa_query_req: send failed

With today release.

This error did not appear with April 19, 2017 driver.

**Comment by yuhhaurlin** [comment]
Please help to check 10.3.4.0-20170512. Thanks.

**Comment by borkra** [comment]
The above problem is gone. 
The only problem I see is key renegotiation every 10 min, did not used to do that.

**Comment by BrainSlayer** [comment]
the key renegotiation is configurable in hostapd. so check which value you used. standard is normally 60 minutes (3600 seconds)

**Comment by yuhhaurlin** [comment]
Yes. It is not related to mwlwifi driver. I close this one.
