### ISSUE TITLE
next-20170501, aka 4.12: build failure due to changes in mac80211

### ISSUE THREAD

**Issue by seragh** [kaloz/mwlwifi#153]
Flags like RX_FLAG_HT are no longer.

hif/pcie/rx.c:231:19: error: 'RX_FLAG_HT' undeclared (first use in this function)
   status->flag |= RX_FLAG_HT;
                         ^

**Comment by yuhhaurlin** [comment]
I will check it. Thanks.

**Comment by yuhhaurlin** [comment]
Thanks. I will check and merge it.
