### ISSUE TITLE
WRT3200ACM - mwlwifi - Kernel Crash Upon Wifi Connect - DDWRT r31899

### ISSUE THREAD

**Issue by rs-se** [kaloz/mwlwifi#154]
Full Log Here: https://pastebin.com/q02pxKcF

Not entirely certain what exactly is causing the Kernel Crash however the crash analysis backtrace sheds light on the mwlwifi driver.

**Comment by BrainSlayer** [comment]
this crash has already been resolved. download www.dd-wrt.com/wrt3200.zip. it contains a newer testversion which covers the issue

**Comment by yuhhaurlin** [comment]
I will close this one. Thanks.
