### ISSUE TITLE
Add support for mwl8k device in mwlwifi

### ISSUE THREAD

**Issue by Menion2k** [kaloz/mwlwifi#155]
Hi
Do you have any plan to add the devices supported in mwl8k in your new mwlwifi?
The reason why I am asking it is that the mwl8k seems to be a kind of umaintaned and it suffers of a lot of instability and issues, see: https://bugs.lede-project.org/index.php?do=details&task_id=759
Bye

**Comment by yuhhaurlin** [comment]
Sorry. I don't think this driver will support mwl8k.
