### ISSUE TITLE
Interface crash?

### ISSUE THREAD

**Issue by farchord** [kaloz/mwlwifi#157]
(Sorry I'm a newb so I'm not too sure what's the proper procedure on reporting this)

I have the Linksys WRT3200ACM with the latest build of davidc502's LEDE firmware. I was running only one 5ghz radio since this morning (Because of the memory bug -- https://github.com/kaloz/mwlwifi/issues/152).

This afternoon at 1 PM, I noticed the wifi was dead. I checked the kernel logs:
Thu May  4 12:55:27 2017 kern.info kernel: [22822.607428] mwifiex_sdio mmc0:0001:1: 2252305 : Tx timeout(#2), bss_type-num = 1-0
Thu May  4 12:55:37 2017 kern.info kernel: [22832.597226] mwifiex_sdio mmc0:0001:1: 2253304 : Tx timeout(#3), bss_type-num = 1-0
Thu May  4 12:55:47 2017 kern.info kernel: [22842.597002] mwifiex_sdio mmc0:0001:1: 2254304 : Tx timeout(#4), bss_type-num = 1-0
Thu May  4 12:55:57 2017 kern.info kernel: [22852.596780] mwifiex_sdio mmc0:0001:1: 2255304 : Tx timeout(#5), bss_type-num = 1-0
Thu May  4 12:56:07 2017 kern.info kernel: [22862.596557] mwifiex_sdio mmc0:0001:1: 2256304 : Tx timeout(#6), bss_type-num = 1-0
Thu May  4 12:56:17 2017 kern.info kernel: [22872.596334] mwifiex_sdio mmc0:0001:1: 2257304 : Tx timeout(#7), bss_type-num = 1-0
Thu May  4 12:56:17 2017 kern.info kernel: [22872.603939] mwifiex_sdio mmc0:0001:1: tx_timeout_cnt exceeds threshold.	Triggering card reset!
Thu May  4 12:56:17 2017 kern.warn kernel: [22872.745127] mwifiex: Have pending ack frames!
Thu May  4 12:56:17 2017 kern.warn kernel: [22872.749511] mwifiex: Have pending ack frames!
Thu May  4 12:56:17 2017 kern.warn kernel: [22872.753885] mwifiex: Have pending ack frames!
Thu May  4 12:56:17 2017 kern.warn kernel: [22872.758263] mwifiex: Have pending ack frames!
Thu May  4 12:56:17 2017 kern.warn kernel: [22872.762636] mwifiex: Have pending ack frames!
Thu May  4 12:56:17 2017 kern.info kernel: [22872.768089] mwifiex_sdio mmc0:0001:1: info: shutdown mwifiex...
Thu May  4 12:56:17 2017 kern.info kernel: [22872.774276] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
Thu May  4 12:56:17 2017 kern.info kernel: [22872.780291] mwifiex_sdio mmc0:0001:1: Failed to delete mgmt IEs!
Thu May  4 12:56:17 2017 kern.info kernel: [22872.786329] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
Thu May  4 12:56:17 2017 kern.info kernel: [22872.792273] mwifiex_sdio mmc0:0001:1: Failed to stop the BSS
Thu May  4 12:56:17 2017 daemon.notice netifd: Network device 'wlan2' link is down
Thu May  4 12:56:17 2017 kern.info kernel: [22872.798347] br-lan: port 2(wlan2) entered disabled state
Thu May  4 12:56:17 2017 kern.info kernel: [22872.805687] device wlan2 left promiscuous mode
Thu May  4 12:56:17 2017 kern.info kernel: [22872.810278] br-lan: port 2(wlan2) entered disabled state
Thu May  4 12:56:17 2017 kern.info kernel: [22872.815794] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
Thu May  4 12:56:17 2017 kern.info kernel: [22872.821847] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
Thu May  4 12:56:17 2017 kern.info kernel: [22872.827889] mwifiex_sdio mmc0:0001:1: PREP_CMD: card is removed
Thu May  4 12:56:17 2017 daemon.notice hostapd: wlan2: AP-STA-DISCONNECTED a4:5e:60:e0:64:4f
Thu May  4 12:56:17 2017 daemon.notice hostapd: wlan2: AP-STA-DISCONNECTED f8:04:2e:f5:d8:fe
Thu May  4 12:56:17 2017 daemon.notice hostapd: wlan2: AP-STA-DISCONNECTED c8:69:cd:88:b2:23
Thu May  4 12:56:17 2017 daemon.notice hostapd: wlan2: AP-STA-DISCONNECTED 68:db:ca:6a:c0:0f
Thu May  4 12:56:17 2017 daemon.notice hostapd: wlan2: INTERFACE-DISABLED 
Thu May  4 12:56:17 2017 kern.info kernel: [22872.980587] mwifiex_sdio mmc0:0001:1: WLAN FW already running! Skip FW dnld
Thu May  4 12:56:17 2017 kern.info kernel: [22872.987723] mwifiex_sdio mmc0:0001:1: WLAN FW is active
Thu May  4 12:56:17 2017 kern.info kernel: [22873.007934] mwifiex_sdio mmc0:0001:1: CMD_RESP: cmd 0x242 error, result=0x2
Thu May  4 12:56:17 2017 kern.info kernel: [22873.014930] mwifiex_sdio mmc0:0001:1: mwifiex_process_cmdresp: cmd 0x242 failed during	initialization
Thu May  4 12:56:17 2017 kern.info kernel: [22873.031196] mwifiex_sdio mmc0:0001:1: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p5) 
Thu May  4 12:56:17 2017 kern.info kernel: [22873.039304] mwifiex_sdio mmc0:0001:1: driver_version = mwifiex 1.0 (15.68.7.p5)

**Comment by yuhhaurlin** [comment]
Radio 2 is not mwlwifi.
