### ISSUE TITLE
TX Rate

### ISSUE THREAD

**Issue by gufus** [kaloz/mwlwifi#16]
No/wrong  TX Rate frame rate information.

**Comment by thagabe** [comment]
Which wlan? 2.4Ghz or 5GHzor both? Trunk version? mwlwifi version?

**Comment by gufus** [comment]
kmod-mwlwifi
3.18.11+10.2.8.5.p0-20150401-1

Both 2.4/7

with trunk

openwrt r45415
Linux 3.18.11 #1 SMP Tue Apr 14 07:30:42 UTC 2015 armv7l GNU/Linux

**Comment by yuhhaurlin** [comment]
It is not supported now. I will add code to support it. Thanks.

**Comment by 353539517** [comment]
TX Rate frame rate information always show "6Mbit/s"

**Comment by gufus** [comment]
@thagabe 

:+1:

**Comment by yuhhaurlin** [comment]
Report transmit frame rate information. 
Signed-off-by: David Lin <dlin@marvell.com>
commit 85cdc98457c31d27a62f3ded31f508a75a95c810

**Comment by gufus** [comment]
Thanks David :+1:

**Comment by gufus** [comment]
@yuhhaurlin 


FYI
https://forum.openwrt.org/viewtopic.php?pid=273816#p273816  :)

**Comment by yuhhaurlin** [comment]
Thanks.
