### ISSUE TITLE
"unknown" properties from kernel

### ISSUE THREAD

**Issue by kb3tbx** [kaloz/mwlwifi#163]
Although I am using LEDE for testing, I do not know what the source of this issue is.

several items reported in iwinfo always show 'unknown' in place of real values.
Like:
- Link Quality
- Signal level
- Bit Rate, 

But, thank you for two days of uptime!

![unknown capture](https://cloud.githubusercontent.com/assets/24195924/26040342/75043c68-38f2-11e7-8f17-5010d631d4fa.PNG)

**Comment by yuhhaurlin** [comment]
Tx/Rx rate and signal report will be added later. It will be added after STA mode is ready. Thanks.

**Comment by kb3tbx** [comment]
OK!
NOW I will be patient.

**Comment by yuhhaurlin** [comment]
Thanks.
