### ISSUE TITLE
WMM mode

### ISSUE THREAD

**Issue by nitroshift** [kaloz/mwlwifi#167]
If WMM mode is turned off, wifi broadcasts but no devices can connect to them. Tested on WRT3200ACM with driver version  10.3.4.0 - 20170512 (commit 6d1595e9db5dec8e61332f6be431b3bf972d6d08).

nitroshift

**Comment by BrainSlayer** [comment]
turning off wmm will disable all 802.11n / 802.11ac capabilities. read the spec

**Comment by mrvltest** [comment]
I close this one. Please don't disable WMM.
