### ISSUE TITLE
5Ghz set  to 160Mhz channel width

### ISSUE THREAD

**Issue by gufus** [kaloz/mwlwifi#18]
trunk
openwrt r45601
 Linux 3.18.11 #1 SMP Mon May 4 22:49:32 CEST 2015 armv7l GNU/Linux
 
kmod-mwlwifi driver
 3.18.11+10.2.8.5.p0-20150422-1

If you set the 5Ghz to 160Mhz channel width. It caused the 5Ghz to be set as "Client" instead of "Master" disabling the 5Ghz.

**Comment by yuhhaurlin** [comment]
This chip does not suport 160 Mhz.

**Comment by gufus** [comment]
Okay, Thanks.

I'll drop a note to kaloz.

	Regards
