### ISSUE TITLE
WDS support for Rango (WRT3200ACM)

### ISSUE THREAD

**Issue by yuhhaurlin** [kaloz/mwlwifi#182]
Support WDS via OpenWRT 4 address solution.

**Comment by BrainSlayer** [comment]
does it mean wds sta / ap 4 address mode works now?

**Comment by yuhhaurlin** [comment]
No. I create this one to track This job

**Comment by GillyMoMo** [comment]
What's the status on this? What part of the code do I need to look at and possibly compare it to get this working right?

**Comment by yuhhaurlin** [comment]
This feature won't be done quickly.

**Comment by gufus** [comment]
@yuhhaurlin 

Maybe soon...

Please :-)

**Comment by yuhhaurlin** [comment]
Busy on other projects. Will implement this feature later. Sorry.

**Comment by gufus** [comment]
Okay.

Thanks, hopefully WDS is on top of your todo pile. :-)

- Regards

**Comment by ad019** [comment]
Can we expect something will be done on WDS and MU-MIMO this year? 
Or will Marvell keep pushing these features into the future and keep dangling a carrot that they are "committed" to this product?

**Comment by yuhhaurlin** [comment]
Sure.

**Comment by GillyMoMo** [comment]
Like with the 1900ACv1, it'll take time before this matures. I remain in no rush for this. As before we are at the whim of Marvell as usual.

**Comment by tapper82** [comment]
How long do we have to wait? Is any work being dun on this driver any more?

**Comment by ad019** [comment]
Not long now I think. Now that the 32X is out and being based on OpenWRT, probably has the same driver as 3200acm, Marvell will have to resolve the pending issues.

**Comment by BrainSlayer** [comment]
@ad019 the wrt32x uses openwrt but does not use mwlwifi. it still uses the good old propertiery driver which has been used in the original firmware for the wrt3200acm

**Comment by yuhhaurlin** [comment]
Yes. WRT32x uses proprietary driver. Mwlwifi is mac80211 driver and it can support all Marvell chips for WRT series driver. It is open source. Proprietary driver of WRT32x is dedicated driver for 88W8964. It is up to you to decide to use which driver.

**Comment by yuhhaurlin** [comment]
In fact, it is the same driver used by stock firmware and Marvell ports it to work with OpenWrt.

**Comment by BrainSlayer** [comment]
@yuhhaurlin i have seen that the firmware blob in this WRT32X for the chipset is a little bit newer and has slightly different code in it. is there anything changed in it which is usefull for mwlwifi? i'm testing this binary right now with mwlwifi on my wrt3200acm

**Comment by yuhhaurlin** [comment]
No. Mwlwifi is mac80211 driver, it can support more features. BTW, for previous memory shortage problem,   it is fixed by mwlwifi first.

**Comment by BrainSlayer** [comment]
i was talking about the W8889.bin file which is slightly different in the WRT32X version.

**Comment by yuhhaurlin** [comment]
I have no idea about W8889.bin! If WRT32X uses this binary, then maybe I am wrong. Sorry.

**Comment by BrainSlayer** [comment]
nono. it uses the propertiery driver, but for sure it uses the same  firmware binary format like mwlwifi, but the WRT32X has a newer version of it. but doesnt look much different from the content

**Comment by yuhhaurlin** [comment]
Yes. There is new version of firmware for 88W8964.

**Comment by BrainSlayer** [comment]
yea. sorry typo from my side. do you know if there is any change in this firmware? or lets say do you know whats has been changed?

**Comment by yuhhaurlin** [comment]
Our QA is pretty busy. If community wants to test new version of firmware, I can do basic test next week and push it to here for you to do test.

**Comment by BrainSlayer** [comment]
i already tested it. so far it works. no negative effects here in my current environment.

**Comment by yuhhaurlin** [comment]
What is the version number?

**Comment by BrainSlayer** [comment]
for the wifi firmware or what?

**Comment by yuhhaurlin** [comment]
Firmware.

**Comment by BrainSlayer** [comment]
8006.img version: B4.18.01 Jun  2 2017 04:52:13 Copyright (c) 2007, 2009-2015 by Cisco Systems, Inc

**Comment by BrainSlayer** [comment]
same version string has in the previous version

**Comment by BrainSlayer** [comment]
driver reports
[    4.031097] ieee80211 phy0: fw download start
[    4.031101] ieee80211 phy0: ddr init: download start
[    4.031479] ieee80211 phy0: ddr init: download complete
[    4.168238] ieee80211 phy0: FwSize = 447616 downloaded Size = 447616 curr_ite                                                                                                                                                             ration 65522
[    7.037377] ieee80211 phy0: fw download complete
[    7.050209] ieee80211 phy0: pcmd = de62c000
[    7.067420] ieee80211 phy0: firmware version: 0x9030008
[    7.295385] ieee80211 phy0: firmware region code: 10
[    7.325027] ieee80211 phy0: 2G enabled, 5G enabled
[    7.329845] ieee80211 phy0: 4 TX antennas, 4 RX antennas
[    7.335255] pci 0000:00:02.0: enabling device (0140 -> 0142)
[    7.341035] ieee80211 phy1: priv->pcmd_buf = da3fc000  priv->pphys_cmd_buf =                                                                                                                                                              1a3fc000
[    7.347674] ieee80211 phy1: fw download start
[    7.347679] ieee80211 phy1: ddr init: download start
[    7.348060] ieee80211 phy1: ddr init: download complete
[    7.487829] ieee80211 phy1: FwSize = 447616 downloaded Size = 447616 curr_ite                                                                                                                                                             ration 65527
[    8.681374] ieee80211 phy1: fw download complete
[    8.694183] ieee80211 phy1: pcmd = da3fc000
[    8.710395] ieee80211 phy1: firmware version: 0x9030008
[    8.848381] ieee80211 phy1: firmware region code: 10
[    8.870970] ieee80211 phy1: 2G enabled, 5G disabled
[    8.875894] ieee80211 phy1: 4 TX antennas, 4 RX antennas

**Comment by yuhhaurlin** [comment]
cat /sys/kernel/debug/ieee80211/phy0/mwlwifi/info.

**Comment by BrainSlayer** [comment]
driver name: mwlwifi
chip type: 88W8964
hw version: 7
driver version: 10.3.4.0-20170810
firmware version: 0x09030008
power table loaded from dts: no
firmware region code: 0x10
mac address: 14:91:82:b9:16:d4
2g: enable
5g: enable
antenna: 4 4
irq number: 46
ap macid support: 0000ffff
sta macid support: 00010000
macid used: 00010000
radio: enable
iobase0: e0c00000
iobase1: e0e80000
tx limit: 1024
rx limit: 16384

**Comment by yuhhaurlin** [comment]
All right, I will push 9.3.0.8 to here next week. However, it won't be tested by our QA.

**Comment by yuhhaurlin** [comment]
@BrainSlayer Please help to test version 9.3.0.8 of 88W8964 firmware via https://drive.google.com/open?id=0B3qLWtcWB9EdWU9vM09QRy1Bc00.

**Comment by thagabe** [comment]
Wait, since the 32X will run on openwrt can we port the killer engine to lede on the 3200acm? Gamer here.

**Comment by rs-se** [comment]
You should ask in LEDE forums, this is for the Wi-Fi driver only.

**Comment by BrainSlayer** [comment]
@thagabe there is no killer engine. the so called killer feature is just a set of qos rules. i checked this already

**Comment by s-pimenta** [comment]
@thagabe Marketing...

**Comment by eduperez** [comment]
@yuhhaurlin : If you push the source code for 9.3.0.8, in a branch here, or even in a fork, I could make packages for the stable version of LEDE, so more people can test the new drivers, without having to reinstall the whole system from scratch.

**Comment by yuhhaurlin** [comment]
9.3.0.8 is binary firmware of 88W8964. I will do basic test and push to here. LEDE is pretty stable now.

**Comment by yuhhaurlin** [comment]
This is not related to WDS.

**Comment by tapper82** [comment]
Is any one still working on this driver? Any news any update? the people would like to no.

**Comment by nitroshift** [comment]
@yuhhaurlin 

Been running the 9.3.0.8 firmware on LEDE for over a week now without any issues. You can commit it in the official repo.

nitroshift

**Comment by yuhhaurlin** [comment]
Thanks. I will check in on10/11.

**Comment by spamtree** [comment]
Question:

I see this is  still listed as open. Was WDS implemented?

Thanks

**Comment by yuhhaurlin** [comment]
This feature is under development now.

**Comment by ad019** [comment]
Does this development also include MU-MIMO?

**Comment by yuhhaurlin** [comment]
No. MU-MIMO will be done later.

**Comment by adamcarter1** [comment]
Regarding mu-mimo. 

Would Be nice if it was done sooner.

Let me just ask this.  Perhaps you can help me understand.
The linksys wrt 32x uses a firmware loosely based on “open wrt”. Not a standard linksys firmware.
Open wrt pretty much gave birth to lede, which you use to test all this stuff.
The linksys 32x has mu-mimo.  Ergo Can’t any of that info from the marvell people who made the driver or firmware or whatever for 32x, be usefull in getting it to work for dd-wrt and/ or lede. 

Am i taking crazy pills?

**Comment by yuhhaurlin** [comment]
Sorry. I have no idea about wrt32x.

**Comment by adamcarter1** [comment]
Sorry, wasn’t trying to be rude or pushy. i was under the assumption you work for marvell. 

What i know about the 32x is this
Their processor, a marvell processor, the same processor is in both the 3200acm and the 32x.
The 32x uses an open wrt based firmware, they have things like mu-mimo working or at least thats what they claim on the box. 
If that is true, someone at marvell has already written the mu-mimo code for an open wrt based system with this processor.
Why are we reinventing the wheel here. 

If you do work for marvell. I’m not asking you to release sensitive wrt-32x information... just perhaps  send a quick internal work email to colleagues who worked on the marvell driver for the 32x to get some of this stuff working. 


I and others appreciate your time.

**Comment by yuhhaurlin** [comment]
Driver of WRT32x is not mwlwifi. It takes time to port MU-MIMO to mwlwifi.

**Comment by BrainSlayer** [comment]
the wrt32x and the wrt3200acm are identical devices. just firmware and price is different. mu-mimo is working for the factory firmwares for wrt3200acm and wrt32x. no difference here. but the driver used in these factory firmwares is not open source and propertiery. you cannot copy just the code to the opensource mwlwifi driver. first it would be a license problem, second the driver is totally different and does not make use of mac80211 etc. so even the code for mu-mimo would be totally different in mwlwifi once its done. the information exist, yes and marvell makes use of it to implement the same feature into mwlwifi. but its a work from scratch

**Comment by yuhhaurlin** [comment]
@BrainSlayer Thanks.

**Comment by ad019** [comment]
@yuhhaurlin do you have scheduled time period in mind for MU-MIMO?

**Comment by adamcarter1** [comment]
Wow, so in essence  the 32x even though the firmware is quite unlike the 3200 firmware “a very resorceful person on the dd-wrt firmware who decoded it, said , looking at the files that it was loosely based on  “open wrt” so even though it is loosly based on that... the driver they use is specifically designed to work only with the propriatary firmware.

Seems to me that it is very inefficient, way to do things. 

As far as licensing issues. Isn’t marvell making the drivers for all firmwares? Who would they have to pay? themselves?

**Comment by aaron1959** [comment]
The key word is loosely.

**Comment by BrainSlayer** [comment]
@adamcarter1 : first i was the one who decoded the firmware and analysed it too look for the so called gaming feature which was just a few lines of qos script. and no the propertiery marvell driver can work with any firmware. it doesnt matter if its openwrt or anything else. its just a driver and its not just loosely based on openwrt, the firmware is 100% openwrt. in fact a guy known to me from the old openwrt community wrote the firmware. or lets say i found indications that he wrote parts of it

**Comment by adamcarter1** [comment]
@BrainSlayer  Well april also looked at it too, she may have been the first after it was publically available. Forget her handle

Lol, what a close knit community we have... 

Open wrt, lede, dd-wrt. 
From my extremely limited knowledge.
32x is as u say 100% open wrt, according to lede’s website lede is a Linux operating system based on OpenWrt.

Again i get it all this stuff is different.... for all intensive purposes.

But comparing just oem firmwares.... would i be correct in saying that when looking at the oem  3200 firmware vs oem 32x firmware and comparing them to lede and dd-wrt.
 that  lede/dd-wrt  have more in common with the oem 32x firmwarw than they do with the oem 3200acm firmware?

**Comment by BrainSlayer** [comment]
dont know her from the dd-wrt community. but good to know that there are girls around :-)
lede is a fork of openwrt and openwrt is dead. right now they want to rename lede back to openwrt. just curious things are going on. i could tell you more about the background but this would turn your world upside down and some people would not like that i talk about some background secrets. 
but to your question. lede/openwrt has more in common with the wrt32x firmware and almost nothing in common with the wrt3200acm. dd-wrt has nothing in common with both of them since dd-wrt has a different architecture and is mainly based and written in C code instead of shell scripts and lua. but we use the same applications packages and  share alot of kernel patches and enhancements. so dd-wrt and lede is also working together in background for making things better

**Comment by yuhhaurlin** [comment]
I commit updated firmware 9.3.2.1 and code for WDS client. WDS AP is still under development. If you want, you can test it. However, this is pre-release.

**Comment by BrainSlayer** [comment]
cool. let me prepare a testbuild

**Comment by BrainSlayer** [comment]
testimages for wds station support ftp://ftp.dd-wrt.com/others/test/linksys-wrt3200acm/

**Comment by spamtree** [comment]
@yuhhaurlin Thanks

That explains why attempt last week to setup WDS totally failed. Anyway got relayd working and that works fine for what I am doing. 

However, will WDS be compatible with other routers  using 4-address  mode? Can I use another router like an atheros router?  Got a little confused when reading about WDS. I thought it didn't work was because I was using an atheros router  and wrt3200acm router that is why I used relayd.

**Comment by BrainSlayer** [comment]
@spamtree thats the plan. just test it. the current mwlwifi tree should be wds sta capable and i provided a dd-wrt testimage. for lede/openwrt you have to compile your own testimage

**Comment by eduperez** [comment]
@spamtree I am building updated packages of the mwlwifi driver, to be installed on top of stable LEDE versions, at https://github.com/eduperez/mwlwifi_LEDE/; you do not need to build them yourself.

(I just mentioned this in another thread, hope this does not annoy anyone, or is seen as spam)

**Comment by aaron1959** [comment]
@eduperez  I saw that other one. I thank you for keeping those folks updated.

**Comment by yuhhaurlin** [comment]
@spamtree 
1. For normal station mode, you need to use relayd.
2. Yes. It can work with other device running as OpenWrt 4 address WDS. However only WDS client works for WRT3200ACM now.

**Comment by yuhhaurlin** [comment]
@eduperez
Thanks for your help.

**Comment by spamtree** [comment]
@yuhhaurlin 
I understand now. Thanks for the explanation. 
@eduperez 
Will driver work with davidc502 builds? Thanks

**Comment by eduperez** [comment]
@spamtree No, LEDE / OpenWrt will only install kernel modules when they
match the exact same kernel version and compilation parameters. However,
@davidc502 has already updated his builds.

**Comment by eduperez** [comment]
@yuhhaurlin Shall we report bugs about WDS here, and help you? Or is it
still too soon, and we will disturb your workflow?

**Comment by yuhhaurlin** [comment]
Yes. You can report problem here.

**Comment by InkblotAdmirer** [comment]
Thanks for working on the WDS implementation.  I have a Rango configured for WDS STA mode on both 2.4G and 5G, it's been running almost a day now -- it wirelessly bridges a LAN and guest network.

Speed is great (5G link:
[SUM]   0.00-20.03  sec  1.37 GBytes   588 Mbits/sec                  receiver

No issues to note on either band so far!  I'm happy to run any tests, especially if any are necessary to get WDS AP mode enabled -- this will allow me to finalize my envisioned network.  Thanks again!

**Comment by wwtk** [comment]
Hello and thanks for the efforts!

I tried WDS mode betwen R8000 AP and 3200ACM STA but it keeps dropping and reconnecting.

`[   69.256209] wlan0: authenticate with e8:fc:af
[   69.357326] ieee80211 phy0: change: 0x100
[   69.370379] ieee80211 phy0: change: 0x100
[   69.383425] ieee80211 phy0: change: 0x42
[   69.485316] ieee80211 phy0: change: 0x2
[   69.489218] wlan0: send auth to e8:fc:af: (try 1/3)
[   69.495574] wlan0: authenticated
[   69.501333] wlan0: associate with e8:fc:af: (try 1/3)
[   69.508260] wlan0: RX AssocResp from e8:fc:af: (capab=0x11 status=0 aid=2)
[   69.591302] ieee80211 phy0: change: 0x2
[   69.595166] wlan0: associated
[   69.598181] wlan0: Limiting TX power to 30 (30 - 0) dBm as advertised by e8:fc:af:
[   72.645788] wlan0: deauthenticated from e8:fc:af:f7: (Reason: 2=PREV_AUTH_NOT_VALID)
[   72.721405] ieee80211 phy0: staid 1 deleted
[   72.730422] ieee80211 phy0: staid 2 deleted`

I compiled this driver, is it correct one?
`driver name: mwlwifi
chip type: 88W8964
hw version: 7
driver version: 10.3.4.0-20171129
firmware version: 0x09030201
power table loaded from dts: no
firmware region code: 0x0
mac address: 60:38:e0:
2g: disable
5g: enable
antenna: 4 4
irq number: 45
ap macid support: 0000ffff
sta macid support: 00010000
macid used: 00010000
radio: enable
iobase0: e1000000
iobase1: e1280000
tx limit: 1024
rx limit: 16384`

**Comment by BrainSlayer** [comment]
the netgear r8000 has a broadcom chipset and has no wds ap support

**Comment by wwtk** [comment]
crap, thanks :(  I guess its time to shop for a new tri band router that does grrrr

**Comment by BrainSlayer** [comment]
you need to check for qca chipsets and whats more important. it must be capable of running openwrt/lede or dd-wrt

since the vendor firmwares normally do not support wds ap / wds sta features

**Comment by wwtk** [comment]
yes, thanks for those tips I appreciate them.  It appears to be a tall order though as most bleeding edge hardware has limited support open firmware wise until they mature which is understandable.

tew828dru does have vendor wds support and it appears some dd-wrt support though I personally prefer lede only because I like the more linuxish approach to storing of the config files.  In other words vi and I are long time friends.

I will try searching for qca chipsets and see what turns up, thanks again!

**Comment by BrainSlayer** [comment]
that itsnt true. even bleeding hardware hardware is well supported by opensource firmwares. the tew828 may run with lede. lede has support for the chipset, just dont know  if there is direct support for it. the tew828 has also the worst chinese build quality i have ever seen.

**Comment by spamtree** [comment]
Finally tested wds mode. Much easier to setup than relayd. 

wrt3200acm Worked perfect in "station" mode with atheros ar7161 as "ap" mode using 2.4 and 5 bands. Speed was excellent but the routers where only about 14cm apart. 

Looks like a minor bug in the atheros wds implementation because the wds station does not showup in  ifconfig but still works fine.  I have seen this reported elsewhere. On the wrt3200acm ifconfig reports wds station as 'wlan1.sta1'.

Thanks!

**Comment by yuhhaurlin** [comment]
@spamtree 
Yes. The setting for OpenWrt 4 address WDS is pretty simple via WEB GUI. For AP, you only need to choose "Access Point (WDS)" instead of "Access Point". For Client, you only need to create an interface "Client (WDS)" and set SSID and open/security mode just like the setting of AP (WDS). You also need to let this interface join bridge.
After WDS connection is established, AP (WDS) will create a virtual interface to work with Client (WDS). All devices hooked to LAN can communicate with each other due to this WDS link.
Another good thing is that AP (WDS) can still allow normal client to connect to it.

**Comment by BrainSlayer** [comment]
@spamtree : our description doesnt sound true. on station side the interface has the wlan1 name and on wds ap side it should be named wlan1.staX for each connected wds station. so there is no bug in the atheros wds implementation. ath9k and ath10k behaves exact like this.

**Comment by spamtree** [comment]
@yuhhaurlin and @BrainSlayer 

Thanks for the information. That was correct information and the artheros does not have luci installed. WDS works perfectly but the WDS interface does not show up when listing the interfaces on the artheros based router there is no wlan1.staX. Anyway I got that information about setting up 4 address wds from 
https://wiki.openwrt.org/doc/recipes/atheroswds
It states in the howto that " (Note: when tested on Barrier Breaker, there was no new interface created, neither on the AP nor on the STA, despite WDS working properly)."

 My artheros router is pretty old, so it is not a problem that it does not have wlan1.staX in the output for "ip" or "ifconfig", it still works perfectly.  My artheros router was made in 2012 so it is pretty old and that could be the problem why all the interfaces don't show but it works perfectly with WDS "station" or "ap". 
It uses the ath9k modules. 

I guess I should not have mentioned the artheros at all (sorry about that). Only use it for testing or as a relayd when I am in the back yard. 

Lets stick to the wrt3200acm and so far everything works as expect with station mode WDS and output from "ip" and "ifconfig" both show the wlan1.staX interface. 

Now correct me if I am wrong but I thought the wrt3200acm only supports wds "station" mode now and that wds "ap" is coming later. 

Thanks this is working great!

**Comment by yuhhaurlin** [comment]
Yes. I work on WDS AP now.

**Comment by BrainSlayer** [comment]
@yuhhaurlin can you explain why the mwlwifi driver creates a wlan1.sta0 interface in wds station mode? this isnt neccessary. this is only required in wds ap mode and was introduced in mac80211 as solution for inter station communication for broadcast packets.

**Comment by spamtree** [comment]
@BrainSlayer 
Do you think this could have something to do with LEDE?

**Comment by BrainSlayer** [comment]
@spamtree no, the sub interfaces .staX are created by mac80211 and lede as well as dd-wrt are almost in sync. we use the same driver base.

**Comment by yuhhaurlin** [comment]
@BrainSlayer Only WDS AP will create this kind of virtual interface. If you add wds_sta to configuration file of hostapd, hostapd will create this kind of interface if WDS client is connected. For WDS client, it uses the original interface.

**Comment by BrainSlayer** [comment]
@yuhhaurlin: i know. i just took the comment from "spamtree" since he said it creates a .staX interface in station side which is unusual for me and not correct. this is why i'm asking

**Comment by yuhhaurlin** [comment]
@BrainSlayer I think he means WDS AP. WDS client will use the original interface created for it.

**Comment by BrainSlayer** [comment]
i thought that, thats why i reasked him about the behaviour. but he wrote again that its on station side

**Comment by spamtree** [comment]
I understand completely now. I will test again and report back with more output. Thanks.

**Comment by spamtree** [comment]
I was completely wrong. @BrainSlayer you were correct. 

This is from the netgear in wds ap mode. 

root@netgear:~# ifconfig wlan0.sta1
wlan0.sta1 Link encap:Ethernet  HWaddr 04:A1:51:9E:36:6E  
          inet6 addr: fe80::6a1:51ff:fe9e:366e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5587 errors:0 dropped:0 overruns:0 frame:0
          TX packets:177 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:623142 (608.5 KiB)  TX bytes:31337 (30.6 KiB)

This is the output from the wrt3200acm in wds station mode. 
wlan1     Link encap:Ethernet  HWaddr 60:38:E0:BA:DC:21  
          inet6 addr: fe80::6238:e0ff:feba:dc21/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:346 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5687 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:44190 (43.1 KiB)  TX bytes:783720 (765.3 KiB)

*******************************************************************************************

There is no "wlan1.staX" on the wrt3200acm in wds station mode.  To put it bluntly my previous posting was incorrect. 

I will be more careful in the future when reviewing and posting information and I apologize for posting inaccurate information.

**Comment by yuhhaurlin** [comment]
BTW, you can reference following links:
https://wireless.wiki.kernel.org/en/users/documentation/iw (Using 4-address for AP and client mode)
https://wiki.openwrt.org/doc/howto/clientmode

**Comment by spamtree** [comment]
@yuhhaurlin Thanks learning all the time.

**Comment by yuhhaurlin** [comment]
I commit code related to WDS AP. In order to support it, firmware should be updated to 9.3.2.2. This is pre-release. I will still do more tests. If you like, you can help to test it. I plan to release code to QA for test late this week or early next week. If you find any problems, please let me know.

**Comment by BrainSlayer** [comment]
thx, let me prepare a test image

**Comment by BrainSlayer** [comment]
new dd-wrt build for wds ap support at ftp://ftp.dd-wrt.com/others/test/linksys-wrt3200acm/

**Comment by aaron1959** [comment]
@BrainSlayer   Will start testing with logging.

**Comment by eduperez** [comment]
Updated `.ipk` package for LEDE 17.01.4 available at
https://github.com/eduperez/mwlwifi_LEDE/releases/tag/c96d1ed

**Comment by 05dyna** [comment]
@BrainSlayer WDS AP & WDS Station are working nicely here with dd-wrt, the only mirror issue I'm seeing so far NTP is not working on WDS Station but is updating the WDS AP.  I realize this is not the focos of the thread but one quick question if I could. I'm using ovpn so do you think this is just normal and the vpn tunnel is preventing the Station from connecting to the NTP?  

In any case a Big Thank You, to you @yuhhaurlin and everyone else who have kept the wrt3200 alive. Off for more testing....

**Comment by BrainSlayer** [comment]
@05dyna missconfigured? ntp works on my wrt3200acm in station mode. router time is correct. so check if you have configured your correct gateway and dns server. otherwise it can't work for sure since the default ntp server is resolved by its name. same for custom one and for openvpn. ahm you did not include any details about your setup here. your tunnel can be anything between 2 devices and i dont know even what is connected to where here and how your routes and nat rules are. and you need a nat rule for openvpn. anway. i use it as plain wds sta. it has a gateway and dns configured. ntp. if you have something custom including openvpn, please fix your custom setup to get ntp working. the router must be able to connect to its destination. if this is not guaranteed, its not working. if your openvpn is connecting too late for instance ntp will fail on first try. then you just need to wait for next ntp update. this may take a while for sure

**Comment by 05dyna** [comment]
@BrainSlayer -thanks for the reply back. I don’t want to hijack the thread with an issue I likely caused.  
You said it should work so that’s good enough for me,  I’ll default it and try it again...

**Comment by spamtree** [comment]
LEDE user success with WDS on WRT3200 to WRT3200 using 2.4 Ghz band and good speeds for my network. This WDS setup can max out my comcast connection (comcast speed 75 Mbits/sec). It worked fine with my netgear but the speeds were ranging between 8-10 Mbits/sec while 1 foot from the WRT3200. The netgear was even slower with relayd. The only thing I have not been able to figure out and this is probably an LEDE setup problem is  how to pass ipv6 over the wds connection with WRT3200 to WRT3200. I had no problem with ipv6 using the netgear to WRT3200. Will have to check that out later. ntp works fine also. 

Below are some iperf stats. Don't know if this is good or bad. Routers were about 30 feet apart with 4 walls separating the routers. 

iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50486
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.2 sec   186 MBytes   154 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50488
[  4]  0.0-10.1 sec  88.9 MBytes  74.0 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50490
[  4]  0.0-10.1 sec   144 MBytes   120 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50492
[  4]  0.0-10.3 sec   104 MBytes  84.8 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50494
[  4]  0.0-10.1 sec  97.6 MBytes  81.2 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50496
[  4]  0.0-10.1 sec   129 MBytes   107 Mbits/sec
[  4] local 192.168.100.1 port 5001 connected with 192.168.100.193 port 50500
[  4]  0.0-10.1 sec   157 MBytes   131 Mbits/sec

**Comment by gxgani** [comment]
@spamtree could I know which LEDE build are you using?

**Comment by yuhhaurlin** [comment]
I change the version of driver to 10.3.4.0-20171214 and release this version of code to our QA for verification. This feature is done. I close this issue. If you find any problems, you can create new issue to track it.
