### ISSUE TITLE
Broken tx rate a signal wrt3200acm

### ISSUE THREAD

**Issue by Ansuel** [kaloz/mwlwifi#187]
With the last commit i have this problem... every device have only 6mbps or 1 mbps from luci interface. If i check the actual speed from the device, i gets the correct one. Where is the problem? 

6mbps for 5ghz connection
1mbps for 2.4

Here a screen of the problem https://s13.postimg.org/qhlxr939z/Cattura.png

**Comment by yuhhaurlin** [comment]
I don't think so. I test the code via LEDE image. WEB GUI can show tx rate without problem. You need to run traffic between AP and Client.

**Comment by yuhhaurlin** [comment]
BTW, if you can get tx/rx rates via "iw wlan0/wlan1 station dump", it means the driver is all right.

**Comment by yuhhaurlin** [comment]
![image](https://user-images.githubusercontent.com/4169364/27952750-fd06cbf8-633b-11e7-9b82-131b6b21ad70.png)

**Comment by Ansuel** [comment]
well.... if i try 
iw wlan0 station dump nothing appear
with iw wlan1 station dump
Station 84:ba:3b:07:53:07 (on wlan1)
        inactive time:  4294825206 ms
        rx bytes:       169993
        rx packets:     463
        tx bytes:       161798
        tx packets:     418
        tx retries:     0
        tx failed:      0
        rx drop misc:   0
        signal:         0 dBm
        signal avg:     0 dBm
        tx bitrate:     1.0 MBit/s
        rx bitrate:     1.0 MBit/s
        authorized:     yes
        authenticated:  yes
        associated:     yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
        DTIM period:    2
        beacon interval:100
        short preamble: yes
        short slot time:yes
        connected time: 132 seconds

**Comment by yuhhaurlin** [comment]
![image](https://user-images.githubusercontent.com/4169364/27952822-3ceba860-633c-11e7-94c4-1814c169a208.png)

**Comment by Ansuel** [comment]
Will check my device sorry.

**Comment by yuhhaurlin** [comment]
inactive time: 4294825206 ms => Please ping AP.

**Comment by Ansuel** [comment]
Ok my problem... now it works
