### ISSUE TITLE
With this driver : num of SSID limited to 8 instead of 16 (Linksys WRT 1900ACS)

### ISSUE THREAD

**Issue by delandtj** [kaloz/mwlwifi#190]
Running on a linksys wrt 1900 acs, where I had 12, with the previous release.
Wireless never came back up...
removed 4 -> things worked again
Needless to say that the main reason for using these AP's is now gone :-(

**Comment by BrainSlayer** [comment]
this is related to the new address fix which limited it to 8 devices. the fix for that issue is easy. let me do a short patch for you. but its up to you to compile it by yourself and try it out

**Comment by BrainSlayer** [comment]
mmh. i reviewed the code. i was wrong. its limited to 16

**Comment by BrainSlayer** [comment]
and i'm talking about current todays driver release

**Comment by BrainSlayer** [comment]
the problem i see is that all the recent changes are not related to WRT1900ACS but only to the WRT3200ACM chipset

**Comment by BrainSlayer** [comment]
so if you're using lede or openwrt, the problem source is maybe not just the driver

**Comment by yuhhaurlin** [comment]
Yes. I close this one.

**Comment by yuhhaurlin** [comment]
The BSSID assignment is only used for WRT3200ACM (88W8964) and it can use 16 VAPs now.

**Comment by delandtj** [comment]
I could use +8 SSIDs on lede 17.01.0, but apparently the mwlwifi driver is introduced in 17.01.=>1 and then 8+ SSIDs  stopped working on WRT1900ACS ... so I would have thought it's the driver somewhere.

**Comment by kylejvrsa** [comment]
@delandtj I think you should have a look at the lede changelog for the specific version.
https://lede-project.org/releases/17.01/start
