### ISSUE TITLE
Crash while streaming audio

### ISSUE THREAD

**Issue by jacksonatl** [kaloz/mwlwifi#193]
Running 20170711 driver on LEDE, playing streaming audio for about 40 minutes reliably crashes wifi. Seems similar to #192 but 5G signal.

# uname -a
Linux router 4.4.74 #0 SMP Sat Jul 8 20:55:19 2017 armv7l GNU/Linux
# cat /sys/kernel/debug/ieee80211/phy0/mwlwifi/info

driver name: mwlwifi
chip type: 88W8964
hw version: 7
driver version: 10.3.4.0-20170711
firmware version: 0x09030007
power table loaded from dts: no
firmware region code: 0x10
mac address: <commentedout>
2g: disable
5g: enable
antenna: 4 4
irq number: 105
ap macid support: 0000ffff
sta macid support: 00010000
macid used: 00000001
radio: enable
iobase0: e0e00000
iobase1: e1080000
tx limit: 1024
rx limit: 16384

Crash:
[  741.242092] ------------[ cut here ]------------
[  741.246787] WARNING: CPU: 0 PID: 0 at compat-wireless-2017-01-31/net/mac80211/rx.c:4221 ieee80211_rx_napi+0x160/0x8e8 [mac80211]()
[  741.258586] Rate marked as a VHT rate but data is invalid: MCS: 0, NSS: 0
[  741.265416] Modules linked in: pppoe ppp_async iptable_nat ath9k pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE ath9k_common xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CLASSIFY slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt ath9k_hw ath sch_cake nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress mwlwifi mac80211 cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables ifb ohci_platform ohci_hcd gpio_button_hotplug
[  741.349775] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.4.74 #0
[  741.355719] Hardware name: Marvell Armada 380/385 (Device Tree)
[  741.361671] [<c0027d80>] (unwind_backtrace) from [<c00244a4>] (show_stack+0x10/0x14)
[  741.369450] [<c00244a4>] (show_stack) from [<c0219f64>] (dump_stack+0x8c/0xa0)
[  741.376704] [<c0219f64>] (dump_stack) from [<c0034f08>] (warn_slowpath_common+0x94/0xb0)
[  741.384828] [<c0034f08>] (warn_slowpath_common) from [<c0034f54>] (warn_slowpath_fmt+0x30/0x40)
[  741.393601] [<c0034f54>] (warn_slowpath_fmt) from [<bf0a80ac>] (ieee80211_rx_napi+0x160/0x8e8 [mac80211])
[  741.403240] [<bf0a80ac>] (ieee80211_rx_napi [mac80211]) from [<bf10eff8>] (pcie_rx_recv_ndp+0x5d0/0xa6c [mwlwifi])
[  741.413640] [<bf10eff8>] (pcie_rx_recv_ndp [mwlwifi]) from [<c0038340>] (tasklet_action+0x8c/0x104)
[  741.422724] [<c0038340>] (tasklet_action) from [<c00384dc>] (__do_softirq+0xd0/0x20c)
[  741.430586] [<c00384dc>] (__do_softirq) from [<c00388d0>] (irq_exit+0xac/0xd4)
[  741.437838] [<c00388d0>] (irq_exit) from [<c006ffec>] (__handle_domain_irq+0x9c/0xac)
[  741.445702] [<c006ffec>] (__handle_domain_irq) from [<c00094dc>] (gic_handle_irq+0x54/0x94)
[  741.454087] [<c00094dc>] (gic_handle_irq) from [<c000a614>] (__irq_svc+0x54/0x70)
[  741.461598] Exception stack(0xc0677f48 to 0xc0677f90)
[  741.466670] 7f40:                   00000001 00000000 00000000 c000b4c0 c0676000 c0678498
[  741.474881] 7f60: c0571d48 00000000 c0670224 c0677fa0 00000000 c0673118 60000013 c0677f98
[  741.483090] 7f80: c0021534 c0021538 60000013 ffffffff
[  741.488161] [<c000a614>] (__irq_svc) from [<c0021538>] (arch_cpu_idle+0x34/0x50)
[  741.495590] [<c0021538>] (arch_cpu_idle) from [<c0068b7c>] (cpu_startup_entry+0x148/0x210)
[  741.503895] [<c0068b7c>] (cpu_startup_entry) from [<c0633d50>] (start_kernel+0x458/0x464)
[  741.512121] ---[ end trace 580762c26a705714 ]---
[12604.806552] ieee80211 phy0: staid 10 deleted
[15022.387979] ieee80211 phy0: staid 7 deleted
[16835.493963] ieee80211 phy0: staid 7 deleted
[17422.380300] ieee80211 phy0: staid 7 deleted
[23750.325225] ieee80211 phy0: staid 3 deleted
[25461.400195] ieee80211 phy0: staid 1 deleted
[25822.390290] ieee80211 phy0: staid 11 deleted

Sample of logread |grep hostapd
Thu Jul 13 16:08:55 2017 daemon.info hostapd: wlan0: STA <commentedout> WPA: group key handshake completed (RSN)
Thu Jul 13 16:08:55 2017 daemon.info hostapd: wlan0: STA <commentedout> WPA: group key handshake completed (RSN)
Thu Jul 13 16:08:59 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED <commentedout>
Thu Jul 13 16:09:04 2017 daemon.info hostapd: wlan0: STA <commentedout> IEEE 802.11: deauthenticated due to local deauth request
Thu Jul 13 16:18:55 2017 daemon.info hostapd: wlan0: STA <commentedout> WPA: group key handshake completed (RSN)
Thu Jul 13 16:18:55 2017 daemon.info hostapd: wlan0: STA <commentedout> WPA: group key handshake completed (RSN)

**Comment by yuhhaurlin** [comment]
This is issue #186, Please check 10.3.4.0-20170713.
