### ISSUE TITLE
Broadcast traffic dropped (follow-on to issue #36)

### ISSUE THREAD

**Issue by pdemarco925** [kaloz/mwlwifi#195]
This is a followup to Issue #36 that was closed a couple days ago.

Using the image you provided in that issue. I'm still having problems.

I have a number of airport express devices, I have one hardwired to the WRT3200ACM it is creating its own wireless network and has 2 other airport express devices as clients. These all work fine. 
My last airport express is on a WRT3200ACM wireless channel, and after a period of time it keeps becoming unreachable.

For some reason arping doesn't receive any replies from anything on my network (maybe I'm not using it correctly).
I can ping the problem device when I'm ON the WRT3200ACM, but I can't ping it from another wireless client.

Here is some information from the syslog on the device I'm having issues with. 
Sat Jul 15 11:29:30 2017 daemon.info hostapd: wlan0: STA 58:1f:aa:e7:cd:41 IEEE 802.11: authenticated
Sat Jul 15 11:29:30 2017 daemon.info hostapd: wlan0: STA 68:c9:0b:91:8d:10 IEEE 802.11: authenticated
Sat Jul 15 11:34:14 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 58:1f:aa:e7:cd:41
Sat Jul 15 11:34:14 2017 daemon.info hostapd: wlan0: STA 58:1f:aa:e7:cd:41 IEEE 802.11: disassociated due to inactivity
Sat Jul 15 11:34:15 2017 daemon.info hostapd: wlan0: STA 58:1f:aa:e7:cd:41 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sat Jul 15 11:34:18 2017 daemon.info hostapd: wlan0: STA 58:1f:aa:e7:cd:41 IEEE 802.11: associated (aid 2)

**Comment by yuhhaurlin** [comment]
Because ap_isolate is enabled. You can disable it via /etc/config/wireless.
