### ISSUE TITLE
Information on Readme is obsolate

### ISSUE THREAD

**Issue by mzaferyahsi** [kaloz/mwlwifi#199]
Hi,

From the changes, I can see that the version is updated to 10.3.4.0-20170727 but the readme has a different information. Can you update the readme with relevant version and information?

> How to build mwlwifi with OpenWrt:
> 
> 10.3.0.17-20160601 had been modified to be built with latest backports package "compat-wireless-2016-01-10" without patches.
> 
> a. Modify package/kernel/mwlwifi/Makefile:
> 
> PKG_VERSION:=10.3.0.17-20160601 & PKG_SOURCE_VERSION:=4bb95ba1aeccce506a95499b49b9b844ecfae8a1
> 
> b. Rename package/kernel/mwlwifi/patches to package/kernel/mwlwifi/patches.tmp
> 
> c. make package/kernel/mwlwifi/clean
> 
> d. make V=s (-jx)

**Comment by yuhhaurlin** [comment]
Sorry. README only shows the way to build the driver after which version. Unless the way to build driver is changed, otherwise README won't update this part of document.
