### ISSUE TITLE
5GHz LED non operational

### ISSUE THREAD

**Issue by Millstone50** [kaloz/mwlwifi#201]
Unable to get the 5GHz LED to light unless there's some hackery in the LED config in LuCI. The only thing that flashes is the 2.4GHz LED.

If I try and mess with the 2.4GHz LED at all in the LED config page, the driver quickly crashes. I am able to set the 5GHz LED through this page, however it is not accurate compared to the 2.4GHz LED then.

**Comment by yuhhaurlin** [comment]
It is not job of mwlwifi.
