### ISSUE TITLE
Hi progress of this driver?

### ISSUE THREAD

**Issue by tapper82** [kaloz/mwlwifi#213]
Hi there is a lot of people watching this driver and wanting to know what's going on. Pleas could we get a progress update on what's being worked on?

**Comment by yuhhaurlin** [comment]
Please just report issue here.

**Comment by tapper82** [comment]
So where are we able to ask about this driver? Do you have a forum, a irq a Email list? Would it not be better just to let people know what's going on? In sted of being a arse about it and closing this? :@

**Comment by yuhhaurlin** [comment]
You can get code from:
LEDE:  https://davidc502sis.dynamic-dns.net/
dd-Wrt: Please check related forum.
