### ISSUE TITLE
Connection drops during Group Rekeying

### ISSUE THREAD

**Issue by 65b** [kaloz/mwlwifi#214]
Using 10.3.4.0-20170713 on LEDE build from master ~ Aug 26th. Nothing is logged in dmesg. Device is WRT1900ACS. Clients eventually reconnect, but traffic is lost. Seems identical to #192 and #194. Has a root cause been identified?

**Comment by yuhhaurlin** [comment]
Only specific 11g device has problem. You can check these two issues to get log to see if it is related group rekey.
If yes, you can try to disable group rekey to confirm it is the root cause. After that, you can create new issue for me to check it.
