### ISSUE TITLE
CCMP-256/GCMP/GCMP-256

### ISSUE THREAD

**Issue by BrainSlayer** [kaloz/mwlwifi#219]
@yuhhaurlin i have seen that the firmware binary may support this encryption modes for 88W8964 and it may also not be a big deal to implement it. unfortunatly i'm missing some api informations todo it by myself. is it possible to implement this feature?

**Comment by yuhhaurlin** [comment]
Need to check. I have no idea now.

**Comment by tapper82** [comment]
@yuhhaurlin why does it take you so long to get back to people when they are asking you things?

**Comment by yuhhaurlin** [comment]
These encryption modes are optional. I close this issue first.

**Comment by DanielRieken** [comment]
> These encryption modes are optional. I close this issue first.

@yuhhaurlin does this mean, mwlwifi only supports CCMP, but not CCMP-256/GCMP/GCMP-256?
