### ISSUE TITLE
9.3.8 88W8964 Firmware

### ISSUE THREAD

**Issue by rs-se** [kaloz/mwlwifi#223]
Does anyone know where to find to the 9.3.8 firmware for 88W8964?

All that I can seem to find is 9.3.7.

**Comment by anomeome** [comment]
There is a link in this [thread](https://github.com/kaloz/mwlwifi/issues/182)

**Comment by rs-se** [comment]
Thanks, I figured there was a link somewhere but missed that one.

**Comment by davidc502** [comment]
yuhhaurlin,

Please commit 9.3.8 88W8964 Firmware.

Best Regards,

David

**Comment by yuhhaurlin** [comment]
Yes. I will check in 9.3.0.8 tomorrow (10/11).

**Comment by yuhhaurlin** [comment]
No.WDS needs the modification of driver. It won't be done soon. I will try to support it before 2018.

**Comment by rs-se** [comment]
Latest driver and firmware is very stable, I have done stress testing on
the driver via iperf3 on both firmware and 9.3.8 works much better.

**Comment by yuhhaurlin** [comment]
Good to know that.

**Comment by yuhhaurlin** [comment]
Done.
