### ISSUE TITLE
5G freeze on r5365 trunk build at WRT1900ACS v1

### ISSUE THREAD

**Issue by tangsoft** [kaloz/mwlwifi#233]
It never happens before, 5G signal dead, and I logged into through 2.4G and grabbed some logs may related with:

`Sun Nov 19 18:19:16 2017 daemon.notice hostapd: wlan0: AP-STA-POLL-OK 2c:20:0b:3f:7b:18
Sun Nov 19 18:19:50 2017 daemon.info odhcpd[1210]: Using a RA lifetime of 0 seconds on br-lan
Sun Nov 19 18:19:54 2017 daemon.info odhcpd[1210]: Using a RA lifetime of 0 seconds on br-lan
Sun Nov 19 18:19:57 2017 daemon.info odhcpd[1210]: Using a RA lifetime of 0 seconds on br-lan
Sun Nov 19 18:20:22 2017 daemon.err odhcp6c[1275]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Sun Nov 19 18:20:46 2017 kern.err kernel: [111123.786219] ieee80211 phy0: cmd 0x9125=BAStream timed out
Sun Nov 19 18:20:46 2017 kern.err kernel: [111123.791762] ieee80211 phy0: return code: 0x1125
Sun Nov 19 18:20:46 2017 kern.err kernel: [111123.796421] ieee80211 phy0: timeout: 0x1125
Sun Nov 19 18:20:50 2017 kern.err kernel: [111127.844990] ieee80211 phy0: cmd 0x9125=BAStream timed out
Sun Nov 19 18:20:50 2017 kern.err kernel: [111127.850529] ieee80211 phy0: return code: 0x1125
Sun Nov 19 18:20:50 2017 kern.err kernel: [111127.855165] ieee80211 phy0: timeout: 0x1125
Sun Nov 19 18:22:24 2017 daemon.err odhcp6c[1275]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Sun Nov 19 18:23:11 2017 user.warn ddns-scripts[2174]: tangsoft_ipv4: Updating IP at DDNS provider failed - starting retry 180/0
Sun Nov 19 18:23:57 2017 daemon.info odhcpd[1210]: Using a RA lifetime of 0 seconds on br-lan
Sun Nov 19 18:24:22 2017 daemon.err odhcp6c[1275]: Failed to send DHCPV6 message to ff02::1:2 (Permission denied)
Sun Nov 19 18:24:22 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 2c:20:0b:3f:7b:18
Sun Nov 19 18:24:22 2017 daemon.info hostapd: wlan0: STA 2c:20:0b:3f:7b:18 IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:24:26 2017 kern.err kernel: [111344.679865] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:24:26 2017 kern.err kernel: [111344.686147] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:24:26 2017 kern.err kernel: [111344.690818] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:24:26 2017 kern.err kernel: [111344.695122] wlan0: failed to remove key (0, 2c:20:0b:3f:7b:18) from hardware (-5)
Sun Nov 19 18:24:26 2017 daemon.info hostapd: wlan0: STA 2c:20:0b:3f:7b:18 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:24:30 2017 kern.err kernel: [111348.689616] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:24:30 2017 kern.err kernel: [111348.695572] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:24:30 2017 kern.err kernel: [111348.700262] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:24:33 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 04:52:f3:28:ee:a2
Sun Nov 19 18:24:33 2017 daemon.info hostapd: wlan0: STA 04:52:f3:28:ee:a2 IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:24:37 2017 kern.err kernel: [111355.700855] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:24:37 2017 kern.err kernel: [111355.707081] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:24:37 2017 kern.err kernel: [111355.711717] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:24:37 2017 kern.err kernel: [111355.716013] wlan0: failed to remove key (0, 04:52:f3:28:ee:a2) from hardware (-5)
Sun Nov 19 18:24:37 2017 daemon.info hostapd: wlan0: STA 04:52:f3:28:ee:a2 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:24:37 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:24:41 2017 kern.err kernel: [111359.712860] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:24:41 2017 kern.err kernel: [111359.718817] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:24:41 2017 kern.err kernel: [111359.723456] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:24:41 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:25:28 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 6c:19:c0:78:fa:48
Sun Nov 19 18:25:28 2017 daemon.info hostapd: wlan0: STA 6c:19:c0:78:fa:48 IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:25:32 2017 kern.err kernel: [111410.504405] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:25:32 2017 kern.err kernel: [111410.510615] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:25:32 2017 kern.err kernel: [111410.515289] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:25:32 2017 kern.err kernel: [111410.519577] wlan0: failed to remove key (0, 6c:19:c0:78:fa:48) from hardware (-5)
Sun Nov 19 18:25:32 2017 daemon.info hostapd: wlan0: STA 6c:19:c0:78:fa:48 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:25:36 2017 kern.err kernel: [111414.516317] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:25:36 2017 kern.err kernel: [111414.522269] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:25:36 2017 kern.err kernel: [111414.526928] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:25:36 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:25:42 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED f0:24:75:99:7c:77
Sun Nov 19 18:25:42 2017 daemon.info hostapd: wlan0: STA f0:24:75:99:7c:77 IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:25:46 2017 kern.err kernel: [111424.367808] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:25:46 2017 kern.err kernel: [111424.374053] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:25:46 2017 kern.err kernel: [111424.378689] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:25:46 2017 kern.err kernel: [111424.382987] wlan0: failed to remove key (0, f0:24:75:99:7c:77) from hardware (-5)
Sun Nov 19 18:25:46 2017 daemon.info hostapd: wlan0: STA f0:24:75:99:7c:77 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:25:50 2017 kern.err kernel: [111428.380004] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:25:50 2017 kern.err kernel: [111428.385986] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:25:50 2017 kern.err kernel: [111428.390640] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:25:50 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:25:50 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 00:9e:c8:b5:1e:a8
Sun Nov 19 18:25:50 2017 daemon.info hostapd: wlan0: STA 00:9e:c8:b5:1e:a8 IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:25:54 2017 kern.err kernel: [111432.371214] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:25:54 2017 kern.err kernel: [111432.377435] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:25:54 2017 kern.err kernel: [111432.382080] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:25:54 2017 kern.err kernel: [111432.386368] wlan0: failed to remove key (0, 00:9e:c8:b5:1e:a8) from hardware (-5)
Sun Nov 19 18:25:54 2017 daemon.info hostapd: wlan0: STA 00:9e:c8:b5:1e:a8 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:25:58 2017 kern.err kernel: [111436.361801] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:25:58 2017 kern.err kernel: [111436.367757] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:25:58 2017 kern.err kernel: [111436.372412] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:25:58 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:25:58 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 3c:15:c2:d4:98:6a
Sun Nov 19 18:25:58 2017 daemon.info hostapd: wlan0: STA 3c:15:c2:d4:98:6a IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:26:02 2017 kern.err kernel: [111440.341366] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:26:02 2017 kern.err kernel: [111440.347587] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:26:02 2017 kern.err kernel: [111440.352233] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:26:02 2017 kern.err kernel: [111440.356521] wlan0: failed to remove key (0, 3c:15:c2:d4:98:6a) from hardware (-5)
Sun Nov 19 18:26:02 2017 daemon.info hostapd: wlan0: STA 3c:15:c2:d4:98:6a IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:26:06 2017 kern.err kernel: [111444.351616] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:26:06 2017 kern.err kernel: [111444.357582] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:26:06 2017 kern.err kernel: [111444.362236] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:26:06 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Sun Nov 19 18:26:06 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 00:9e:c8:d1:15:db
Sun Nov 19 18:26:06 2017 daemon.info hostapd: wlan0: STA 00:9e:c8:d1:15:db IEEE 802.11: disassociated due to inactivity
Sun Nov 19 18:26:10 2017 kern.err kernel: [111448.331008] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Sun Nov 19 18:26:10 2017 kern.err kernel: [111448.337256] ieee80211 phy0: return code: 0x1122
Sun Nov 19 18:26:10 2017 kern.err kernel: [111448.341901] ieee80211 phy0: timeout: 0x1122
Sun Nov 19 18:26:10 2017 kern.err kernel: [111448.346189] wlan0: failed to remove key (0, 00:9e:c8:d1:15:db) from hardware (-5)
Sun Nov 19 18:26:10 2017 daemon.info hostapd: wlan0: STA 00:9e:c8:d1:15:db IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Sun Nov 19 18:26:14 2017 kern.err kernel: [111452.328515] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Sun Nov 19 18:26:14 2017 kern.err kernel: [111452.334470] ieee80211 phy0: return code: 0x1111
Sun Nov 19 18:26:14 2017 kern.err kernel: [111452.339110] ieee80211 phy0: timeout: 0x1111
Sun Nov 19 18:26:18 2017 kern.err kernel: [111456.336412] ieee80211 phy0: cmd 0x8050=broadcast_ssid_enable timed out
Sun Nov 19 18:26:18 2017 kern.err kernel: [111456.343074] ieee80211 phy0: return code: 0x0050
Sun Nov 19 18:26:18 2017 kern.err kernel: [111456.347733] ieee80211 phy0: timeout: 0x0050
Sun Nov 19 18:26:22 2017 kern.err kernel: [111460.337252] ieee80211 phy0: cmd 0x8127=SetInformationElements timed out
Sun Nov 19 18:26:22 2017 kern.err kernel: [111460.343997] ieee80211 phy0: return code: 0x0127
Sun Nov 19 18:26:22 2017 kern.err kernel: [111460.348665] ieee80211 phy0: timeout: 0x0127
Sun Nov 19 18:26:26 2017 kern.err kernel: [111464.347123] ieee80211 phy0: cmd 0x801c=80211RadioControl timed out
Sun Nov 19 18:26:26 2017 kern.err kernel: [111464.353446] ieee80211 phy0: return code: 0x001c
Sun Nov 19 18:26:26 2017 kern.err kernel: [111464.358082] ieee80211 phy0: timeout: 0x001c
Sun Nov 19 18:26:30 2017 kern.err kernel: [111468.353348] ieee80211 phy0: cmd 0x8126=SetFixedRate timed out
Sun Nov 19 18:26:30 2017 kern.err kernel: [111468.359209] ieee80211 phy0: return code: 0x0126
Sun Nov 19 18:26:30 2017 kern.err kernel: [111468.363910] ieee80211 phy0: timeout: 0x0126
Sun Nov 19 18:26:30 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5`

**Comment by yuhhaurlin** [comment]
Same as #232. I will check WRT3200ACM, then 88W8864.
