### ISSUE TITLE
MU-MIMO for 88W8964.

### ISSUE THREAD

**Issue by yuhhaurlin** [kaloz/mwlwifi#241]
Create this issue to track this feature.

**Comment by adamcarter1** [comment]
Excited for this!

**Comment by ad019** [comment]
@yuhhaurlin before Christmas this year?

**Comment by yuhhaurlin** [comment]
Company will shutdown one week after Christmas. There is only one week before Christmas. I don't think it can be done within one week.

**Comment by s-pimenta** [comment]
Take your time... We have enough of instability...

**Comment by s-pimenta** [comment]
160MHz will also be available?

**Comment by yuhhaurlin** [comment]
160 MHz working now.

**Comment by s-pimenta** [comment]
Nice... I will buy the new Intel Wireless-AC 9260 https://www.intel.com/content/www/us/en/wireless-products/dual-band-wireless-ac-9260-brief.html to test 160Mhz

**Comment by aaron1959** [comment]
@p3x-robot   all your connections are @ 80 Mhz.
Do you actually have any functioning at 160 Mhz Rates? 
Your post does not show this.

**Comment by aaron1959** [comment]
VHT 160 has absolutely NOTHING to do with MU-MIMO!

**Comment by aaron1959** [comment]
VHT 160 works right now But ONLY between devices which are capable of VHT 160.  
It seems that you are confusing a couple of things which have no relation to each other.

**Comment by aaron1959** [comment]
The Androids are ONLY VHT 80 capable, don't you understand this? 
You will NEVER connect to them with VHT 160!!!!

**Comment by aaron1959** [comment]
BY that I mean **your particular Android devices**, 
In the near future yes the next gen devices  MAY have VHT 160 but not NOW.

**Comment by GillyMoMo** [comment]
![capture](https://user-images.githubusercontent.com/13874870/34395931-da48ae72-eb32-11e7-8270-684c4dda9781.PNG)

An example of the VHT 160. It would more or less like this.

**Comment by thagabe** [comment]
@GillyMoMo What device is that? 

@p3x-robot Pls, stapppp you are mixing up things left and right.

**Comment by aaron1959** [comment]
@thagabe I'm hoping it can be attributed to a language issue, otherwise someone is prone to random spurious emissions.
Nothing to be learned by that. :-(

**Comment by thagabe** [comment]
@aaron1959 I do believe it has to do with language issues. However, the fact that he said he had 160 MHz and showed a bunch of screen shots that showed he didn't + now showing that he has a 1200AC which DOES NOT have 160 MHz makes me believe he doesnt know what he is talking about lol

**Comment by aaron1959** [comment]
Roger that.

**Comment by GillyMoMo** [comment]
@thegabe I have two 3200ACMs. They are bridged. I also have a 1900AC v1 and v2.

**Comment by thagabe** [comment]
@GillyMoMo WDS bridge? That would explain the 160 MHz. I still do not own a devices that can connect via 160 Mhz to device. I'm using a 3200ACM as the main router and my old 1900ACv1 as a DumbAP but wired.

**Comment by thagabe** [comment]
@p3x-robot Also Kaloz is the openwrt maintainer of mwlwifi but the developers behind the driver is yuhhaurlin who is a Marvell employee/contractor.

**Comment by GillyMoMo** [comment]
@thagabe Yes, I do have a WDS bridge. It works pretty good. At first I was having to restart from time to time, but now that it's stable it works just fine now.

**Comment by bbogey** [comment]
Thinking to get wrt3200acm. MU-MIMO coming anytime soon?

**Comment by aaron1959** [comment]
They can't even make it function as a basic wifi router yet I doubt that MU-MIMO is going to happen before the router is even fully functional, right now all firmware and drivers are still in alpha testing if you read these Git hub you will know.

**Comment by yuhhaurlin** [comment]
@aaron1959 Did you still encounter problems? If you did not have problems, why you said basic function of this router is not fully functional? Right now, only problems with Google problem of Andriod phone and group rekey for WDS AP are under tracking. Most of users should use the router without problems.

**Comment by yuhhaurlin** [comment]
MU-MIMO should be added later. In fact, mac80211 only supports MU-MIMO for client mode. I wonder which mac80211open source router supports MU-MIMO for AP mode?

**Comment by adamcarter1** [comment]
Now that everything is fixed, mu-mimo full steam ahead ;)

**Comment by thagabe** [comment]
@yuhhaurlin Ping

**Comment by thagabe** [comment]
He isn't wrong. Specifications for Wireless AX are coming out and soon early prototypes will be released. mwlwifi is, for a lack of a better word, chugging along. It has some unfinished or dirty workarounds for older models that are left while focusing on newer models which is still not feature complete. Most of Q1'18 has been debugging rather than implementing. I do realize this is not easy but @p3x-robot is right, more people can and would get involved but everything is shrouded in secrecy.

**Comment by yuhhaurlin** [comment]
Start to work on this feature.

**Comment by adamcarter1** [comment]
Progress?

**Comment by ad019** [comment]
@yuhhaurlin any eta for this?

**Comment by adamcarter1** [comment]
@ad019 i think we will have this all latched up by the time 802.11ax comes out.

**Comment by ad019** [comment]
¯\_(ツ)_/¯

**Comment by tapper82** [comment]
Any news?

**Comment by ad019** [comment]
Could be that Foxconn acquisition of Belkin has led to change of priorities between Marvell and Belkin.

**Comment by adamcarter1** [comment]
True.

**Comment by yuhhaurlin** [comment]
Sorry. I am busy on other jobs recently. I come back to work on this feature now.

**Comment by davidc502** [comment]
Good to see you back yuhhaurlin. 

Thanks for your hard work.

**Comment by BrainSlayer** [comment]
mmh its not about belkin. its about marvell, the chipset vendor. linksys/belkin does not develop the drivers. marvell has a mi-mimo supporting driver which is propertiery. personally i dont understand why its usefull to maintain 2 drivers. one is propertiery and one is opensource but less featured due the small human resources offered for it. but consider that its the same for qca with ath10k. the chipsets are mu-mimo capable, but ath10k does not support it, but the propertiery driver does. but at least its easier to get access to qca's internal driver sources with some efforts. and for sure we dont need to talk about broadcom. this all makes no sense for me. it makes no sense for marvells business and it makes no sense for the driver quality which is the only thing visible to end users

**Comment by BrainSlayer** [comment]
it is widespread for all vendor provided firmwares, but the benefits arent directly visible for the end user. mu-mimo feature has also just measureable performance gain for multiple clients. thats nothing you will notice at home. for sure you're able to get the propertiery driver from marvell if you start a business discussion with them and if they see some benefit in it you get it. i got them for older chipsets and i did not have to pay any money for it. from my experience companies always try to protect intellectual properties which are included in these special drivers. but if i review the propertiery drivers of qca, marvell or broadcom or mediatek which are heavily complex and bringing own wireless stacks. i can't find any argument for it. thats why i say that this all makes no sense at all.  all companies putting alot of effort in developing own wireless stacks which replace mac80211 and there seem to work alot of people on these drivers. if they would spend this power in using existing technology like mac80211 they would even reduce development time.

**Comment by davidc502** [comment]
@p3x-robot

I look at it this way; the 3200acx is a bit future proof, which is great!

As for mu-mimo, I don't expect anyone to really notice a difference in home applications. Currently only 4 supported clients can take advantage anyway, so really this is low priority. 

I'm just happy it is to the point where it can be implemented, so I can brag when it is done! :)   cheers.

**Comment by BrainSlayer** [comment]
1. yes, same for dd-wrt which i do
2. yes
3. royalty? no. you can use the propertiery as is for free, but you cannot republish it in source form and creating a mac80211 interface is something nearly impossible. i know the original driver
consider that mwlwifi is created by marvell and also maintained. so the question why marvell should help is pointless. its just that marvell doesnt spend much resources in the opensource driver


and yes i'm in germany. i can just tell you that most of the 802.11ac wave2 supporting routers with factory firmwares (not openwrt or dd-wrt or whatever) do support mu-mimo with no exception. same for laptops and phones. they just need to have wave 2 chipsets. in all known wave 2 chipsets mu-mimo has been implemented. so if you have a recent macbook pro retina or recent iphone, yes. its supported. but i dont know all laptops on the market and nor do i know all the chipsets included. so these are just examples. at the time the wrt3200acm was released the situation was different. wave 2 chipsets where rare at this time. but that has been changed

@davidc502. praise? the wrt3200acm is not outstanding from its features right now. i love the netgear r9000 for instance. vht160 capable. su and mu mimo. 1 sfp+ 10gbit port. 8 port switch. quadcore 1.8 ghz cpu. 1 gig ram. 256 mb flash, sata, usb for sure. ah 60 ghz 802.11ad support as well. so the wrt3200acm is not bad, but its not the only good product on the market and the r9000 is just a sample for sure. the only bad thing. openwrt never made support for it. dd-wrt only has it. and ath10k has no mu-mimo support as well. so if someone wants mu-mimo. he only has the choice to use the vendor firmware. but i hope this will change anytime

**Comment by PalebloodSky** [comment]
So if I could briefly jump in what's the recommended router then? I've had R7000 (w/DD-WRT) forever, and messed around with the R7800 and WRT3200ACM. Both seem like the proper step up. But for want of features like 940Mbit WAN (future proofing), 80-100MB/s USB Storage to replace NAS, and of course OpenWrt and/or DD-WRT support. Seems like the ones I listed are ideal for the price, but don't necessarily have that from an open source standpoint, only factory firmware. Recommendation?

**Comment by yuhhaurlin** [comment]
Sorry. This issue lost its tracking function.

**Comment by BrainSlayer** [comment]
in germany i just have a 50 mbit vdsl line, but i have access to fibre connections at another location and our company has fibre as well. we also have access to the DECIX with out servers. but typically a private user can't get more than 50 - 100 mbit in germany since we dont have regular fibre based isp's just cable with crappy quality (shared over too many users) and VDSL

**Comment by thagabe** [comment]
@yuhhaurlin any updates regarding mu-mimo? It was schedule to be completed by the beginning of this year and thus far the issue tracker has been silent. The 3200ACM is over a year now and this is a selling feature. progressive updates are nice, even if it's to say hello...

**Comment by yuhhaurlin** [comment]
It is under working. However, other jobs will interrupt this working sometimes, but this feature will be added finally.

**Comment by orenre** [comment]
Any updates regarding mu-mimo?
Hope to see more progress in this project!
