### ISSUE TITLE
LEDE and handling of noise within 2.4GHz range

### ISSUE THREAD

**Issue by ratsputin** [kaloz/mwlwifi#249]
How should the WRT3200ACM be handling noise within the channel range where a given antenna is running?

I purchased a wifi spectrum analyzer (wiSpy DBx) to try to figure out what has been going on with my wifi.  As it turns out, there is a device nearby broadcasting at about 1W, which is fluctuating between channels 7 and 9 over the course of about an hour.  This, of course, impacts 20MHz 2.4GHz running on channels 6 and 11, depending on where the interference happens to be at any given time.

If you'll recall, I was complaining about issues connecting to my 2.4GHz radio running on channel 11, where my iPhone was giving me an "Invalid Password" error.

What is the expected behavior when a strong noise source interferes with the wifi signal?

The noise source appears to be about 1000mW and 5MHz wide.  It's moved from about 2442MHz to 2455MHz in the hour I've been watching it.

**Comment by yuhhaurlin** [comment]
Change channel. Or use 5g band.
