### ISSUE TITLE
Kernel Module not loading

### ISSUE THREAD

**Issue by thagabe** [kaloz/mwlwifi#277]
@yuhhaurlin 

Wanted to test your latest stable release. Will compile but will not load into kernel 4.14.20. 
Device: WRT1900ACv1
Kernel: 4.14.20
Firmware: OpenWrt r6323-a49f656 (Trunk - Please checkout the latest commits: https://github.com/openwrt/openwrt/commit/c8e62f830df71d2de9e620643bcd2c098fd92153 and https://github.com/openwrt/openwrt/commit/c5b06da56cebf5a4373ebeeab2b5a942246fb04d + https://github.com/openwrt/openwrt/commit/39f8751cdc9fe383f5c8ed7ced75da3e0b6eb6a6) 
// Looking back on how I did this and I first loaded the driver on my previous build which did not had these commits and it still failed (My build environment was exactly the same as the img i built and deployed)

Here is a cleaned log:
```
[    8.150280] kmodloader: loading kernel modules from /etc/modules.d/*
[    8.487642] Loading modules backported from Linux version wt-2017-11-01-0-gfe248fc2c180
[    8.495685] Backport generated by backports.git v4.14-rc2-1-31-g86cf0e5d
[    8.512379] mwlwifi: Unknown symbol vfs_write (err 0)
[    8.551908] mwlwifi: Unknown symbol vfs_write (err 0)
[    8.911811] mwlwifi: Unknown symbol vfs_write (err 0)
[    9.301868] mwlwifi: Unknown symbol vfs_write (err 0)
[    9.352910] mwlwifi: Unknown symbol vfs_write (err 0)
[    9.392882] mwlwifi: Unknown symbol vfs_write (err 0)
[    9.431254] kmodloader: 1 module could not be probed
[    9.436278] kmodloader: - mwlwifi - 0
```
WRT1900ACv1 is used as an AP so no harm done and I can quickly able to test builds. WRT3200ACM is my main router sooooo WIFI needs to be up.
-------------------------------------------------------------------------------------------------------------

I loaded the kmod on my WRT3200ACM and i am testing but I'm afraid when I reboot the driver won't be loaded.

**Comment by yuhhaurlin** [comment]
Same as #271. Please patch it by yourself now. Thanks.
