### ISSUE TITLE
WMM queue priority is not working

### ISSUE THREAD

**Issue by yydcool** [kaloz/mwlwifi#284]
I'm testing with Linksys wrt1200ac router on 2.4GHz. I set up 2 tcp flows to two device using iperf, then I change the dscp value to 56 for one of the flow. The direction of the flows is down link (router to devices).

The expected result should be that dscp 56 flow takes more(almost all) bandwidth because it has higher priority in the WMM queue. However there is no difference before and after I change the dscp. The two flows share the bandwidth half half.

I also tested other dscp values based on: http://www.bintec-elmeg.com/portal/downloadcenter/dateien/workshops/current_en/ws_wlan_html_en_HTML/vowlan_infra_qos_wmm.html

There is no observable difference before and after dscp value changed.

Some my system info is here:
driver name: mwlwifi
chip type: 88W8864
hw version: 7
driver version: 10.3.4.0-20180226
firmware version: 0x0702091a

**Comment by yuhhaurlin** [comment]
This is impossible，I don’t know what the test you did.
