### ISSUE TITLE
Is there a way to get WMM queue sizes?

### ISSUE THREAD

**Issue by yydcool** [kaloz/mwlwifi#285]
Providing the WMM queue sizes, or packet counts for the four queues: AC_BK (background), AC_BE (best effort), AC_VI (video), AC_VO (voice).

This will be helpful when developing the WMM priority levels.

Similar features in ath9k is implemented in debugfs at /sys/kernel/ieee80211/phy0/ath9k/queues

**Comment by yuhhaurlin** [comment]
You can check the code. I did not show it.
