### ISSUE TITLE
Unable to send additional Vendor Specific Elements - WRT1200AC

### ISSUE THREAD

**Issue by vis1phil** [kaloz/mwlwifi#286]
Hello,
i tried to send some additional Vendor Specific Elements, but unfortunately i did'nt work as planned.

System:
- Linksys WRT1200AC
- Marvell 88W8864
- Lede 17.01.4
- kmod-mwlwifi - 4.4.92+10.3.4.0.git-2017-06-06-1

I tried to access the vendor_elements in hostapd with the following ubus commands:

![ubus_set_vendor](https://user-images.githubusercontent.com/37411562/37472963-96b74b3c-286d-11e8-8cca-ab0a6c49708f.PNG)

since it is available in the list

![ubus hostapd](https://user-images.githubusercontent.com/37411562/37473002-acc0e294-286d-11e8-8ec0-fef37841780c.PNG)

but there isn't a change in the _/var/run/hostapd-phy1.conf_.

I tried the command _killall hostapd_ and then _hostapd -B ./hostapd.conf_ but i get

![error hostapd](https://user-images.githubusercontent.com/37411562/37472935-874e4650-286d-11e8-9d3c-8ae0a340e406.PNG)

Second i tried to modify the _/lib/sysfd/hostapd.sh_ to add the vendor_elements manually.  I managed to do so (second from bottom), but still the router does'nt send the Vendor Elements out.

![hostapd-phy1 conf](https://user-images.githubusercontent.com/37411562/37473130-ef81cee0-286d-11e8-966a-ee15c31a8347.PNG)

This is my analysis with wireshark in the VMware:

![wireshark](https://user-images.githubusercontent.com/37411562/37473380-8bb7b16c-286e-11e8-800d-6b47c2a096c6.PNG)

Is there a problem with my configuration or is this a problem with the driver?
Thank you in advance :)

Greetings
Phil

**Comment by yuhhaurlin** [comment]
The driver doesn't support it.
