### ISSUE TITLE
WiFi Power Issue

### ISSUE THREAD

**Issue by Abed1985** [kaloz/mwlwifi#292]
I have a linksys WRT1900ACS flashed per below 👍 

Model | Linksys WRT1900ACS
-- | --
Firmware Version | LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.290.79498-d3f0685)
Kernel Version | 4.4.92

with the stock linksys I had customization of the antenna power to 27 dbm . With the current firmware and updated mwlwifi driver I believe, I have only max of 20 dbm. I thouhgt with the custom firmware and driver I should be able to get the 30 dbm customization. Isnt this possible ? I have also the region set to US too.  I see also high noise in the graphs tab too

**Comment by yuhhaurlin** [comment]
The power table of DTS is prepared by belkin. I have no idea of that.
