### ISSUE TITLE
5GHz Channel not reverting after DFS interrupt

### ISSUE THREAD

**Issue by supersebbo** [kaloz/mwlwifi#294]
Hi,

When the firmware detects radar operating on a DFS channel it is correctly switching to a non-DFS channel. Log:
[352980.024811] ieee80211 phy0: radar detected by firmware
[352980.153620] device wlan0 left promiscuous mode
[352980.158229] br-lan: port 3(wlan0) entered disabled state

However, after the designated DFS 'non-occupancy period' which for my (and most) regulatory domains is 30 minutes, the firmware should revert back to the software configured channel.  This is not happening with the mwlwifi firmware, instead the 5Ghz radio stays on the alternate non-DFS channel seemingly indefinitely (over 10 days in my situation).

This creates a mismatch between the software configuration and the firmware configuration of the device.

**Comment by yuhhaurlin** [comment]
This is not correct. Unless you reconfigure channel or the changed channel is DFS channel and radar detection happened again, otherwise the device should stay with changed channel.

**Comment by supersebbo** [comment]
Hi yuhhaurlin,

This documentation supports my view, perhaps it is vendor decision? https://documentation.meraki.com/MR/Radio_Settings/Dynamic_Frequency_Selection_(DFS)

My problem is this: sometime after DFS radar detection the radio will move to a random non-DFS channel that is highly congested, this results in performance problems with the router.  Because the new channel is non-DFS the radio stays with this congested channel and never moves.  So the only way to resolve performance issues is manual intervention. 

Surely this can’t be by design?

**Comment by supersebbo** [comment]
OK - I have raised it with hostap maintainers.  Thanks for the input.

**Comment by BrainSlayer** [comment]
the problem is the autochannel selection which is also available in hostapd. to select a good working channel you dont need just to take care about available and seen networks, but also to the available airtime. but the airtime property is not available for mwlwifi, so a autochannel algorithm may not select the best working channel

**Comment by yuhhaurlin** [comment]
Mwlwifi supports auto channel. BTW, once if auto channel selects a specific channel，it won’t change it later unless it is DFS channel and radar is detected.

**Comment by supersebbo** [comment]
I may be wrong, but I think if ACS is disabled for the radio (i.e. you manually select a channel) then ACS is also not used for DFS alternate channel selection and it is done entirely at random.
