### ISSUE TITLE
wifi 2.4 or 5ghz Slowwwwwww

### ISSUE THREAD

**Issue by jdthomas4181** [kaloz/mwlwifi#30]
Ok i just installed openwrt-15.05-rc3-mvebu-armada-xp-linksys-mamba-squashfs-factory on this wrt1900ac v1   and now access to the internet via wireless is excruciatingly slow....

backgroud of my network DHCP and DNS on Windows server 2012, internet router is Pfsense. All im using the WRT1900AC for is a wifi access point. doesnt matter if i try and use 5ghz or 2.4ghz the result is the same 30-60 seconds for websites loading on my phone..not as bad with laptop however its still bad...speedtest.net shows speeds of 20mb down 5 up  i have a 30mb internet connection....however the issue isnt entirely with the speed as it is the ping time which shows anywhere from 65 to 95ms.
With stock firmware it was 14 to 16ms and would download at full speed...the reason im using openwrt is because the factory firmware doesnt support Class A networks.

**Comment by JW0914** [comment]
Just an fyi... in order for any dev to troubleshoot your issue, actual information from the device is required.  This includes logs, config files, etc.

**Comment by jdthomas4181** [comment]
now the wireless 5ghz doesnt even work, says its not associated.

heres my log

ue Jul 21 19:40:00 2015 cron.info crond[995]: USER root pid 3734 cmd /sbin/fan_ctrl.sh
Tue Jul 21 19:45:00 2015 cron.info crond[995]: USER root pid 3970 cmd /sbin/fan_ctrl.sh
Tue Jul 21 19:48:15 2015 daemon.info hostapd: wlan0: STA f4:f1:e1:02:e3:2b WPA: group key handshake completed (RSN)
Tue Jul 21 19:48:57 2015 daemon.info hostapd: wlan0: STA f4:f1:e1:02:e3:2b IEEE 802.11: disassociated
Tue Jul 21 19:48:58 2015 daemon.info hostapd: wlan0: STA f4:f1:e1:02:e3:2b IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Tue Jul 21 19:50:00 2015 cron.info crond[995]: USER root pid 4196 cmd /sbin/fan_ctrl.sh
Tue Jul 21 19:55:00 2015 cron.info crond[995]: USER root pid 4422 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:00:00 2015 cron.info crond[995]: USER root pid 4648 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:05:00 2015 cron.info crond[995]: USER root pid 4874 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:10:00 2015 cron.info crond[995]: USER root pid 5100 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:15:00 2015 cron.info crond[995]: USER root pid 5326 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:20:00 2015 cron.info crond[995]: USER root pid 5541 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:25:00 2015 cron.info crond[995]: USER root pid 5766 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:30:00 2015 cron.info crond[995]: USER root pid 5992 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:35:00 2015 cron.info crond[995]: USER root pid 6218 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:40:00 2015 cron.info crond[995]: USER root pid 6444 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:45:00 2015 cron.info crond[995]: USER root pid 6670 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:50:00 2015 cron.info crond[995]: USER root pid 6896 cmd /sbin/fan_ctrl.sh
Tue Jul 21 20:55:00 2015 cron.info crond[995]: USER root pid 7122 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:00:00 2015 cron.info crond[995]: USER root pid 7349 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:05:00 2015 cron.info crond[995]: USER root pid 7564 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:10:00 2015 cron.info crond[995]: USER root pid 7790 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:15:00 2015 cron.info crond[995]: USER root pid 8017 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:20:00 2015 cron.info crond[995]: USER root pid 8243 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:22:43 2015 daemon.notice netifd: wan (1386): Sending renew...
Tue Jul 21 21:22:43 2015 daemon.notice netifd: wan (1386): Lease of 74.141.176.224 obtained, lease time 86400
Tue Jul 21 21:22:43 2015 user.notice firewall: Reloading firewall due to ifupdate of wan (eth1)
Tue Jul 21 21:25:00 2015 cron.info crond[995]: USER root pid 8490 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:30:00 2015 cron.info crond[995]: USER root pid 8716 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:35:00 2015 cron.info crond[995]: USER root pid 8942 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:40:00 2015 cron.info crond[995]: USER root pid 9167 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:45:00 2015 cron.info crond[995]: USER root pid 9393 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:50:00 2015 cron.info crond[995]: USER root pid 9608 cmd /sbin/fan_ctrl.sh
Tue Jul 21 21:55:00 2015 cron.info crond[995]: USER root pid 9834 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:00:00 2015 cron.info crond[995]: USER root pid 10060 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:00:30 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Tue Jul 21 22:00:30 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 0 addresses
Tue Jul 21 22:00:30 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Tue Jul 21 22:00:58 2015 daemon.warn odhcpd[974]: DHCPV6 SOLICIT IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Tue Jul 21 22:00:59 2015 daemon.warn odhcpd[974]: DHCPV6 REQUEST IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Tue Jul 21 22:00:59 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Tue Jul 21 22:00:59 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 1 addresses
Tue Jul 21 22:00:59 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Tue Jul 21 22:05:00 2015 cron.info crond[995]: USER root pid 10292 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:10:00 2015 cron.info crond[995]: USER root pid 10518 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:15:00 2015 cron.info crond[995]: USER root pid 10745 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:20:00 2015 cron.info crond[995]: USER root pid 10960 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:25:00 2015 cron.info crond[995]: USER root pid 11186 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:30:00 2015 cron.info crond[995]: USER root pid 11412 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:35:00 2015 cron.info crond[995]: USER root pid 11638 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:40:00 2015 cron.info crond[995]: USER root pid 11864 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:45:00 2015 cron.info crond[995]: USER root pid 12090 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:50:00 2015 cron.info crond[995]: USER root pid 12316 cmd /sbin/fan_ctrl.sh
Tue Jul 21 22:55:00 2015 cron.info crond[995]: USER root pid 12542 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:00:00 2015 cron.info crond[995]: USER root pid 12767 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:05:00 2015 cron.info crond[995]: USER root pid 12993 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:10:00 2015 cron.info crond[995]: USER root pid 13219 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:15:00 2015 cron.info crond[995]: USER root pid 13434 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:20:00 2015 cron.info crond[995]: USER root pid 13660 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:25:00 2015 cron.info crond[995]: USER root pid 13887 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:30:00 2015 cron.info crond[995]: USER root pid 14113 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:35:00 2015 cron.info crond[995]: USER root pid 14339 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:40:00 2015 cron.info crond[995]: USER root pid 14565 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:45:00 2015 cron.info crond[995]: USER root pid 14791 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:50:00 2015 cron.info crond[995]: USER root pid 15017 cmd /sbin/fan_ctrl.sh
Tue Jul 21 23:55:00 2015 cron.info crond[995]: USER root pid 15243 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:00:00 2015 cron.info crond[995]: USER root pid 15468 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:05:00 2015 cron.info crond[995]: USER root pid 15694 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:10:00 2015 cron.info crond[995]: USER root pid 15920 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:15:00 2015 cron.info crond[995]: USER root pid 16146 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:20:00 2015 cron.info crond[995]: USER root pid 16372 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:25:00 2015 cron.info crond[995]: USER root pid 16598 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:30:00 2015 cron.info crond[995]: USER root pid 16825 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:35:00 2015 cron.info crond[995]: USER root pid 17051 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:40:00 2015 cron.info crond[995]: USER root pid 17277 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:45:00 2015 cron.info crond[995]: USER root pid 17503 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:50:00 2015 cron.info crond[995]: USER root pid 17718 cmd /sbin/fan_ctrl.sh
Wed Jul 22 00:55:00 2015 cron.info crond[995]: USER root pid 17944 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:00:00 2015 cron.info crond[995]: USER root pid 18170 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:05:00 2015 cron.info crond[995]: USER root pid 18396 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:10:00 2015 cron.info crond[995]: USER root pid 18622 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:15:00 2015 cron.info crond[995]: USER root pid 18848 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:20:00 2015 cron.info crond[995]: USER root pid 19074 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:25:00 2015 cron.info crond[995]: USER root pid 19300 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:30:00 2015 cron.info crond[995]: USER root pid 19526 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:35:00 2015 cron.info crond[995]: USER root pid 19752 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:40:00 2015 cron.info crond[995]: USER root pid 19978 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:45:00 2015 cron.info crond[995]: USER root pid 20204 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:50:00 2015 cron.info crond[995]: USER root pid 20430 cmd /sbin/fan_ctrl.sh
Wed Jul 22 01:55:00 2015 cron.info crond[995]: USER root pid 20656 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:00:00 2015 cron.info crond[995]: USER root pid 20882 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:05:00 2015 cron.info crond[995]: USER root pid 21108 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:10:00 2015 cron.info crond[995]: USER root pid 21323 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:15:00 2015 cron.info crond[995]: USER root pid 21549 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:20:00 2015 cron.info crond[995]: USER root pid 21775 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:25:00 2015 cron.info crond[995]: USER root pid 22001 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:30:00 2015 cron.info crond[995]: USER root pid 22227 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:35:00 2015 cron.info crond[995]: USER root pid 22453 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:40:00 2015 cron.info crond[995]: USER root pid 22678 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:45:00 2015 cron.info crond[995]: USER root pid 22904 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:50:00 2015 cron.info crond[995]: USER root pid 23130 cmd /sbin/fan_ctrl.sh
Wed Jul 22 02:55:00 2015 cron.info crond[995]: USER root pid 23357 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:00:00 2015 cron.info crond[995]: USER root pid 23583 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:05:00 2015 cron.info crond[995]: USER root pid 23810 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:10:00 2015 cron.info crond[995]: USER root pid 24036 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:15:00 2015 cron.info crond[995]: USER root pid 24262 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:20:00 2015 cron.info crond[995]: USER root pid 24488 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:25:00 2015 cron.info crond[995]: USER root pid 24714 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:30:00 2015 cron.info crond[995]: USER root pid 24940 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:35:00 2015 cron.info crond[995]: USER root pid 25165 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:40:00 2015 cron.info crond[995]: USER root pid 25391 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:45:00 2015 cron.info crond[995]: USER root pid 25606 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:50:00 2015 cron.info crond[995]: USER root pid 25832 cmd /sbin/fan_ctrl.sh
Wed Jul 22 03:55:00 2015 cron.info crond[995]: USER root pid 26058 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:00:00 2015 cron.info crond[995]: USER root pid 26284 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:05:00 2015 cron.info crond[995]: USER root pid 26510 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:10:00 2015 cron.info crond[995]: USER root pid 26736 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:15:00 2015 cron.info crond[995]: USER root pid 26962 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:20:00 2015 cron.info crond[995]: USER root pid 27188 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:25:00 2015 cron.info crond[995]: USER root pid 27414 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:30:00 2015 cron.info crond[995]: USER root pid 27640 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:35:00 2015 cron.info crond[995]: USER root pid 27866 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:40:00 2015 cron.info crond[995]: USER root pid 28092 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:45:00 2015 cron.info crond[995]: USER root pid 28318 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:50:00 2015 cron.info crond[995]: USER root pid 28545 cmd /sbin/fan_ctrl.sh
Wed Jul 22 04:53:09 2015 daemon.warn odhcpd[974]: DHCPV6 SOLICIT IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 04:53:09 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 04:53:09 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 0 addresses
Wed Jul 22 04:53:09 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 04:53:10 2015 daemon.warn odhcpd[974]: DHCPV6 REQUEST IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 04:53:10 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 04:53:10 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 1 addresses
Wed Jul 22 04:53:10 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 04:55:00 2015 cron.info crond[995]: USER root pid 28780 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:00:00 2015 cron.info crond[995]: USER root pid 29006 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:05:00 2015 cron.info crond[995]: USER root pid 29232 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:10:00 2015 cron.info crond[995]: USER root pid 29458 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:15:00 2015 cron.info crond[995]: USER root pid 29685 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:20:00 2015 cron.info crond[995]: USER root pid 29911 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:25:00 2015 cron.info crond[995]: USER root pid 30136 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:30:00 2015 cron.info crond[995]: USER root pid 30362 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:35:00 2015 cron.info crond[995]: USER root pid 30588 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:40:00 2015 cron.info crond[995]: USER root pid 30814 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:45:00 2015 cron.info crond[995]: USER root pid 31029 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:50:00 2015 cron.info crond[995]: USER root pid 31256 cmd /sbin/fan_ctrl.sh
Wed Jul 22 05:55:00 2015 cron.info crond[995]: USER root pid 31482 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:00:00 2015 cron.info crond[995]: USER root pid 31708 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:05:00 2015 cron.info crond[995]: USER root pid 31934 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:10:00 2015 cron.info crond[995]: USER root pid 32160 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:15:00 2015 cron.info crond[995]: USER root pid 32386 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:20:00 2015 cron.info crond[995]: USER root pid 32612 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:25:00 2015 cron.info crond[995]: USER root pid 374 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:30:00 2015 cron.info crond[995]: USER root pid 608 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:35:00 2015 cron.info crond[995]: USER root pid 835 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:40:00 2015 cron.info crond[995]: USER root pid 1068 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:45:00 2015 cron.info crond[995]: USER root pid 1295 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:50:00 2015 cron.info crond[995]: USER root pid 1524 cmd /sbin/fan_ctrl.sh
Wed Jul 22 06:55:00 2015 cron.info crond[995]: USER root pid 1750 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:00:00 2015 cron.info crond[995]: USER root pid 1975 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:05:00 2015 cron.info crond[995]: USER root pid 2201 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:10:00 2015 cron.info crond[995]: USER root pid 2427 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:13:09 2015 daemon.warn odhcpd[974]: DHCPV6 SOLICIT IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 07:13:09 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 07:13:09 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 0 addresses
Wed Jul 22 07:13:09 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 07:13:10 2015 daemon.warn odhcpd[974]: DHCPV6 REQUEST IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 07:13:10 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 07:13:10 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 1 addresses
Wed Jul 22 07:13:10 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 07:15:00 2015 cron.info crond[995]: USER root pid 2660 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:20:00 2015 cron.info crond[995]: USER root pid 2886 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:22:54 2015 daemon.warn odhcpd[974]: DHCPV6 SOLICIT IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 07:22:54 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 07:22:54 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 0 addresses
Wed Jul 22 07:22:54 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 07:22:55 2015 daemon.warn odhcpd[974]: DHCPV6 REQUEST IA_NA from 000100011d307f4d000c29ac8ad6 on br-lan: ok 2605:a000:160b:c0a8::3ec/128 fde9:a0af:c66f::3ec/128 
Wed Jul 22 07:22:55 2015 daemon.info dnsmasq[1472]: read /etc/hosts - 1 addresses
Wed Jul 22 07:22:55 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/odhcpd - 1 addresses
Wed Jul 22 07:22:55 2015 daemon.info dnsmasq[1472]: read /tmp/hosts/dhcp - 1 addresses
Wed Jul 22 07:25:00 2015 cron.info crond[995]: USER root pid 3118 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:30:00 2015 cron.info crond[995]: USER root pid 3344 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:35:00 2015 cron.info crond[995]: USER root pid 3570 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:40:00 2015 cron.info crond[995]: USER root pid 3796 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:45:00 2015 cron.info crond[995]: USER root pid 4012 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:50:00 2015 cron.info crond[995]: USER root pid 4238 cmd /sbin/fan_ctrl.sh
Wed Jul 22 07:55:00 2015 cron.info crond[995]: USER root pid 4464 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:00:00 2015 cron.info crond[995]: USER root pid 4690 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:05:00 2015 cron.info crond[995]: USER root pid 4916 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:10:00 2015 cron.info crond[995]: USER root pid 5142 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:15:00 2015 cron.info crond[995]: USER root pid 5368 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:20:00 2015 cron.info crond[995]: USER root pid 5593 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:25:00 2015 cron.info crond[995]: USER root pid 5819 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:30:00 2015 cron.info crond[995]: USER root pid 6045 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:35:00 2015 cron.info crond[995]: USER root pid 6271 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:40:00 2015 cron.info crond[995]: USER root pid 6497 cmd /sbin/fan_ctrl.sh
Wed Jul 22 08:45:00 2015 cron.info crond[995]: USER root pid 6724 cmd /sbin/fan_ctrl.sh

**Comment by jdthomas4181** [comment]
bump

**Comment by yuhhaurlin** [comment]
Please do not use Auto channel.

**Comment by yuhhaurlin** [comment]
Except for that, the driver should work well.

**Comment by jdthomas4181** [comment]
ive taken it off auto, its still very slow, and what can cause the 5ghz to stay offline with the message 	Signal: 0 dBm / Noise: 0 dBm
0%	SSID: OpenWrt | Mode: Unknown
Wireless is disabled or not associated

its not disabled!

**Comment by notnyt** [comment]
Nobody else is experiencing this issue, and you haven't posted your config, so I'm not sure what support you're expecting to get.  I'd suggest posting on the forum, as this does not appear to be a driver issue.

**Comment by jdthomas4181** [comment]
OK I'll look bout posting config when I return at 5am....

**Comment by jdthomas4181** [comment]
ok so how do i look at my config files?

**Comment by JW0914** [comment]
As @notnyt stated, this is not a driver issue and needs to be posted on the WRT1900 thread page: https://forum.openwrt.org/viewtopic.php?id=50173&p=266

Please include the following in your post on the thread page:
 * Wireless Config `cat /etc/config/wireless` (Remove plaintext password/key)

**Comment by jdthomas4181** [comment]
well i re flashed the firmware i got the 5ghz wireless working again...speed seems fine on my laptop now however with android devices its still slow... i will post of the forum you may close this
