### ISSUE TITLE
newest release, fail to load wifi on linksys wrt1200ac

### ISSUE THREAD

**Issue by rezad1393** [kaloz/mwlwifi#304]
I use git trunk of openwrt to build custom images for my linksys 1200ac.
at the git commit 0845a346661092f380ab88fd69f7c29f5247c61a the mwlwifi driver gets updated to the new veriosn mwlwifi-2018-06-15-8683de8e from mwlwifi-2018-03-30-fcaea79a.

this causes the router not to be able to load wireless interfaces.

this is the errors I get (just greped the kernel messeges)
`
 Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.354318] ieee80211 phy1: unmapped+free’d 250 0xdd5e6080 0x1d5e6080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.361232] ieee80211 phy1: unmapped+free’d 251 0xdd5e8080 0x1d5e8080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.368148] ieee80211 phy1: unmapped+free’d 252 0xdd5ea080 0x1d5ea080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.375064] ieee80211 phy1: unmapped+free’d 253 0xdd5ec080 0x1d5ec080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.381975] ieee80211 phy1: unmapped+free’d 254 0xdd5ee080 0x1d5ee080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.388890] ieee80211 phy1: unmapped+free’d 255 0xdd5f0080 0x1d5f0080 4096
Fri Jun 22 01:18:38 2018 kern.info kernel: [ 16.395870] ieee80211 phy1: cleaned 0 TX descr
Fri Jun 22 01:18:38 2018 kern.err kernel: [ 16.400373] ieee80211 phy1: init fail
Fri Jun 22 01:18:38 2018 kern.err kernel: [ 16.404060] ieee80211 phy1: fail to initialize wireless lan
Fri Jun 22 01:18:38 2018 kern.err kernel: [ 16.446770] ieee80211 phy1: adapter does not exist

Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 13.322711] mwlwifi: probe of 0000:01:00.0 failed with error -5
Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 14.411335] Modules linked in: mwlwifi(+) mac80211 cfg80211 compat ledtrig_oneshot xt_set x_tables ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink pppoatm ppp_generic slhc ifb tun br2684 atm ahci gpio_button_hotplug mii
Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 14.516316] [<bf181e70>] (ieee80211_register_hw [mac80211]) from [<bf1ec480>] (mwl_init_hw+0xa44/0xcb8 [mwlwifi])
Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 14.526659] [<bf1ec480>] (mwl_init_hw [mwlwifi]) from [<bf1f7144>] (pcie_probe+0×274/0x2c8 [mwlwifi])
Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 14.535942] [<bf1f7144>] (pcie_probe [mwlwifi]) from [<c038a1e4>] (pci_device_probe+0×90/0x11c)
Fri Jun 22 01:18:38 2018 kern.warn kernel: [ 16.451636] mwlwifi: probe of 0000:02:00.0 failed with error -5 

`

reverting to one commit before that update fixes this issue so the issue is with this new driver

**Comment by yuhhaurlin** [comment]
It is impossible. We have tested with 88W8864 which is the chip used by WRT1200AC.

**Comment by BrainSlayer** [comment]
@rezad1393 i also cannot reproduce this issue with current sources. there must be something broken in your local source tree. consider the strange memory allocation related messages from mac80211 i see in your log

**Comment by rezad1393** [comment]
so I should do a clean source ?
will try .
thank you.

**Comment by rezad1393** [comment]
I did the whole clean build but it still fails

**Comment by thagabe** [comment]
when in doubt 
$ git reset --hard && make clean && make dirclean && make distclean  && git pull && ./scripts/feeds update -a && ./scripts/feeds install -a  && make defconfig && make menuconfig 

then do your selection 

(this will get rid of ALL changes)

**Comment by rezad1393** [comment]
added the mesh option as suggested on lede forum and it fixed it.
CONFIG_PACKAGE_MAC80211_MESH
