### ISSUE TITLE
FireTV Stick unable to connect on first startup

### ISSUE THREAD

**Issue by dmascord** [kaloz/mwlwifi#310]
Hi guys,

I have a FireTV Stick, that is unable to obtain an IPv4 address on normal startup.  I have to restart the FireTV stick, and then it will correctly get an IPv4 address.   This is very frustrating behaviour, and something that worked without issue on TP Link 4320, UBNT AC PRO, and also Cisco MR12.

I have tried with 2.4Ghz or 5Ghz, it doesn't change the behaviour (5Ghz is weaker signal due to walls etc).

I am running trunk OpenWRT, and trunk mwlwifi, on a WRT1900ACSv2.

Logs during normal startup:

> Wed Jul 18 00:39:16 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: authenticated
> Wed Jul 18 00:39:16 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: associated (aid 6)
> Wed Jul 18 00:39:17 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 88:71:e5:d0:f6:4a
> Wed Jul 18 00:39:17 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a RADIUS: starting accounting session DB9E898447E84472
> Wed Jul 18 00:39:17 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a WPA: pairwise key handshake completed (RSN)
> Wed Jul 18 00:39:48 2018 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 88:71:e5:d0:f6:4a
> Wed Jul 18 00:39:48 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: disassociated
> Wed Jul 18 00:39:49 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
> Wed Jul 18 00:39:57 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f IEEE 802.11: authenticated
> Wed Jul 18 00:39:57 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f IEEE 802.11: associated (aid 1)
> Wed Jul 18 00:39:57 2018 daemon.notice hostapd: wlan0: AP-STA-CONNECTED b0:72:bf:4e:e0:0f
> Wed Jul 18 00:39:57 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f RADIUS: starting accounting session 43F84D406BB43C86
> Wed Jul 18 00:39:57 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f WPA: pairwise key handshake completed (RSN)
> Wed Jul 18 00:40:00 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: authenticated
> Wed Jul 18 00:40:00 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: associated (aid 6)
> Wed Jul 18 00:40:01 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 88:71:e5:d0:f6:4a
> Wed Jul 18 00:40:01 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a RADIUS: starting accounting session 836911F5D40EA97B
> Wed Jul 18 00:40:01 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a WPA: pairwise key handshake completed (RSN)
> Wed Jul 18 00:40:32 2018 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED 88:71:e5:d0:f6:4a
> Wed Jul 18 00:40:32 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: disassociated
> Wed Jul 18 00:40:33 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
> Wed Jul 18 00:40:33 2018 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED b0:72:bf:4e:e0:0f
> Wed Jul 18 00:40:33 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f IEEE 802.11: disassociated
> Wed Jul 18 00:40:34 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: authenticated
> Wed Jul 18 00:40:34 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a IEEE 802.11: associated (aid 6)
> Wed Jul 18 00:40:34 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED 88:71:e5:d0:f6:4a
> Wed Jul 18 00:40:34 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a RADIUS: starting accounting session 8261B3186862F7C6
> Wed Jul 18 00:40:34 2018 daemon.info hostapd: wlan1: STA 88:71:e5:d0:f6:4a WPA: pairwise key handshake completed (RSN)
> Wed Jul 18 00:40:34 2018 daemon.info hostapd: wlan0: STA b0:72:bf:4e:e0:0f IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
> Wed Jul 18 00:40:56 2018 daemon.notice hostapd: wlan1: AP-STA-DISCONNECTED f0:42:1c:e6:56:a4
> Wed Jul 18 00:41:00 2018 daemon.info hostapd: wlan1: STA f0:42:1c:e6:56:a4 IEEE 802.11: authenticated
> Wed Jul 18 00:41:00 2018 daemon.info hostapd: wlan1: STA f0:42:1c:e6:56:a4 IEEE 802.11: associated (aid 3)
> Wed Jul 18 00:41:00 2018 daemon.notice hostapd: wlan1: AP-STA-CONNECTED f0:42:1c:e6:56:a4
> Wed Jul 18 00:41:00 2018 daemon.info hostapd: wlan1: STA f0:42:1c:e6:56:a4 RADIUS: starting accounting session 2ADE5EA4821AD694
> Wed Jul 18 00:41:00 2018 daemon.info hostapd: wlan1: STA f0:42:1c:e6:56:a4 WPA: pairwise key handshake completed (RSN)

tcpdump during process.   

> root@OpenWrt:~# tcpdump -i wlan1 -vvv -n ether host 88:71:e5:d0:f6:4a
> tcpdump: listening on wlan1, link-type EN10MB (Ethernet), capture size 262144 bytes
> 00:34:41.591108 88:71:e5:d0:f6:4a > ff:ff:ff:ff:ff:ff Null Unnumbered, xid, Flags [Response], length 6: 01 00
> 00:34:41.591123 88:71:e5:d0:f6:4a > ff:ff:ff:ff:ff:ff Null Unnumbered, xid, Flags [Response], length 6: 01 00
> 00:34:41.612076 EAPOL key (3) v2, len 95
> 00:34:41.632612 EAPOL key (3) v1, len 117
> 00:34:41.632835 EAPOL key (3) v2, len 151
> 00:34:41.637760 EAPOL key (3) v1, len 95
> 00:34:42.132797 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffd0:f64a: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fe80::8a71:e5ff:fed0:f64a
> 00:34:42.132833 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffd0:f64a: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fe80::8a71:e5ff:fed0:f64a
> 00:34:42.143070 IP6 (hlim 1, next-header Options (0) payload length: 36) :: > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 1 group record(s) [gaddr ff02::1:ffd0:f64a to_ex { }]
> 00:34:42.143094 IP6 (hlim 1, next-header Options (0) payload length: 36) :: > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 1 group record(s) [gaddr ff02::1:ffd0:f64a to_ex { }]
> 00:34:43.132815 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::8a71:e5ff:fed0:f64a > ff02::2: [icmp6 sum ok] ICMP6, router solicitation, length 16
>           source link-address option (1), length 8 (1): 88:71:e5:d0:f6:4a
>             0x0000:  8871 e5d0 f64a
> 00:34:43.132843 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 16) fe80::8a71:e5ff:fed0:f64a > ff02::2: [icmp6 sum ok] ICMP6, router solicitation, length 16
>           source link-address option (1), length 8 (1): 88:71:e5:d0:f6:4a
>             0x0000:  8871 e5d0 f64a
> 00:34:43.133376 IP6 (flowlabel 0x194b5, hlim 255, next-header ICMPv6 (58) payload length: 120) fe80::24f5:a2ff:fe27:99a8 > fe80::8a71:e5ff:fed0:f64a: [icmp6 sum ok] ICMP6, router advertisement, length 120
>         hop limit 64, Flags [managed, other stateful], pref medium, router lifetime 0s, reachable time 0s, retrans time 0s
>           source link-address option (1), length 8 (1): 26:f5:a2:27:99:a8
>             0x0000:  26f5 a227 99a8
>           mtu option (5), length 8 (1):  1500
>             0x0000:  0000 0000 05dc
>           prefix info option (3), length 32 (4): fd34:4e30:64f6::/64, Flags [onlink, auto], valid time infinity, pref. time infinity
>             0x0000:  40c0 ffff ffff ffff ffff 0000 0000 fd34
>             0x0010:  4e30 64f6 0000 0000 0000 0000 0000
>           route info option (24), length 24 (3):  fd34:4e30:64f6::/48, pref=medium, lifetime=infinity
>             0x0000:  3000 ffff ffff fd34 4e30 64f6 0000 0000
>             0x0010:  0000 0000 0000
>           rdnss option (25), length 24 (3):  lifetime 6000s, addr: fd34:4e30:64f6::1
>             0x0000:  0000 0000 1770 fd34 4e30 64f6 0000 0000
>             0x0010:  0000 0000 0001
>           advertisement interval option (7), length 8 (1):  600000ms
>             0x0000:  0000 0009 27c0
> 00:34:43.142807 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffd0:f64a: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fd34:4e30:64f6:0:8a71:e5ff:fed0:f64a
> 00:34:43.142833 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffd0:f64a: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fd34:4e30:64f6:0:8a71:e5ff:fed0:f64a
> 00:34:43.143023 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffa0:ea9f: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fd34:4e30:64f6:0:292e:9daf:51a0:ea9f
> 00:34:43.143040 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 24) :: > ff02::1:ffa0:ea9f: [icmp6 sum ok] ICMP6, neighbor solicitation, length 24, who has fd34:4e30:64f6:0:292e:9daf:51a0:ea9f
> 00:34:43.154672 IP6 (hlim 1, next-header Options (0) payload length: 56) fe80::8a71:e5ff:fed0:f64a > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 2 group record(s) [gaddr ff02::1:ffa0:ea9f to_ex { }] [gaddr ff02::1:ffd0:f64a to_ex { }]
> 00:34:43.154690 IP6 (hlim 1, next-header Options (0) payload length: 56) fe80::8a71:e5ff:fed0:f64a > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 2 group record(s) [gaddr ff02::1:ffa0:ea9f to_ex { }] [gaddr ff02::1:ffd0:f64a to_ex { }]
> 00:34:50.822823 IP6 (hlim 1, next-header Options (0) payload length: 36) fe80::8a71:e5ff:fed0:f64a > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 1 group record(s) [gaddr ff02::1:ffa0:ea9f to_ex { }]
> 00:34:50.822856 IP6 (hlim 1, next-header Options (0) payload length: 36) fe80::8a71:e5ff:fed0:f64a > ff02::16: HBH (rtalert: 0x0000) (padn) [icmp6 sum ok] ICMP6, multicast listener report v2, 1 group record(s) [gaddr ff02::1:ffa0:ea9f to_ex { }]
> 00:35:15.390908 88:71:e5:d0:f6:4a > ff:ff:ff:ff:ff:ff Null Unnumbered, xid, Flags [Response], length 6: 01 00
> 00:35:15.390925 88:71:e5:d0:f6:4a > ff:ff:ff:ff:ff:ff Null Unnumbered, xid, Flags [Response], length 6: 01 00

Info:

> root@OpenWrt:~# cat /sys/kernel/debug/ieee80211/phy1/mwlwifi/info
> 
> driver name: mwlwifi
> chip type: 88W8864
> hw version: 7
> driver version: 10.3.8.0-20180615
> firmware version: 0x0702091a
> power table loaded from dts: no
> firmware region code: 0x81
> mac address: 00:25:9c:14:5d:71
> 2g: enable
> 5g: disable
> antenna: 4 4
> irq number: 49
> ap macid support: 0000ffff
> sta macid support: 00010000
> macid used: 00000001
> radio: enable
> iobase0: e1100000
> iobase1: e1280000
> tx limit: 768
> rx limit: 64
> qe trigger number: 25119

I have tried with broadcast set to 1, but it doesn't change anything

> config host
>         option ip '10.0.0.194'
>         option mac '88:71:e5:d0:f6:4a'
>         option broadcast '1'

I have tried to change the wpa_group_rekey period to 86400, and disabled the disassoc_low_ack, but no joy:

>       option wpa_group_rekey '86400'
>       option disassoc_low_ack '0'

> root@OpenWrt:~# iw list
> Wiphy phy1
>         max # scan SSIDs: 4
>         max scan IEs length: 2242 bytes
>         max # sched scan SSIDs: 0
>         max # match sets: 0
>         max # scan plans: 1
>         max scan plan interval: -1
>         max scan plan iterations: 0
>         Retry short limit: 7
>         Retry long limit: 4
>         Coverage class: 0 (up to 0m)
>         Device supports T-DLS.
>         Available Antennas: TX 0 RX 0
>         Supported interface modes:
>                  * managed
>                  * AP
>                  * AP/VLAN
>                  * monitor
>                  * mesh point
>         Band 1:
>                 Capabilities: 0x106f
>                         RX LDPC
>                         HT20/HT40
>                         SM Power Save disabled
>                         RX HT20 SGI
>                         RX HT40 SGI
>                         No RX STBC
>                         Max AMSDU length: 3839 bytes
>                         DSSS/CCK HT40
>                 Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
>                 Minimum RX AMPDU time spacing: 4 usec (0x05)
>                 HT TX/RX MCS rate indexes supported: 0-23, 32
>                 VHT Capabilities (0x33837930):
>                         Max MPDU length: 3895
>                         Supported Channel Width: neither 160 nor 80+80
>                         RX LDPC
>                         short GI (80 MHz)
>                         SU Beamformer
>                         SU Beamformee
>                         RX antenna pattern consistency
>                         TX antenna pattern consistency
>                 VHT RX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: MCS 0-9
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT RX highest supported: 0 Mbps
>                 VHT TX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: MCS 0-9
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT TX highest supported: 0 Mbps
>                 Frequencies:
>                         * 2412 MHz [1] (36.0 dBm)
>                         * 2417 MHz [2] (36.0 dBm)
>                         * 2422 MHz [3] (36.0 dBm)
>                         * 2427 MHz [4] (36.0 dBm)
>                         * 2432 MHz [5] (36.0 dBm)
>                         * 2437 MHz [6] (36.0 dBm)
>                         * 2442 MHz [7] (36.0 dBm)
>                         * 2447 MHz [8] (36.0 dBm)
>                         * 2452 MHz [9] (36.0 dBm)
>                         * 2457 MHz [10] (36.0 dBm)
>                         * 2462 MHz [11] (36.0 dBm)
>                         * 2467 MHz [12] (36.0 dBm)
>                         * 2472 MHz [13] (36.0 dBm)
>                         * 2484 MHz [14] (disabled)
>         valid interface combinations:
>                  * #{ AP } <= 16, #{ mesh point } <= 1, #{ managed } <= 1,
>                    total <= 16, #channels <= 1, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 160 MHz }
> 
>         HT Capability overrides:
>                  * MCS: ff ff ff ff ff ff ff ff ff ff
>                  * maximum A-MSDU length
>                  * supported channel width
>                  * short GI for 40 MHz
>                  * max A-MPDU length exponent
>                  * min MPDU start spacing
> Wiphy phy0
>         max # scan SSIDs: 4
>         max scan IEs length: 2247 bytes
>         max # sched scan SSIDs: 0
>         max # match sets: 0
>         max # scan plans: 1
>         max scan plan interval: -1
>         max scan plan iterations: 0
>         Retry short limit: 7
>         Retry long limit: 4
>         Coverage class: 0 (up to 0m)
>         Device supports T-DLS.
>         Available Antennas: TX 0 RX 0
>         Supported interface modes:
>                  * managed
>                  * AP
>                  * AP/VLAN
>                  * monitor
>                  * mesh point
>         Band 2:
>                 Capabilities: 0x106f
>                         RX LDPC
>                         HT20/HT40
>                         SM Power Save disabled
>                         RX HT20 SGI
>                         RX HT40 SGI
>                         No RX STBC
>                         Max AMSDU length: 3839 bytes
>                         DSSS/CCK HT40
>                 Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
>                 Minimum RX AMPDU time spacing: 4 usec (0x05)
>                 HT TX/RX MCS rate indexes supported: 0-23, 32
>                 VHT Capabilities (0x33837930):
>                         Max MPDU length: 3895
>                         Supported Channel Width: neither 160 nor 80+80
>                         RX LDPC
>                         short GI (80 MHz)
>                         SU Beamformer
>                         SU Beamformee
>                         RX antenna pattern consistency
>                         TX antenna pattern consistency
>                 VHT RX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: MCS 0-9
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT RX highest supported: 0 Mbps
>                 VHT TX MCS set:
>                         1 streams: MCS 0-9
>                         2 streams: MCS 0-9
>                         3 streams: MCS 0-9
>                         4 streams: not supported
>                         5 streams: not supported
>                         6 streams: not supported
>                         7 streams: not supported
>                         8 streams: not supported
>                 VHT TX highest supported: 0 Mbps
>                 Frequencies:
>                         * 5180 MHz [36] (23.0 dBm)
>                         * 5200 MHz [40] (23.0 dBm)
>                         * 5220 MHz [44] (23.0 dBm)
>                         * 5240 MHz [48] (23.0 dBm)
>                         * 5260 MHz [52] (20.0 dBm) (radar detection)
>                         * 5280 MHz [56] (20.0 dBm) (radar detection)
>                         * 5300 MHz [60] (20.0 dBm) (radar detection)
>                         * 5320 MHz [64] (20.0 dBm) (radar detection)
>                         * 5500 MHz [100] (27.0 dBm) (radar detection)
>                         * 5520 MHz [104] (27.0 dBm) (radar detection)
>                         * 5540 MHz [108] (27.0 dBm) (radar detection)
>                         * 5560 MHz [112] (27.0 dBm) (radar detection)
>                         * 5580 MHz [116] (27.0 dBm) (radar detection)
>                         * 5600 MHz [120] (disabled)
>                         * 5620 MHz [124] (disabled)
>                         * 5640 MHz [128] (disabled)
>                         * 5660 MHz [132] (27.0 dBm) (radar detection)
>                         * 5680 MHz [136] (27.0 dBm) (radar detection)
>                         * 5700 MHz [140] (27.0 dBm) (radar detection)
>                         * 5720 MHz [144] (27.0 dBm) (radar detection)
>                         * 5745 MHz [149] (36.0 dBm)
>                         * 5765 MHz [153] (36.0 dBm)
>                         * 5785 MHz [157] (36.0 dBm)
>                         * 5805 MHz [161] (36.0 dBm)
>         valid interface combinations:
>                  * #{ AP } <= 16, #{ mesh point } <= 1, #{ managed } <= 1,
>                    total <= 16, #channels <= 1, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 160 MHz }
> 
>         HT Capability overrides:
>                  * MCS: ff ff ff ff ff ff ff ff ff ff
>                  * maximum A-MSDU length
>                  * supported channel width
>                  * short GI for 40 MHz
>                  * max A-MPDU length exponent
>                  * min MPDU start spacing

**Comment by davidc502** [comment]
The following setting fixed my fireTV boxes which had the same behavior...  Un-check "Allow legacy 802.11b rates"  in the Advanced Settings Tab on both 2.4 and 5Ghz Wifi configurations.

**Comment by yuhhaurlin** [comment]
Thanks. I close this issue.

**Comment by dmascord** [comment]
Using David's suggestion, the startup sometimes works on first go, but it is still not 100%.  Is there any debug that I can do to diagnose why it is failing ?
