### ISSUE TITLE
Wi-Fi 802.11ac performance

### ISSUE THREAD

**Issue by olimpiumarius** [kaloz/mwlwifi#312]
Hello,
Can someone tell me what are the performance of a device that uses Wi-Fi 802.11ac? 
In this case we have as an example the TV from Lg 2017 the series 49SJ810V. i ask because i use the following router from Linksys WRT1900ACS v2 OpenWrt/LEDE Kernel Version 4.14.53, with 1Gbps internet connection.
This tv is connected on the 5Ghz wifi side, at a distance of 6 meters that is positioned in the same room with the router.In speed test i have a speed of 128 -172 Mbps download, the problem is on the wifi 5Ghz side when it comes to seeing 4K content on Netflix, he loses his resolution while i watching a movie in 4k, or loses his internet connection for a few seconds, this shows that he loses the wifi signal with the router....
On the 2.4Ghz Netflix side runs smoothly with 4k content, i think the problem is from wrt1900acs v2 wifi driver.
I'll leave you a link with the command line logs,ping Tv and phone to check the information by there.
Wireless mudule
https://fccid.io/BEJLGSBWAC72/User-Manual/User-Manual-3078784
http://opensource.lge.com/osSch/list?types=ALL&search=SJ810V#
http://s.go.ro/w87526ap

driver name: mwlwifi
chip type: 88W8864
hw version: 7
driver version: 10.3.8.0-20180615
firmware version: 0x0702091a
power table loaded from dts: no
firmware region code: 0x30
mac address: 
2g: disable
5g: enable
antenna: 4 4
irq number: 48
ap macid support: 0000ffff
sta macid support: 00010000
macid used: 00000001
radio: enable
iobase0: e1180000
iobase1: e1300000
tx limit: 768
rx limit: 64
qe trigger number: 21578065

Thx

**Comment by olimpiumarius** [comment]
it looks like the firmware  stock (Ver. 2.0.2.188405   5.15.2018) runs perfectly smoothly !

http://s.go.ro/tfn7h1l2

**Comment by BrainSlayer** [comment]
will check the wifi firmware within the stock firmware. its maybe newer

**Comment by BrainSlayer** [comment]
consider that mwlwifi has not the latest firmware. i extracted the 7.2.9.27 wifi fw a while ago which is included in dd-wrt, but not in openwrt/lede. 

you can download the wifi firmware i extracted from here ftp://ftp.dd-wrt.com/others/test/linksys_wrt1900_fw/88W8864.bin
but you have to insert it into your project by yourself for sure. its tested by myself and working. but i dont know if there are any benefits. as far as i know just region specific changes has been made

driver name: mwlwifi
chip type: 88W8864
hw version: 7
driver version: 10.3.8.0-20180716
firmware version: 0x0702091b

**Comment by Kherby** [comment]
So here we have another Wifi card that doesn't work well with the mwlwifi driver...
I wonder when @yuhhaurlin is going to address these issues.

**Comment by BrainSlayer** [comment]
@s-pimenta no this is 1900 / 1200 series only the wrt3200acm has a totally different wifi chipset

**Comment by jebrossard** [comment]
I am seeing something similar with my WRT1900ACSv1 running 18.06.0.  I can not maintain a connection to my work systems from home using Chrome Remote Desktop, using either of my two (very different) Chromebooks, the Chrome Remote Desktop connection drops in seconds, but only on 5 GHz, it works fine on 2.4 GHz, I can work remotely for hours.  I had this issue with 17.0.5 as well.

It's not a Chromebook problem, as I have no issues when connected to my Netgear WAC104 AP on the other side of the house at 5 GHz.  (The WRT1200ACS and WAC104 are on different channels of course.)

I need help with generating logs to document this.  I don't see anything interesting in the syslog, but watching LuCI the RX rate of all of the AC connections constantly jump around, A LOT, even from devices mounted on a wall, i.e. the signal conditions shouldn't be changing that much.

Any help with this would be appreciated.  I would like to be able to work remotely from both sides of the house!  :)

Regards,

Jim

**Comment by jebrossard** [comment]
I have updated to the latest drivers at https://github.com/eduperez/mwlwifi_LEDE/releases/tag/d9c8c59 and the issue I'm having remains.

**Comment by tapper82** [comment]
Nothing will change as @kaloz has not aded anything to fix anything for people using the wrt1200ac 19ac or 3200acm or x. All the new stuff is for a router that is not even out yet. He is just doing what his bosses are telling him to.

**Comment by kaloz** [comment]
@tapper82: This driver is maintained by Marvell as they don’t publish the datasheets of the chips. Try to complain at the right place next time before doing false claims.

**Comment by olimpiumarius** [comment]
As you can see in the pictures below i chose to channel 48, but the software chooses to use channel 44!
I think here are other problems....

http://s.go.ro/x63arzlo

**Comment by yuhhaurlin** [comment]
Yes. I will check this issue later.

**Comment by yuhhaurlin** [comment]
Channel setting should not have problem. The GUI is OpenWrt?

**Comment by olimpiumarius** [comment]
Yes sure.

**Comment by yuhhaurlin** [comment]
Basically mwlwifi will not control channel setting, it just follows the setting from upper layer.

**Comment by howl** [comment]
@olimpiumarius hostap auto switch between channels to avoid beacons from other BBS in the secondary channel. So you set 48 and depending in your bandwidth setting 44 is also used. If there are networks operating in the channel 44 hostap switch between 48 and 44 the secondary and primary channels, but you are still using the same channels. You should check the log as hostapd warns about it when doing.

**Comment by olimpiumarius** [comment]
It looks like everything is working well now, with the new drive version, disconnections have gone away, plus in speed test Netflix network  speed is 285 Mbps on 5Ghz wifi side. And this on a TV!

I noticed a speed anomaly on the 2Ghz wifi side, in speed test achieves only 30 Mbps download & upload speed 50mbps, and that on all the devices.....

Thanks for everything you do!


BusyBox v1.29.3 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 r8324+61-055fb0ba83 Firmware -> https://superwrt.download
 -----------------------------------------------------
root@swrt:~# cat /sys/kernel/debug/ieee80211/phy1/mwlwifi/info

driver name: mwlwifi
chip type: 88W8864
hw version: 7
driver version: 10.3.8.0-20181022
firmware version: 0x0702091a
power table loaded from dts: no
firmware region code: 0x30
mac address: 00:25:9c:14:32:16
2g: enable
5g: disable
antenna: 4 4
irq number: 49
ap macid support: 0000ffff
sta macid support: 00010000
macid used: 00000001
radio: enable
iobase0: e1480000
iobase1: e1600000
tx limit: 768
rx limit: 64
qe trigger number: 1640582

root@swrt:~# cat /etc/config/wireless 

config wifi-device 'radio0'
        option type 'mac80211'
        option hwmode '11a'
        option path 'soc/soc:pcie/pci0000:00/0000:00:01.0/0000:01:00.0'
        option htmode 'VHT80'
        option disabled '0'
        list ht_capab 'SHORT-GI-20'
        list ht_capab 'SHORT-GI-40'
        option country 'RO'
        option legacy_rates '1'
        option channel '44'

config wifi-iface 'default_radio0'
        option device 'radio0'
        option network 'lan'
        option mode 'ap'
        option macaddr '
        option encryption 'psk2'
        option ssid 'superwrt 5Ghz'
        option key '

config wifi-device 'radio1'
        option type 'mac80211'
        option hwmode '11g'
        option path 'soc/soc:pcie/pci0000:00/0000:00:02.0/0000:02:00.0'
        option disabled '0'
        option noscan '1'
        option htmode 'HT40'
        list channels '1'
        list channels '6'
        list channels '11'
        list ht_capab 'SHORT-GI-20'
        list ht_capab 'SHORT-GI-40'
        option country 'RO'
        option legacy_rates '1'
        option channel '6'

config wifi-iface 'default_radio1'
        option device 'radio1'
        option network 'lan'
        option mode 'ap'
        option macaddr 
        option encryption 'psk2'
        option ssid 'superwrt'
        option key

**Comment by yuhhaurlin** [comment]
Thanks. I will close this one. About 2.4g, we have done tested on 8997, it works normally. I can't get my device with 8864 now. I will check 8864 later. For 8964, I will also do some modifications later and come out a formal release and check how many issues are still existed.
