### ISSUE TITLE
5GHz wifi stops working (cmd 0x9125=BAStream timed out)

### ISSUE THREAD

**Issue by blerglemon** [kaloz/mwlwifi#316]
I have seen that issue in a few other tickets. In my case wlan1 will crash with the same errors others have reported, and it will always happen in the middle of a large data transfer over SMB, though it also ends up happening by itself over time. Sometime a reboot will be needed, other times wlan0 remains accessible. I'm using a WRT1900AC V1 (I know, old device), and I have been encountering this problem on every releases of OpenWRT and DD WRT I have tried so far (currently on 18.06.0-rc2)

> driver name: mwlwifi
> chip type: 88W8864
> hw version: 7
> driver version: 10.3.8.0-20180716
> firmware version: 0x0702091a
> power table loaded from dts: yes
> firmware region code: 0x0
> mac address: 00:25:9c:13:c0:5a
> 2g: enable
> 5g: disable
> antenna: 4 4
> irq number: 46
> ap macid support: 0000ffff
> sta macid support: 00010000
> macid used: 00000001
> radio: enable
> iobase0: d0e80000
> iobase1: d1000000
> tx limit: 768
> rx limit: 64
> qe trigger number: 108690

**Comment by yuhhaurlin** [comment]
Duplicated as #308.
