### ISSUE TITLE
MOD : Fix in iw list

### ISSUE THREAD

**Issue by jbsky** [kaloz/mwlwifi#326]
Hello;

I would like to make a small comparison about a simple function like iw list.

![image](https://user-images.githubusercontent.com/16622566/46922538-b59cc280-d00a-11e8-9402-4a9ebbe1b675.png)

When I type this command to display the map information, I am surprised to see 0. I circled in red to help you understand.

Below is a capture from one of your commercial competitors, and we can see that it is not at 0.
![image](https://user-images.githubusercontent.com/16622566/46922527-93a34000-d00a-11e8-9fbd-398e8cfb8fdc.png)

Can you make sure that you display a value that reflects the real capacity of the wifi card?

With kind regards.

Jbsky

**Comment by ryan-dev** [comment]
I can confirm as well, this has been an issue for awhile but just ignored
it.

Would be nice if it actually did report back max speeds for the wifi driver.

**Comment by jbsky** [comment]
Already fixed
