### ISSUE TITLE
ANO : flag no IR with debian/stretch

### ISSUE THREAD

**Issue by jbsky** [kaloz/mwlwifi#327]
Hello,

The firmware 88W8864 has a serious compatibility problem with stretch, Debian distribution for intimates.

The no IR flag is visible when you type iw list, see capture below.
![image](https://user-images.githubusercontent.com/16622566/46981268-eeef3400-d0d7-11e8-9daf-db1a5fc0674c.png)

With Jessie, I don't have the problem.

Do you take care of this problem?

When this flag is set, it is impossible to set up a wifi access point. Knowing that Debian is one of the three branches where linux comes from.

With kind regards.

Jbsky.

**Comment by yuhhaurlin** [comment]
Mwlwifi won’t touch regulatory domain.
