### ISSUE TITLE
VHT80P80 Support

### ISSUE THREAD

**Issue by lantis1008** [kaloz/mwlwifi#339]
Is the 88W8964 capable of 80+80 configuration? If yes, is it just not exposed in driver/firmware?

**Comment by yuhhaurlin** [comment]
Sorry. This is only supported by next generation of Marvell 11ax wifi chip.

**Comment by lantis1008** [comment]
@BrainSlayer yep works ok here, but I do occasionally run into DFS radar detection events. 
If I could use 80+80 I’d be able to avoid the DFS region entirely.

**Comment by BrainSlayer** [comment]
@lantis1008 mmh you may not know it. but its possible to disable dfs entirely as workaround. but i did not tell you this of course

**Comment by lantis1008** [comment]
Yes I think I saw this in the code the other day when I was originally searching for VHT80P80.
