### ISSUE TITLE
Setting mcs value un-supported

### ISSUE THREAD

**Issue by AXavez** [kaloz/mwlwifi#354]
Trying to set the mcs value by using command:
iw dev wlan0 set bitrates vht-mcs-5 1:9

But I get back "Command failed: Unsupported(-95)". I'm on channel 149 and have a BW of 80. also tried with BW  40;

Im trying to determine if thats this driver or if it's the iw command.

versions:
iw - 4.14-1
mwlwifi-firmware-88w8964 - 2018-11-14-81413aa9-1

**Comment by yuhhaurlin** [comment]
Yes. This is not supported.
