### ISSUE TITLE
WRT32X  repeater (client/vap) doesnt work

### ISSUE THREAD

**Issue by SESNut** [kaloz/mwlwifi#363]
Tested gargoyle, openwrt and ddwrt using 5ghz radio, did not test 2.4g

Gargoyle has a wireless bridge setting, but ap never comes up and client never connects
Openwrt client will connect, but vap will never come up, conversely if set to ap, unable to scan for wireless aps to join
ddwrt same as openwrt, client will connect, no vap

**Comment by BrainSlayer** [comment]
will test it tomorrow on my wrt3200acm which has the same hw spec

**Comment by lantis1008** [comment]
I fixed this with a patch a few weeks ago. Which Gargoyle version did you try?

**Comment by lantis1008** [comment]
If this was your thread, you just stopped replying. 
https://www.gargoyle-router.com/phpbb/viewtopic.php?t=12048
