### ISSUE TITLE
linksys WTR32X wireless not work

### ISSUE THREAD

**Issue by zcracker** [kaloz/mwlwifi#384]
Thu Mar 12 01:07:19 2020 kern.err kernel: [  867.497650] ieee80211 phy1: cmd 0x9122=UpdateEncryption timed out
Thu Mar 12 01:07:19 2020 kern.err kernel: [  867.503795] ieee80211 phy1: return code: 0x1122
Thu Mar 12 01:07:19 2020 kern.err kernel: [  867.508353] ieee80211 phy1: timeout: 0x1122
Thu Mar 12 01:07:19 2020 kern.err kernel: [  867.512555] wlan1: failed to remove key (0, b8:5d:0a:b5:bf:c8) from hardware (-5)
Thu Mar 12 01:07:19 2020 kern.debug kernel: [  867.520177] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:07:39 2020 kern.err kernel: [  887.511069] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:07:39 2020 kern.err kernel: [  887.516943] ieee80211 phy0: return code: 0x001d
Thu Mar 12 01:07:39 2020 kern.err kernel: [  887.521492] ieee80211 phy0: timeout: 0x001d
Thu Mar 12 01:07:39 2020 kern.debug kernel: [  887.525700] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:07:59 2020 kern.err kernel: [  907.526192] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:07:59 2020 kern.err kernel: [  907.532055] ieee80211 phy0: return code: 0x001d
Thu Mar 12 01:07:59 2020 kern.err kernel: [  907.536614] ieee80211 phy0: timeout: 0x001d
Thu Mar 12 01:07:59 2020 kern.debug kernel: [  907.540816] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:08:07 2020 user.err ddns-scripts[10389]: myddns_ipv4: ip Error: 1
Thu Mar 12 01:08:19 2020 kern.err kernel: [  927.516900] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:08:19 2020 kern.err kernel: [  927.522768] ieee80211 phy0: return code: 0x001d
Thu Mar 12 01:08:19 2020 kern.err kernel: [  927.527318] ieee80211 phy0: timeout: 0x001d
Thu Mar 12 01:08:19 2020 daemon.info hostapd: wlan1: STA b8:5d:0a:b5:bf:c8 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Thu Mar 12 01:08:19 2020 kern.debug kernel: [  927.537608] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:08:39 2020 kern.err kernel: [  947.512350] ieee80211 phy1: cmd 0x9111=SetNewStation timed out
Thu Mar 12 01:08:39 2020 kern.err kernel: [  947.518212] ieee80211 phy1: return code: 0x1111
Thu Mar 12 01:08:39 2020 kern.err kernel: [  947.522770] ieee80211 phy1: timeout: 0x1111
Thu Mar 12 01:08:39 2020 daemon.info hostapd: wlan0: STA f4:60:e2:84:0f:d2 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Thu Mar 12 01:08:39 2020 kern.debug kernel: [  947.529337] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:08:59 2020 kern.err kernel: [  967.521226] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Thu Mar 12 01:08:59 2020 kern.err kernel: [  967.527105] ieee80211 phy0: return code: 0x1111
Thu Mar 12 01:08:59 2020 kern.err kernel: [  967.531668] ieee80211 phy0: timeout: 0x1111
Thu Mar 12 01:08:59 2020 kern.debug kernel: [  967.536131] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:09:07 2020 user.err ddns-scripts[10389]: myddns_ipv4: ip Error: 1
Thu Mar 12 01:09:19 2020 kern.err kernel: [  987.550172] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:09:19 2020 kern.err kernel: [  987.556058] ieee80211 phy1: return code: 0x001d
Thu Mar 12 01:09:19 2020 kern.err kernel: [  987.560620] ieee80211 phy1: timeout: 0x001d
Thu Mar 12 01:09:19 2020 kern.debug kernel: [  987.564838] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:09:39 2020 kern.err kernel: [ 1007.594940] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:09:39 2020 kern.err kernel: [ 1007.600811] ieee80211 phy1: return code: 0x001d
Thu Mar 12 01:09:39 2020 kern.err kernel: [ 1007.605376] ieee80211 phy1: timeout: 0x001d
Thu Mar 12 01:09:39 2020 kern.debug kernel: [ 1007.609594] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 01:09:59 2020 kern.err kernel: [ 1027.572230] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 01:09:59 2020 kern.err kernel: [ 1027.578096] ieee80211 phy1: return code: 0x001d
Thu Mar 12 01:09:59 2020 kern.err kernel: [ 1027.582653] ieee80211 phy1: timeout: 0x001d
Thu Mar 12 01:09:59 2020 kern.debug kernel: [ 1027.587053] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000

[  687.479415] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  707.436575] ieee80211 phy1: cmd 0x9111=SetNewStation timed out
[  707.442465] ieee80211 phy1: return code: 0x1111
[  707.447032] ieee80211 phy1: timeout: 0x1111
[  707.485678] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  727.465330] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  727.471198] ieee80211 phy1: return code: 0x001d
[  727.475751] ieee80211 phy1: timeout: 0x001d
[  727.479961] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  747.442018] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  747.447889] ieee80211 phy1: return code: 0x001d
[  747.452438] ieee80211 phy1: timeout: 0x001d
[  747.456670] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  767.421303] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  767.427171] ieee80211 phy1: return code: 0x001d
[  767.431727] ieee80211 phy1: timeout: 0x001d
[  767.437659] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  787.444255] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  787.450129] ieee80211 phy1: return code: 0x001d
[  787.454679] ieee80211 phy1: timeout: 0x001d
[  787.458890] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  807.463756] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  807.469634] ieee80211 phy1: return code: 0x001d
[  807.474198] ieee80211 phy1: timeout: 0x001d
[  807.478429] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  827.461484] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  827.467363] ieee80211 phy1: return code: 0x001d
[  827.471936] ieee80211 phy1: timeout: 0x001d
[  847.478406] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
[  847.484538] ieee80211 phy0: return code: 0x1122
[  847.489097] ieee80211 phy0: timeout: 0x1122
[  847.493305] wlan0: failed to remove key (0, f4:60:e2:84:0f:d2) from hardware (-5)
[  847.501616] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  867.497650] ieee80211 phy1: cmd 0x9122=UpdateEncryption timed out
[  867.503795] ieee80211 phy1: return code: 0x1122
[  867.508353] ieee80211 phy1: timeout: 0x1122
[  867.512555] wlan1: failed to remove key (0, b8:5d:0a:b5:bf:c8) from hardware (-5)
[  867.520177] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  887.511069] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
[  887.516943] ieee80211 phy0: return code: 0x001d
[  887.521492] ieee80211 phy0: timeout: 0x001d
[  887.525700] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  907.526192] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
[  907.532055] ieee80211 phy0: return code: 0x001d
[  907.536614] ieee80211 phy0: timeout: 0x001d
[  907.540816] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  927.516900] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
[  927.522768] ieee80211 phy0: return code: 0x001d
[  927.527318] ieee80211 phy0: timeout: 0x001d
[  927.537608] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  947.512350] ieee80211 phy1: cmd 0x9111=SetNewStation timed out
[  947.518212] ieee80211 phy1: return code: 0x1111
[  947.522770] ieee80211 phy1: timeout: 0x1111
[  947.529337] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  967.521226] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
[  967.527105] ieee80211 phy0: return code: 0x1111
[  967.531668] ieee80211 phy0: timeout: 0x1111
[  967.536131] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[  987.550172] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[  987.556058] ieee80211 phy1: return code: 0x001d
[  987.560620] ieee80211 phy1: timeout: 0x001d
[  987.564838] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[ 1007.594940] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[ 1007.600811] ieee80211 phy1: return code: 0x001d
[ 1007.605376] ieee80211 phy1: timeout: 0x001d
[ 1007.609594] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[ 1027.572230] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[ 1027.578096] ieee80211 phy1: return code: 0x001d
[ 1027.582653] ieee80211 phy1: timeout: 0x001d
[ 1027.587053] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[ 1047.538906] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[ 1047.544768] ieee80211 phy1: return code: 0x001d
[ 1047.549324] ieee80211 phy1: timeout: 0x001d
[ 1047.553528] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[ 1067.559630] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[ 1067.565498] ieee80211 phy1: return code: 0x001d
[ 1067.570047] ieee80211 phy1: timeout: 0x001d
[ 1067.574256] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
[ 1087.577206] ieee80211 phy1: cmd 0x801d=MEMAddrAccess timed out
[ 1087.583074] ieee80211 phy1: return code: 0x001d
[ 1087.587623] ieee80211 phy1: timeout: 0x001d
[ 1087.621363] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000

Thu Mar 12 02:11:39 2020 kern.err kernel: [  524.512564] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
Thu Mar 12 02:11:39 2020 kern.err kernel: [  524.518430] ieee80211 phy0: return code: 0x1111
Thu Mar 12 02:11:39 2020 kern.err kernel: [  524.522991] ieee80211 phy0: timeout: 0x1111
Thu Mar 12 02:11:39 2020 kern.debug kernel: [  524.527393] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:11:58 2020 kern.err kernel: [  544.261615] ieee80211 phy0: cmd 0x9100=BssStart timed out
Thu Mar 12 02:11:58 2020 kern.err kernel: [  544.267069] ieee80211 phy0: return code: 0x1100
Thu Mar 12 02:11:58 2020 kern.err kernel: [  544.271631] ieee80211 phy0: timeout: 0x1100
Thu Mar 12 02:11:58 2020 kern.debug kernel: [  544.275855] ieee80211 phy0: change: 0x40
Thu Mar 12 02:11:58 2020 kern.debug kernel: [  544.275859] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:12:18 2020 kern.err kernel: [  564.021880] ieee80211 phy0: cmd 0x9114=SetApMode timed out
Thu Mar 12 02:12:18 2020 kern.err kernel: [  564.027393] ieee80211 phy0: return code: 0x1114
Thu Mar 12 02:12:18 2020 kern.err kernel: [  564.031949] ieee80211 phy0: timeout: 0x1114
Thu Mar 12 02:12:18 2020 kern.debug kernel: [  564.036154] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:12:38 2020 kern.err kernel: [  583.783964] ieee80211 phy0: cmd 0x8129=LinkAdaptCsMode timed out
Thu Mar 12 02:12:38 2020 kern.err kernel: [  583.790007] ieee80211 phy0: return code: 0x0129
Thu Mar 12 02:12:38 2020 kern.err kernel: [  583.794559] ieee80211 phy0: timeout: 0x0129
Thu Mar 12 02:12:38 2020 kern.debug kernel: [  583.798774] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:12:58 2020 kern.err kernel: [  603.531403] ieee80211 phy0: cmd 0x8120=80211hDetectRadar timed out
Thu Mar 12 02:12:58 2020 kern.err kernel: [  603.537625] ieee80211 phy0: return code: 0x0120
Thu Mar 12 02:12:58 2020 kern.err kernel: [  603.542177] ieee80211 phy0: timeout: 0x0120
Thu Mar 12 02:12:58 2020 kern.debug kernel: [  603.546386] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:13:17 2020 kern.err kernel: [  623.372094] ieee80211 phy0: cmd 0x810a=SetRfChannel timed out
Thu Mar 12 02:13:17 2020 kern.err kernel: [  623.377868] ieee80211 phy0: return code: 0x010a
Thu Mar 12 02:13:17 2020 kern.err kernel: [  623.382426] ieee80211 phy0: timeout: 0x010a
Thu Mar 12 02:13:17 2020 kern.debug kernel: [  623.386636] ieee80211 phy0: change: 0x100
Thu Mar 12 02:13:17 2020 kern.debug kernel: [  623.386640] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:13:37 2020 kern.err kernel: [  643.112482] ieee80211 phy0: cmd 0x801c=80211RadioControl timed out
Thu Mar 12 02:13:37 2020 kern.err kernel: [  643.118703] ieee80211 phy0: return code: 0x001c
Thu Mar 12 02:13:37 2020 kern.err kernel: [  643.123256] ieee80211 phy0: timeout: 0x001c
Thu Mar 12 02:13:37 2020 daemon.notice hostapd: nl80211: Failed to remove interface wlan1 from bridge br-lan: Invalid argument
Thu Mar 12 02:13:57 2020 kern.err kernel: [  662.776064] ieee80211 phy1: cmd 0x9122=UpdateEncryption timed out
Thu Mar 12 02:13:57 2020 kern.err kernel: [  662.782195] ieee80211 phy1: return code: 0x1122
Thu Mar 12 02:13:57 2020 kern.err kernel: [  662.786747] ieee80211 phy1: timeout: 0x1122
Thu Mar 12 02:13:57 2020 kern.err kernel: [  662.790958] wlan1: failed to remove key (0, c0:cc:f8:f4:0e:94) from hardware (-5)
Thu Mar 12 02:13:57 2020 kern.debug kernel: [  662.798645] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:14:17 2020 kern.err kernel: [  682.523538] ieee80211 phy1: cmd 0x9111=SetNewStation timed out
Thu Mar 12 02:14:17 2020 kern.err kernel: [  682.529427] ieee80211 phy1: return code: 0x1111
Thu Mar 12 02:14:17 2020 kern.err kernel: [  682.533989] ieee80211 phy1: timeout: 0x1111
Thu Mar 12 02:14:17 2020 kern.debug kernel: [  682.538309] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 02:14:36 2020 kern.err kernel: [  702.272655] ieee80211 phy1: cmd 0x9100=BssStart timed out
Thu Mar 12 02:14:36 2020 kern.err kernel: [  702.278130] ieee80211 phy1: return code: 0x1100
Thu Mar 12 02:14:36 2020 kern.err kernel: [  702.282693] ieee80211 phy1: timeout: 0x1100
Thu Mar 12 02:14:36 2020 kern.debug kernel: [  702.286899] ieee80211 phy1: change: 0x40
Thu Mar 12 02:14:36 2020 kern.debug kernel: [  702.286904] ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 11:58:16 2020 daemon.info hostapd: wlan0: STA ac:1f:74:ab:35:38 IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)
Thu Mar 12 11:58:16 2020 kern.debug kernel: [  421.531868] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  968.175070] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
[  987.820517] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out

Thu Mar 12 14:29:12 2020 daemon.info hostapd: wlan1: STA ac:d5:64:a2:d6:97 IEEE 802.11: authenticated
Thu Mar 12 14:32:49 2020 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED ac:1f:74:ab:35:38
Thu Mar 12 14:32:49 2020 daemon.info hostapd: wlan0: STA ac:1f:74:ab:35:38 IEEE 802.11: disassociated due to inactivity
Thu Mar 12 14:33:09 2020 kern.err kernel: [  450.631832] ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
Thu Mar 12 14:33:09 2020 kern.err kernel: [  450.637979] ieee80211 phy0: return code: 0x1122
Thu Mar 12 14:33:09 2020 kern.err kernel: [  450.642541] ieee80211 phy0: timeout: 0x1122
Thu Mar 12 14:33:09 2020 kern.err kernel: [  450.646742] wlan0: failed to remove key (0, ac:1f:74:ab:35:38) from hardware (-5)
Thu Mar 12 14:33:09 2020 kern.debug kernel: [  450.654421] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 14:33:29 2020 kern.err kernel: [  470.661457] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 14:33:29 2020 kern.err kernel: [  470.667466] ieee80211 phy0: return code: 0x001d
Thu Mar 12 14:33:29 2020 kern.err kernel: [  470.672015] ieee80211 phy0: timeout: 0x001d
Thu Mar 12 14:33:29 2020 kern.debug kernel: [  470.676218] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
Thu Mar 12 14:33:49 2020 kern.err kernel: [  490.674192] ieee80211 phy0: cmd 0x801d=MEMAddrAccess timed out
Thu Mar 12 14:33:49 2020 kern.err kernel: [  490.680082] ieee80211 phy0: return code: 0x001d
Thu Mar 12 14:33:49 2020 kern.err kernel: [  490.684650] ieee80211 phy0: timeout: 0x001d
Thu Mar 12 14:33:49 2020 kern.debug kernel: [  490.688854] ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000

**Comment by kubrickfr** [comment]
Don't change the region, see https://github.com/kaloz/mwlwifi/issues/355

**Comment by thagabe** [comment]
I'ma just put this here: [https://github.com/EXSERENS/mwlwifi/commit/97e051a562c57e61a0404f09d64132a3abbfcc91](url)

**Comment by monokrome** [comment]
The region isn't the issue here. The issue happens even on the expected region.

**Comment by gitthangbaby** [comment]
i also have a normal region set on all interfaces, and all of a sudden, for the first time in years, i get this
`ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000`
no timeouts or other errors usually displayed with this. wifi up and not accepting clients.
i do frequently run command "wifi" to restart wifi (so i don't need to restart router), if it helps.  i must have restarted the wifi/router by my own watchdog script 10.000 times, it's so unreliable:o

**Comment by andyinsf** [comment]
I fixed mine by shutting off WPA3 per https://openwrt.org/toh/linksys/wrt_ac_series#wpa380211w_may_hang_kernel
