### ISSUE TITLE
Firmware update for 88W8864 to 7.2.9.27

### ISSUE THREAD

**Issue by thagabe** [kaloz/mwlwifi#385]
Hello,

I am just wondering if this guy's PR has any merrit. 
[https://github.com/schm0/mwlwifi/commit/121a7f2541c14680b11da56a0d68892b9ab151d7](url)

Will look into testing this, but y'all can get a head start on me!

**Comment by lucenera** [comment]
Only now I did a test with Analiti on smartphones with Sanpdragon 855 on the new mwlwifi firmware and 5GHz

![155](https://user-images.githubusercontent.com/35407790/79499686-a0538a80-802b-11ea-8aec-61209943d5ec.png)
