### ISSUE TITLE
Inconsistent Wi-Fi - WRT3200ACM

### ISSUE THREAD

**Issue by larivierec** [kaloz/mwlwifi#387]
Hello,

I have to spam reboot my router to get a stable state. I don't think this is intended.
Everytime, you see a message like this.
![image](https://user-images.githubusercontent.com/3633214/84390222-3ee01000-abc5-11ea-893a-a6272b19cca8.png)

Am I missing something?
My basic configuration is 160 MHz on 5 GHz and forced 40 on 2.4 GHz.
Encryption strictly uses CCMP.

Upon rebooting, sometimes this buffer error is reflected on phy0, and vice-versa

**Comment by davidc502** [comment]
it's been my experience that 160Mhz has been unreliable and I have never recommended anyone use it. 
BTW -- No 'real' driver updates in over a year and a half, so take that as you will.

**Comment by larivierec** [comment]
This is true. Believe it or not it wasn't the fault of the driver but how OpenWRT handles LEDs that caused that issue.

It's still shameful that they are no more driver updates though...

Thanks for your comment
