### ISSUE TITLE
Excessive softirq

### ISSUE THREAD

**Issue by northbound1** [kaloz/mwlwifi#43]
Since no one else is going to start this issue :)
root@OpenWrt:~# grep mwl /proc/interrupts ; sleep 1; grep mwl /proc/interrupts
 87:    1282535          0  armada_370_xp_irq  59  mwlwifi
 88:  124531322          0  armada_370_xp_irq  60  mwlwifi
 87:    1284531          0  armada_370_xp_irq  59  mwlwifi
 88:  124533305          0  armada_370_xp_irq  60  mwlwifi
htop also shows 37% core0 with no load 60%+ when both radios are enabled 
Could the checks be cut in half or 25%

**Comment by davidc502** [comment]
Agreed. Monitoring is showing 60% utilization, on core0, though the router is idle. If I turn off wifi (both of them), CPU returns to normal.

This doesn't seem to affect performance.

**Comment by notnyt** [comment]
I see the same, openwrt trunk and 10.3.0.12

**Comment by yuhhaurlin** [comment]
Thanks. I will use timer task to replace queue empty interrupt to flush AMSDU packets.

**Comment by northbound1** [comment]
@yuhhaurlin   Thanks for the work I can almost see the light at the end of the tunnel. :)
And ALL of  the others that help to bring it together!

**Comment by gufus** [comment]
@yuhhaurlin

Thanks for everything.

:+1

**Comment by johnnysl** [comment]
Initial tests show me that the new driver shows a way way higher Sirq-load during heavy Wifi usage?

Device: WRT1900AC-V2

**Comment by notnyt** [comment]
Confirmed.

````
CPU0:  0.0% usr  0.0% sys  0.0% nic 11.3% idle  0.0% io  0.0% irq 88.6% sirq
CPU1:  0.1% usr  0.3% sys  0.0% nic 60.1% idle  0.0% io  0.0% irq 39.2% sirq

````

**Comment by notnyt** [comment]
I think this might be a little tight.


+	mod_timer(&priv->period_timer, jiffies + 1);

**Comment by johnnysl** [comment]
<scratches head> every clock tik?

**Comment by notnyt** [comment]
What load were you seeing with the other driver while performing a transfer?  I didn't test before hand.

**Comment by johnnysl** [comment]
at max: 20%, now over 80% for the same amount of wifi traffic

**Comment by yuhhaurlin** [comment]
I think it is correct to use queue empty interrupt to flush AMSDU packets. Although it generates lot interrupts when system is idle, but it will not generate any interrupts when wifi is heavy. I will change it back and release 10.3.0.14.

**Comment by johnnysl** [comment]
@yuhhaurlin : the whole discussion comes from the fact that the driver seems to create excessive load on a V1 WRT1900AC, when idle. This blamed on the high amount of Interrupts created every second. Yet with the V2-version, there is no CPU-load when idle (but still a lot of interrupts seen in /proc/interrupts).

So ideally you want a driver that does not create any CPU-load when idle, and does not create an excessive load either when moving data via WiFI. Personally i have no clue if the hugh interrupts are related to the high CPU load on the V1, or that there is another bug in the driver/kernel/whatever.

**Comment by yuhhaurlin** [comment]
If wifi is idle, even though more interrupts are generated, it should not do lot of things in the flush function.

**Comment by notnyt** [comment]
Please update the issue after you commit and I will test again right away.  Thanks

**Comment by gufus** [comment]
1900ac v1

wifi driver 10.3.0.12

Both mwlwifi 2g and 5g on CPU1

CPU0:  0.1% usr  0.5% sys  0.0% nic 99.2% idle  0.0% io  0.0% irq  0.0% sirq
CPU1:  0.9% usr  1.5% sys  0.0% nic 36.6% idle  0.0% io  0.0% irq 60.7% sirq

**Comment by TireMeat** [comment]
@yuhhaurlin  ...  just a thought -- in mwl_tx_done and other functions the lock/unlocks are very far apart (code-wise, lots of things happening), judging by the high soft IRQ count, (Rescheduling and Single Func), could it be possible that there is too much processing happening in between the locks so that the kernel defers calls (hence creating the Rescheduling interrupts)?

**Comment by notnyt** [comment]
.14 is worse under load than .13.  I think you had it better with the timer.

Mem: 51352K used, 203708K free, 124K shrd, 4628K buff, 11736K cached
CPU0:  0.0% usr  0.0% sys  0.0% nic  7.2% idle  0.0% io  0.0% irq 92.7% sirq
CPU1:  0.0% usr  1.4% sys  0.0% nic 24.6% idle  0.0% io  0.0% irq 73.9% sirq

**Comment by notnyt** [comment]
I actually tested these both under load, and they have similar sirq usage.  However, .13 is MUCH better at idle.  I'd suggest sticking with the timer as opposed to the queue empty interrupt.

Thoughts?

**Comment by yuhhaurlin** [comment]
I think marvell will keep queue empty interrupt to flush AMSDU packets.

**Comment by yuhhaurlin** [comment]
Please based on 10.3.0.14 to see if you still encounter issues listed here. I will check open issues later and try to close them if they will not happen on 10.3.0.14. Thanks.

**Comment by johnnysl** [comment]
I'll check .14 on my v2 later today. What i don't understand is why he behavior is different on the different hardware versions.

**Comment by johnnysl** [comment]
@yuhhaurlin 10.3.0.14 on a WRT1900AC-V2 lowers the cpu temperature by about 15 degrees, and no more high load during heavy wifi transfers. CPU load is ~0 when idling as well, so this looks good for me.

**Comment by yuhhaurlin** [comment]
Thanks for your information.

**Comment by notnyt** [comment]
At idle

````
root@ZOMGWTFBBQWIFI:/# dmesg | grep 10.3.0
[   18.862598] <<Marvell 802.11ac Wireless Network Driver version 10.3.0.14>>
root@ZOMGWTFBBQWIFI:/# uptime
 09:50:45 up 17 min,  load average: 0.00, 0.01, 0.04
root@ZOMGWTFBBQWIFI:/# sensors
armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +68.2Â°C

tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +54.3Â°C
temp2:        +55.0Â°C

CPU0:  0.0% usr  3.1% sys  0.0% nic 39.0% idle  0.0% io  0.0% irq 57.8% sirq
CPU1:  0.0% usr  0.0% sys  0.0% nic  100% idle  0.0% io  0.0% irq  0.0% sirq
````

**Comment by notnyt** [comment]
with 2.4ghz wan to wifi xfer and 5ghz lan to wifi.  Is this within safe operating limits?  It's still going up, so I'll continue monitoring.


````
root@ZOMGWTFBBQWIFI:/# uptime
 10:20:23 up 47 min,  load average: 0.43, 0.38, 0.24


root@ZOMGWTFBBQWIFI:/# sensors
armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +87.7Â°C

tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +66.9Â°C
temp2:        +78.1Â°C

CPU0:  0.0% usr  0.0% sys  0.0% nic  7.8% idle  0.0% io  0.0% irq 92.1% sirq
CPU1:  0.8% usr  1.7% sys  0.0% nic 34.7% idle  0.0% io  0.0% irq 62.6% sirq


````

**Comment by johnnysl** [comment]
@notnyt I just have no idea why a V1 shows such a different behavior. Was this always the case? so also with 10.3.0.3, or was this introduced in some version? i'm getting the idea that the load issue you see might be because of some other bug.

this is my temp during a load test:
/# sensors
tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +44.4°C
temp2:        +46.2°C

armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +72.7°C

/# top (during idle)
Mem: 103284K used, 411740K free, 1804K shrd, 38620K buff, 18584K cached
CPU:   0% usr   0% sys   0% nic  98% idle   0% io   0% irq   1% sirq
Load average: 0.03 0.04 0.05 2/82 29752

**Comment by notnyt** [comment]
I wasn't monitoring this closely with 10.3.0.3, but I do not believe this was the case.

What are you doing for a load test?  My test was wan to wifi on 2.4ghz at 120mbps and lan to wifi on 5ghz at about 200mbps.

**Comment by notnyt** [comment]
I wasn't monitoring this closely with 10.3.0.3, but I do not believe this was the case. I believe this began with 10.3.0.8, but I could not run it due to BA issues. Which kernel are you using?

What are you doing for a load test? My test was wan to wifi on 2.4ghz at 120mbps and lan to wifi on 5ghz at about 200mbps.

As for idle, it seems v1 always experience 50-60% sirq since then.

**Comment by johnnysl** [comment]
load-test: run iperf3 with a N-300 client on 5ghz, against an iperf3 server on the lan.
i test traffic both up and down, and the speed around 160mbits.

/# uname -a
Linux MYROUTR 3.18.23 #3 SMP Fri Nov 6 11:50:11 CET 2015 armv7l n

i'm running DD bleading edge r47389

**Comment by notnyt** [comment]
@yuhhaurlin any idea why v2 isn't showing this problem but v1 is?

**Comment by northbound1** [comment]
I am just a peon but why when the hardware acceleration is enabled ..Since .8?  The cpu load increases with sirq, I thought it would be off loaded.  Or am I in left field?

**Comment by yuhhaurlin** [comment]
Top uses timer tick to collect information. It means it collects information on the rate 100 times per second. For regular periodical event, top may not report correct information.

**Comment by yuhhaurlin** [comment]
I think you only need to care top information when wifi traffic is heavy.

**Comment by northbound1** [comment]
If not showing both cores  top shows an avg. of both at least for me. Htop on the other hand shows both. To me it is the that heat tells the story 10.3.0.3 at idle was close to nil fan never ran.. 10.3.0.8 since has heated me up to 60c and cycled the fan @ 10 to 15 min cycles. This is at idle.

**Comment by northbound1** [comment]
I guess what I am saying is why is it not the wifi getting hot since the load should be going there.
Instead of the cpu.

**Comment by TireMeat** [comment]
Does anyone know how much overhead kernel debugging (debugfs?) add to overhead?

(BTW, 10.3.0.10 has the same system resource performance profile)

**Comment by northbound1** [comment]
This is what I see running guface's fan script you can see the fan cycles. This is at idle.
https://onedrive.live.com/redir?resid=E71014BBAA19358A!8052&authkey=!ALdIv8UJZS26DW0&v=3&ithint=photo%2cJPG

**Comment by notnyt** [comment]
Trying to blame top for anything is absurd.  The busybox version in openwrt sleeps for 5 seconds at a time then reads the data from /proc.  You can trigger an update by pressing enter.  Pressing 1 shows individual cpu stats.

driver 10.3.0.13 shows no sirq at idle, yet 10.3.0.14 shows thousands per second.  CPU temperature at idle is approximately 70C

````
root@ZOMGWTFBBQWIFI:~# grep mwlwifi /proc/interrupts ;sleep 1;grep mwlwifi /proc/interrupt
s
 87:  164636645          0  armada_370_xp_irq  59  mwlwifi
 88:  160197843          0  armada_370_xp_irq  60  mwlwifi
 87:  164638651          0  armada_370_xp_irq  59  mwlwifi
 88:  160199865          0  armada_370_xp_irq  60  mwlwifi

root@ZOMGWTFBBQWIFI:~# uptime
 09:01:34 up 23:28,  load average: 0.11, 0.07, 0.06
root@ZOMGWTFBBQWIFI:~# sensors
armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +70.4Â°C

tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +55.2Â°C
temp2:        +56.1Â°C

````

**Comment by northbound1** [comment]
10.3.0.13 is an improvement I can now run both radios and stay cool.
root@OpenWrt:~# grep mwlwifi /proc/interrupts ;sleep 1;grep mwlwifi /proc/interrupts
 87:      29265          0  armada_370_xp_irq  59  mwlwifi
 88:    1043990          0  armada_370_xp_irq  60  mwlwifi
 87:      29318          0  armada_370_xp_irq  59  mwlwifi
 88:    1044030          0  armada_370_xp_irq  60  mwlwifi
root@OpenWrt:~# sensors
tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +45.1°C
temp2:        +48.1°C

armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +53.7°C

**Comment by johnnysl** [comment]
@northbound1: well 10.0.3.13 does exactly the reverse on a V2, it's 10.3.0.14 that runs quite well on that platform. So i'm not convinced that the interrupts logged in /proc/interrupts are the cause of the high cpu. It might also be some other change in the driver.

**Comment by lantis1008** [comment]
.14 running on a V1 with low cpu temp and high idle sirq

**Comment by northbound1** [comment]
Back to 10.3.0.13  .14  is tolerable on 1 radio but with both up the fan cycles. There is no real difference in iperf no difference in usb3 transfer. I can't see idling at 25% with no load. That makes no sense to me.

**Comment by gufus** [comment]
1900ac v1

wifi driver 10.3.0.12

Both mwlwifi 2g and 5g on CPU1


Runs like this MOST of the time.

CPU0:  0.7% usr  0.3% sys  0.0% nic 98.8% idle  0.0% io  0.0% irq  0.0% sirq
CPU1:  0.5% usr  0.9% sys  0.0% nic 34.8% idle  0.0% io  0.0% irq 63.5% sirq


Then once-in-awhile...

CPU0:  0.1% usr  0.3% sys  0.0% nic 99.4% idle  0.0% io  0.0% irq  0.0% sirq
CPU1:  0.7% usr  0.5% sys  0.0% nic 80.0% idle  0.0% io  0.0% irq 18.5% sirq

queue empty interrupt to flush AMSDU packets WORKS

I'm sure wifi driver 10.3.0.14 will be the SAME, it's the same code as wifi driver 10.3.0.12

**Comment by northbound1** [comment]
@gufus have you tried .13?

**Comment by northbound1** [comment]
You should since you also have a v1. Just to see if you see any real difference in iperf or anything else.
I see no real difference. Except for the cpu doing what it should at idle which is next to nothing.

**Comment by northbound1** [comment]
This is what you should see in collectd when idle with both radios up. wrt1900ac v1 10.3.0.13
![10 3 0 13 idle cpu](https://cloud.githubusercontent.com/assets/15316281/11023588/68c118dc-864b-11e5-89ea-67113124f019.JPG)
![10 3 0 13 idle sensors](https://cloud.githubusercontent.com/assets/15316281/11023589/68c4ac9a-864b-11e5-82bc-208f9c6ced39.JPG)

**Comment by gufus** [comment]
Using username "root".
DD-WRT v3.0-r28112 std (c) 2015 NewMedia-NET GmbH
Release: 11/10/15
Authenticating with public key "rsa-key-20120810"


BusyBox v1.24.1 (2015-11-10 00:30:38 CET) built-in shell (ash)

root@AC-DD-WRT:~# dmesg | grep 10.3.0
[    5.843715] <<Marvell 802.11ac Wireless Network Driver version 10.3.0.14>>
root@AC-DD-WRT:~#

2 clients on 2.4ghz 1 client on 5ghz

CPU0:  1.5% usr  0.9% sys  0.0% nic 56.5% idle  0.0% io  0.0% irq 40.8% sirq
CPU1:  0.1% usr  0.5% sys  0.0% nic 83.2% idle  0.0% io  0.0% irq 15.9% sirq

CPU 67.4 °C / WL0 50.7 °C / WL1 52.5 °C  

NO performance tweaks

**Comment by gufus** [comment]
1900ac v1

Using username "root".
DD-WRT v3.0-r28112 std (c) 2015 NewMedia-NET GmbH
Release: 11/10/15
Authenticating with public key "rsa-key-20120810"


BusyBox v1.24.1 (2015-11-10 00:30:38 CET) built-in shell (ash)

root@AC-DD-WRT:~# strings /lib/ath9k/mwlwifi.ko | grep 10.3
10.3.0.14
10.3.0.14
root@AC-DD-WRT:~#

2 clients on 2.4ghz 1 client on 5ghz

CPU0:  1.5% usr  0.9% sys  0.0% nic 56.5% idle  0.0% io  0.0% irq 40.8% sirq
CPU1:  0.1% usr  0.5% sys  0.0% nic 83.2% idle  0.0% io  0.0% irq 15.9% sirq

CPU 67.4 °C / WL0 50.7 °C / WL1 52.5 °C  

NO performance tweaks

**Comment by cfinch81** [comment]
I've noticed looking through tx.c that every function other than mwl_tx_flush_amsdu that uses locks on sta_lock, tx_desc_lock and/or amsdu_lock use spin_lock_bh/spin_unlock_bh instead of spin_lock/spin_unlock.  Does anyone (@yuhhaurlin maybe?) know if there is a reason the bh variants weren't used in mwl_tx_flush_amsdu?  Is it possible that the queue empty interrupt is being called again before the previous one finishes causing the new thread to spin waiting for the lock, and causing the high sirq usage v1 devices are seeing?  If that turns out to be the case, using the bh variant for the 3 locks in mwl_tx_flush_amsdu would disable softirqs while the locks are active, which would solve that problem and prevent the queue empty interrupt from firing again while the amsdu packets are being flushed, but I have no idea if it would cause other issues.  There may be other sirqs that need to fire and be acted upon immediately while that code runs, or there may be other reasons for not using the sirq-disabling bh variants, I don't know.  Unfortunately (or fortunately, depending on how you look at it ;) ), I don't have a v1 to test any of this with.

**Comment by gufus** [comment]
1900ac v1

wifi driver 10.3.0.14

Both mwlwifi 2g and 5g on CPU1

queue empty interrupt to flush AMSDU packets WORKS

wifi driver 10.3.0.14 is the **SAME**


MOST of the time

CPU0:  0.9% usr  0.7% sys  0.0% nic 98.2% idle  0.0% io  0.0% irq  0.0% sirq
CPU1:  0.1% usr  0.3% sys  0.0% nic 39.7% idle  0.0% io  0.0% irq 59.6% sirq

once-in-awhile

CPU0:  0.5% usr  0.3% sys  0.0% nic 99.0% idle  0.0% io  0.0% irq  0.0% sirq
CPU1:  1.3% usr  1.3% sys  0.0% nic 78.6% idle  0.0% io  0.0% irq 18.5% sirq

**Comment by northbound1** [comment]
@Calvin Finch
If you get it to work on a v2 I am game to try it on a v1
I would be great to see something that works properly on both.

**Comment by cfinch81** [comment]
I did a bit more research and deleted the post because further research indicated it wouldn't make a difference, the tasklet wouldn't get called again while it was running.  The only way I could see that it would make a difference is if the lock is global across all loaded copies of the driver in which case the driver on the 2.4 ghz radio could be calling it at the same time as the 5 ghz radio, but I don't know.  My experience with kernel modules is too weak.  Once I get a compile system going I'll do some actual testing and debugging and if there's anything to that line of reasoning, I'll post my results.  Until then I'm just taking a stab in the dark and probably showing my ignorance and wasting peoples time.

**Comment by TireMeat** [comment]
@cfinch81  ..  no worries about the time wasting stuff.   Most of us on here are good people (typical nerds without social skill sometimes but good people nonetheless).  @yuhhaurlin is the engineer who's keeping it all together and releasing "official" code.

I do think there's something to the locks - personally I've been buried with work to check into it.  About a week ago I was mentioned noticing that in mwl_tx_done and other functions the lock/unlocks are very far apart (code-wise with lots of commands happening in between, loops, etc.), and judging by the high soft IRQ count, (Rescheduling and Single Func), could it be possible that there is too much processing happening in between the locks so that the kernel defers calls (hence creating the Rescheduling interrupts)?   I have on my to-do list next week (hopefully) to see what happens if the lock/unlock are tightened to just around the commands that actually need the lock.

About the types of locks, I found this useful ... https://www.kernel.org/pub/linux/kernel/people/rusty/kernel-locking/c214.html.   BH locks seem to be appropriate here - note that in tx they're not uniform throughout the code.

**Comment by yuhhaurlin** [comment]
Top uses timer tick to collect information. It means it collects information on the rate 100 times per second. For regular periodical event, top may not report correct information. The mechanism is correct and it won't take lot of CPU times when system is idle.

**Comment by yuhhaurlin** [comment]
There is no need to use spin_lock with bh inside bh.

**Comment by yuhhaurlin** [comment]
I think I can modify the code to trigger queue empty tasklet only when previous queue empty interrupt is occurred longer than one tick.

**Comment by northbound1** [comment]
Looking forward to the commit.

**Comment by notnyt** [comment]
@yuhhaurlin any news on the modification discussed here?

**Comment by TireMeat** [comment]
I wanted to share a patch to 10.3.0.14 for rx.c below.

On my test unit, the Rescheduling Interrupts are lower (~2-3x as the crow flies) under heavy transfer load and overall (upload) performance is increased.  Stability is good with two PC running Intel AC 7260, a Samsung Galaxy S4, and an iPhone 6+.

My changes are to tighten the spin lock/unlock around the memory operations. 

```
--- original_10.3.0.14/rx.c	2015-11-06 00:13:02.000000000 -0600
+++ updated_10.3.0.14/rx.c	2015-11-23 01:16:44.232709000 -0600
@@ -488,9 +488,10 @@
 	struct ieee80211_hdr *wh;
 	u32 status_mask;
 
-	spin_lock(&priv->rx_desc_lock);
-	desc = &priv->desc_data[0];
-	curr_hndl = desc->pnext_rx_hndl;
+		spin_lock(&priv->rx_desc_lock);
+		desc = &priv->desc_data[0];
+		curr_hndl = desc->pnext_rx_hndl;
+		spin_unlock(&priv->rx_desc_lock);
 
 	if (!curr_hndl) {
 		status_mask = readl(priv->iobase1 +
@@ -500,7 +501,6 @@
 
 		priv->is_rx_schedule = false;
 		wiphy_warn(hw->wiphy, "busy or no receiving packets\n");
-		spin_unlock(&priv->rx_desc_lock);
 		return;
 	}
 
@@ -560,7 +560,9 @@
 
 					tr = (struct mwl_dma_data *)
 					     prx_skb->data;
+					spin_lock(&priv->rx_desc_lock);
 					memset((void *)&tr->data, 0, 4);
+					spin_unlock(&priv->rx_desc_lock);
 					pkt_len += 4;
 				}
 
@@ -602,9 +604,11 @@
 							      &status))
 					goto out;
 		}
-
+		spin_lock(&priv->rx_desc_lock);
 		memcpy(IEEE80211_SKB_RXCB(prx_skb), &status, sizeof(status));
 		ieee80211_rx(hw, prx_skb);
+		spin_unlock(&priv->rx_desc_lock);
+
 out:
 		mwl_rx_refill(priv, curr_hndl);
 		curr_hndl->pdesc->rx_control = EAGLE_RXD_CTRL_DRIVER_OWN;
@@ -622,5 +626,4 @@
 
 	priv->is_rx_schedule = false;
 
-	spin_unlock(&priv->rx_desc_lock);
 }
```

**Comment by johnnysl** [comment]
@Tiremeat: interesting. i'll see if i can add it to my code and test it as well.
Thanks for your work!

**Comment by thagabe** [comment]
@johnnysl mind walking me through on applying this on my build? I want to know how to apply this patch. Thank You

**Comment by johnnysl** [comment]
@thagabe: dead easy, from build root create "package/kernel/mwlwifi/patches/120-tiremeat.patch" (or whatever fancy name you want to give it)
copy and paste above content in the file, and then build the image as usual.

**Comment by thagabe** [comment]
@johnnysl durrrrrr! of course! thanks!

**Comment by yuhhaurlin** [comment]
@notnyt Commit code to decrease the number to trigger queue empty tasklet.

**Comment by thagabe** [comment]
@yuhhaurlin Have you committed @johnnysl 's patches?

**Comment by notnyt** [comment]
@yuhhaurlin looks much better now at idle.

CPU0:  0.0% usr  1.6% sys  0.0% nic 96.7% idle  0.0% io  0.0% irq  1.6% sirq
CPU1:  0.0% usr  0.0% sys  0.0% nic  100% idle  0.0% io  0.0% irq  0.0% sirq

And while transferring a file over 5ghz at 21.5MB/s

CPU0:  0.1% usr  0.0% sys  0.0% nic 30.0% idle  0.0% io  0.0% irq 69.7% sirq
CPU1:  0.0% usr  0.0% sys  0.0% nic 55.9% idle  0.0% io  0.0% irq 44.0% sirq

**Comment by notnyt** [comment]
Speeds are significantly improved with @TireMeat 's patch applied to the new version.  Good job.  @yuhhaurlin  get this in the codebase ;)

@TireMeat you should submit a pull request to make it easier.  If you fork the repo, clone it locally, make your changes, commit them, then push it back to github, you can submit a pull request to this repo to make it easy.

**Comment by notnyt** [comment]
Also sirq usage is down with @TireMeat 's patch.

During the same xfer as above:

CPU0:  0.0% usr  0.0% sys  0.0% nic 24.5% idle  0.0% io  0.0% irq 75.4% sirq
CPU1:  0.3% usr  0.3% sys  0.0% nic 98.6% idle  0.0% io  0.0% irq  0.5% sirq

**Comment by thagabe** [comment]
@notnyt I'll assume the patch was not merged :/ rats! I just finished building a new image with your patch and the new driver.

**Comment by notnyt** [comment]
@thagabe  i have the changes commited to my forked repo here: https://github.com/notnyt/mwlwifi

I've submitted a pull request with it, but you can check that out if you want to.

**Comment by yuhhaurlin** [comment]
@notnyt Please help to check if new committed code won't get high Software IRQ for v1 when system is idle?

**Comment by notnyt** [comment]
@yuhhaurlin please see my replies further up.

The new changes fix the SIRQ issue.  @TireMeat 's patch reduces SIRQ usage under load even further.

Summarized:

````
With just the code in this repo at idle:
CPU0: 0.0% usr 1.6% sys 0.0% nic 96.7% idle 0.0% io 0.0% irq 1.6% sirq
CPU1: 0.0% usr 0.0% sys 0.0% nic 100% idle 0.0% io 0.0% irq 0.0% sirq

And while transferring a file over 5ghz at 21.5MB/s

CPU0: 0.1% usr 0.0% sys 0.0% nic 30.0% idle 0.0% io 0.0% irq 69.7% sirq
CPU1: 0.0% usr 0.0% sys 0.0% nic 55.9% idle 0.0% io 0.0% irq 44.0% sirq

And while transferring a file over 5ghz with @tiremeat's patch.  Notice the 2nd core isn't loaded.

CPU0: 0.0% usr 0.0% sys 0.0% nic 24.5% idle 0.0% io 0.0% irq 75.4% sirq
CPU1: 0.3% usr 0.3% sys 0.0% nic 98.6% idle 0.0% io 0.0% irq 0.5% sirq
````


Temperatures have also dropped:
````
root@ZOMGWTFBBQWIFI:~# sensors
armada_thermal-virtual-0
Adapter: Virtual device
temp1:        +64.6Â°C

tmp421-i2c-0-4c
Adapter: mv64xxx_i2c adapter
temp1:        +52.8Â°C
temp2:        +53.1Â°C

````

**Comment by yuhhaurlin** [comment]
@notnyt I think if the new commit fixed this problem, you can close this one. rx_desc spin lock is used to protect receive descriptor structure. Thanks for your help.

**Comment by notnyt** [comment]
@yuhhaurlin I'm pretty sure everything remains protected with his patch.  Please review:

https://github.com/kaloz/mwlwifi/issues/43#issuecomment-158871088

It lowers sirq usage a good deal and I have not seen any stability issues.

**Comment by notnyt** [comment]
@yuhhaurlin Isn't the rx_desc spin lock still used where necessary with this patch? I'm running with it now with no adverse affects.

**Comment by yuhhaurlin** [comment]
@notnyt I check the code now. It looks like there is no need to use this spin lock.

**Comment by notnyt** [comment]
@yuhhaurlin What do you mean?  All he's done is tightened up the lock around the sensitive structures/calls.  Functionality should remain the same, unless I'm missing a bit of code there that needs to be protected.  If so, can you point out where?

**Comment by yuhhaurlin** [comment]
Only this tasketlet access rx descriptor,  so the spin lock maybe can be removed. I check it now.

**Comment by notnyt** [comment]
Latest changes look great on v1.  Anyone test on v2?  Safe to close this out now?

**Comment by johnnysl** [comment]
Will test the latest changes tomorrow on my V2.  Must say that tiremeats patch did not change anything on my V2.

**Comment by gufus** [comment]
1900ac v1

Commit code to support following items: 

1. Use compiler attribute "____cacheline_aligned_in_smp" to let
spin lock be cacheline aligned.
2. Avoid to trigger queue empty tasklet more than one time within
one tick.


Using username "root".
DD-WRT v3.0-r28320 std (c) 2015 NewMedia-NET GmbH
Release: 11/25/15
Authenticating with public key "rsa-key-20120810"
==========================================================

     ___  ___     _      _____  ______       ____  ___
    / _ \/ _ \___| | /| / / _ \/_  __/ _  __|_  / / _ \
   / // / // /___/ |/ |/ / , _/ / /   | |/ //_ <_/ // /
  /____/____/    |__/|__/_/|_| /_/    |___/____(_)___/

                       DD-WRT v3.0
                   http://www.dd-wrt.com

==========================================================


BusyBox v1.24.1 (2015-11-25 03:38:09 CET) built-in shell (ash)

root@AC-DD-WRT_M:~#

2g wifi

sirq are down, and they flush pretty fast too

idle

CPU0:  1.9% usr  0.3% sys  0.0% nic 90.0% idle  0.0% io  0.0% irq  7.5% sirq
CPU1:  0.1% usr  0.0% sys  0.0% nic 97.2% idle  0.0% io  0.0% irq  2.5% sirq

temps are the same

23:32:18 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:19 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:20 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:22 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:23 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:24 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=100
23:32:25 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=100
23:32:26 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=100
23:32:27 CPUtemp=66 WLOtemp=52 WL1temp=53 fanstatus=100
23:32:28 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=100
23:32:29 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:30 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:31 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:32 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:33 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=0
23:32:34 CPUtemp=68 WLOtemp=52 WL1temp=53 fanstatus=100

wifi load

CPU0:  0.7% usr  2.3% sys  0.0% nic 51.9% idle  0.0% io  0.0% irq 44.8% sirq
CPU1:  0.5% usr  0.9% sys  0.0% nic 74.9% idle  0.0% io  0.0% irq 23.5% sirq

**Comment by lantis1008** [comment]
So what do we call this new set of patches?
10.3.0.15? 

I'll do a build now, but I'm on 18 days uptime with no issues on 10.3.0.14 on a V1 lol.

**Comment by yuhhaurlin** [comment]
You can check kaloz to build this version of code.
10.3.0.15 is under development. I remember kaloz will hook date with version.

**Comment by northbound1** [comment]
@kaloz There is definite improvement on the latest push to trunk. Don't have time now but will beat on it more later.

**Comment by johnnysl** [comment]
Soft Irq CPU-load on the V2 dropped from 1.5% to 0.1% after the upgrade. Impressive difference.
Wifi speed has also significantly improved. This update is really a great improvement!
CPU and wireless temperatures do not really differ after the upgrade though. 68, 41 and 42 degrees C.

**Comment by yuhhaurlin** [comment]
I had checked with kaloz. Latest version of this driver is checked into CC branch and main trunk. Thanks for all helps from community. This issue is closed.

**Comment by TireMeat** [comment]
@yuhhaurlin  ..  thanks much Mr. Lin - you've carried this project.  Kalotz hasn't done much as far as I've seen - too busy with conferences and panels.  ;-)

**Comment by yuhhaurlin** [comment]
@TireMeat This project is cooperated between Belkin and Marvell. This driver is the responsibility of Marvell. Kaloz is OpenWrt site admin.

**Comment by itrankolov** [comment]
I am running V1 hardware and with latest patches SoftIRQ is still an issue (~4176 p/s). CPU load at idle is ~26%. Temps are at least 5°C higher. Performance is the same or lower as with 10.3.0.3.

**Comment by megaloegoman** [comment]
@yuhhaurlin, I stumbled across this thread when I was doing an experiment to see if OpenWRT with a tickless kernel (NO_HZ_IDLE) can reduce the #interrupts. Some interrupts did go down, but mwlwifi interrupts (i.e. queue empty) went up, probably because the interrupt isn't cleared until the next tick, leading to lots of spurious IRQs. Anyways, it seems you've already done a lot to reduce the CPU usage to 0 during idle, so for practical purposes, the current driver is good enough. But being an optimization freak, I'm having an itch to get rid of those thousands of spurious interrupts/s.

I have little experience writing kernel drivers, but from what I've read in the code, there are 3 places for flushing the aggregate packet. The 1st 2 happen synchronously with packet submission ((mwl_mac80211_tx()).

1. mwl_tx_do_amsdu(): if submitted packet length is > SYSADPT_AMSDU_ALLOW_SIZE
2. mwl_tx_do_amsdu(): total # aggregated packets is > SYSADPT_AMSDU_PACKET_THRESHOLD
3. flush aggregate packet every jiffy (in ISR.c) or else the user will wait forever for the last few packets. I don't understand why it uses a hardware interrupt (empty FIFO) when a timer interrupt would suffice.

Instead of periodically flushing packets every jiffy, I propose creating a 1 shot timer interrupt each time an new aggregate packet is created (in mwl_mac80211_tx()). It will flush the aggregate packet in the future, but if #1 or #2 happens before that, then the timer interrupt will just be a no-op.

This should greatly reduce the #interrupts during idle and allow the CPU to enter sleep longer.

What do you think?

-Yale

**Comment by yuhhaurlin** [comment]
This had been done before. I don't think I will change it now.

**Comment by megaloegoman** [comment]
Thanks for the fast reply. If it was tried, then why was it changed? What problems did it have?

**Comment by yuhhaurlin** [comment]
The more heavy the traffic is, the less interrupts generated by queue empty.
