### ISSUE TITLE
10.3.0.13 or 10.3.0.14 + IPV6 causes a kernel crash on hostapd?

### ISSUE THREAD

**Issue by johnnysl** [kaloz/mwlwifi#45]
See ticket: https://dev.openwrt.org/ticket/20857 comment 13 for a more complete crash dump.
I asume currently that Hostapd crashes due to the driver crashing, eventually taking down the kernel.But please correct me if i'm wrong.

**Comment by yuhhaurlin** [comment]
I commit the fix for issue #49. Can you help to check if it also fixes your problem?

**Comment by johnnysl** [comment]
Sure, and thanks for the quick fix!
Will give feedback later today.

**Comment by yuhhaurlin** [comment]
Thanks.

**Comment by johnnysl** [comment]
System is up with the new driver for about 80 minutes now. Running great, yet to be 100% sure it is fixed i'll need to test it for about 2 days

**Comment by yuhhaurlin** [comment]
Thanks for your information and sorry for the bug.

**Comment by johnnysl** [comment]
No worries, everyone makes mistakes. Happy to see progress, and that i'm able to help testing.
Currently 5:30 hours of uptime and still no issues. I'm tempted to say the fix patches the issue, but i'll report back again tomorrow, for progress on that.

Once fixed, my only issue left with this driver would be the inability to use channel 100 and up (DFS support, as i'm not able to persuade OpenWRT to use the driver without it)

**Comment by tangsoft** [comment]
Here is my dmesg:

[  395.806050] Unable to handle kernel paging request at virtual address 1c2bf3cc
[  395.815972] pgd = ccd78000
[  395.818939] [1c2bf3cc] *pgd=00000000
[  395.823265] Internal error: Oops: 5 [#1] SMP ARM
[  395.827915] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE armada_thermal xt_time xt_tcpudp xt_state xt_socket xt_nat xt_multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TPROXY xt_TCPMSS xt_REDIRECT xt_LOG xt_CT thermal_sys slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_raw iptable_mangle iptable_filter ip_tables crc_ccitt hid evdev input_core tmp421 pwm_fan hwmon i2c_mv64xxx i2c_dev mwlwifi mac80211 cfg80211 compat ledtrig_usbdev xt_set ip_set_list_set ip_set_hash_netiface ip_set_hash_netport ip_set_hash_netnet ip_set_hash_net ip_set_hash_netportnet ip_set_hash_mac ip_set_hash_ipportnet ip_set_hash_ipportip ip_set_hash_ipport ip_set_hash_ipmark ip_set_hash_ip ip_set_bitmap_port ip_set_bitmap_ipmac ip_set_bitmap_ip ip_set nfnetlink ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables tun nls_utf8 nls_cp437 regmap_spi regmap_mmio ecb usb_storage leds_tlc59116 regmap_i2c i2c_core xhci_plat_hcd xhci_pci xhci_hcd sata_mv libata ehci_orion ehci_platform ehci_hcd sd_mod scsi_mod gpio_button_hotplug ext4 jbd2 mbcache usbcore nls_base usb_common aead crypto_hash
[  395.946081] CPU: 0 PID: 1922 Comm: transmission-da Not tainted 3.18.23 #1
[  395.952909] task: cd812800 ti: cccb4000 task.ti: cccb4000
[  395.958340] PC is at put_page+0xc/0x54
[  395.962125] LR is at skb_release_data+0x70/0xc4
[  395.966685] pc : [<c0090348>]    lr : [<c0273bfc>]    psr: 80000013
[  395.966685] sp : cccb5d10  ip : cccb5d20  fp : cccb5d1c
[  395.978211] r10: c0482940  r9 : 00000014  r8 : 00000fff
[  395.983471] r7 : ccc95d00  r6 : c09700c0  r5 : c09700f0  r4 : 00000001
[  395.990027] r3 : 000000ed  r2 : 00000000  r1 : 00000001  r0 : 1c2bf3cc
[  395.996588] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[  396.003767] Control: 10c5387d  Table: 0cd7806a  DAC: 00000015
[  396.009541] Process transmission-da (pid: 1922, stack limit = 0xcccb4238)
[  396.016363] Stack: (0xcccb5d10 to 0xcccb6000)
[  396.020748] 5d00:                                     cccb5d3c cccb5d20 c0273bfc c0090348
[  396.028973] 5d20: ccc95d00 cd97e380 00000000 cccb5ed8 cccb5d54 cccb5d40 c0273c78 c0273b98
[  396.037203] 5d40: ccc95d00 cd97e380 cccb5d6c cccb5d58 c0273c90 c0273c5c ccc95d00 cd97e380
[  396.045433] 5d60: cccb5d8c cccb5d70 c0279cf0 c0273c88 ccc95d00 00000014 cd97e380 cccb5ed8
[  396.053664] 5d80: cccb5de4 cccb5d90 c02da51c c0279c20 cccb5db4 cf8004c0 a0000113 cccb5ef4
[  396.061882] 5da0: 00000000 00000040 cccb5dd4 00000000 00000000 00000014 cd84b280 cccb5ed8
[  396.070108] 5dc0: c02da23c 00000fff cccb5ed8 c0409ae8 cd812800 b6c1dc74 cccb5e1c cccb5de8
[  396.078338] 5de0: c02e48f0 c02da248 00000040 00000000 cccb5dfc 00000010 cccb5e24 00000010
[  396.086568] 5e00: c0278870 c02e4860 00000040 00000fff cccb5ec4 cccb5e20 c026c318 c02e486c
[  396.094797] 5e20: 00000040 c001eed0 00000000 00000000 00000000 cccb5e60 cd812800 00000000
[  396.103026] 5e40: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
[  396.111245] 5e60: cd8a900c 00000000 00000040 00000fff cf79b640 cccb5e80 00000000 cccb5ed8
[  396.119469] 5e80: cccb5e9c cccb5e90 c00d7d54 c00d77b8 cccb5eac cccb5ea0 c00d7d78 c00d7cf4
[  396.127699] 5ea0: c0465008 00000fff b6c1dbf4 cf79b640 00000000 00000040 cccb5fa4 cccb5ec8
[  396.135928] 5ec0: c026ea88 c026c2a0 fffffff7 00000001 b6c1dc88 00000feb cccb5ef4 00000000
[  396.144157] 5ee0: cccb5ed0 00000001 00000000 00000000 b6c1e8ac d8250002 0c0e5165 00000000
[  396.152387] 5f00: 00000000 cccb5f10 c006b610 c025fec4 4dc75767 00000002 bc577498 00b2727a
[  396.160617] 5f20: ffffffff 00000000 ffffffff cccb5f88 b6ea0ce0 00000000 00000107 c0008fe4
[  396.168847] 5f40: cccb5f5c cccb5f50 c006c5c0 c006b5d4 cccb5f84 cccb5f60 c006803c c006c5bc
[  396.177076] 5f60: 565c4e5b b6ea0ce0 00000000 00000107 c0008fe4 dc8cb017 00000008 b6c1dbf4
[  396.185305] 5f80: b6c1dbf0 0000001d 00000124 c0008fe4 cccb4000 00000000 00000000 cccb5fa8
[  396.193535] 5fa0: c0008e40 c026e9e8 b6c1dbf4 b6c1dbf0 00000012 b6c1dc74 00000fff 00000000
[  396.201754] 5fc0: b6c1dbf4 b6c1dbf0 0000001d 00000124 00000000 00022c98 b6e9f800 00000000
[  396.209979] 5fe0: b6c1dba8 b6c1db94 b6ef92fc b6efc1cc 60000010 00000012 00000000 00000000
[  396.218191] Backtrace: 
[  396.220683] [<c009033c>] (put_page) from [<c0273bfc>] (skb_release_data+0x70/0xc4)
[  396.228302] [<c0273b8c>] (skb_release_data) from [<c0273c78>] (skb_release_all+0x28/0x2c)
[  396.236519]  r7:cccb5ed8 r6:00000000 r5:cd97e380 r4:ccc95d00
[  396.242290] [<c0273c50>] (skb_release_all) from [<c0273c90>] (__kfree_skb+0x14/0x20)
[  396.250060]  r5:cd97e380 r4:ccc95d00
[  396.253707] [<c0273c7c>] (__kfree_skb) from [<c0279cf0>] (skb_free_datagram_locked+0xdc/0xe0)
[  396.262270]  r5:cd97e380 r4:ccc95d00
[  396.265922] [<c0279c14>] (skb_free_datagram_locked) from [<c02da51c>] (udp_recvmsg+0x2e0/0x41c)
[  396.274660]  r7:cccb5ed8 r6:cd97e380 r5:00000014 r4:ccc95d00
[  396.280417] [<c02da23c>] (udp_recvmsg) from [<c02e48f0>] (inet_recvmsg+0x90/0xa4)
[  396.287934]  r10:b6c1dc74 r9:cd812800 r8:c0409ae8 r7:cccb5ed8 r6:00000fff r5:c02da23c
[  396.295884]  r4:cccb5ed8
[  396.298460] [<c02e4860>] (inet_recvmsg) from [<c026c318>] (sock_recvmsg_nosec+0x84/0x98)
[  396.306587]  r6:00000fff r5:00000040 r4:c02e4860
[  396.311284] [<c026c294>] (sock_recvmsg_nosec) from [<c026ea88>] (SyS_recvfrom+0xac/0x118)
[  396.319497]  r9:00000040 r8:00000000 r7:cf79b640 r6:b6c1dbf4 r5:00000fff r4:c0465008
[  396.327374] [<c026e9dc>] (SyS_recvfrom) from [<c0008e40>] (ret_fast_syscall+0x0/0x38)
[  396.335240]  r10:00000000 r9:cccb4000 r8:c0008fe4 r7:00000124 r6:0000001d r5:b6c1dbf0
[  396.343187]  r4:b6c1dbf4
[  396.345757] Code: eaffffc6 e1a0c00d e92dd800 e24cb004 (e5902000) 
[  396.355922] ---[ end trace 00205ea24f83378b ]---

**Comment by johnnysl** [comment]
@tangsoft is that before or after the update to the driver David uploaded this morning?

**Comment by yuhhaurlin** [comment]
Kaloz had just included the lastest driver to OpenWrt. You can build the latest driver for testing. Because the version of driver is the same, please help to check source code to make sure the latest fix is built in. Thanks.

**Comment by thagabe** [comment]
@yuhhaurlin All good on my end. No errors at this time (30 mins after loading the firmware) I have an intel 7260 and works fine on 5 GHZ US.

**Comment by yuhhaurlin** [comment]
@thagabe Thanks for your information.

**Comment by johnnysl** [comment]
@yuhharlin: mine is still stable as well. Issue is fixed with commit 352efe4bdc34204cc528ac9a979bb0032a6996e0. Let close this one :+1:

**Comment by tangsoft** [comment]
@johnnysl I think it may be caused by the disk errors. I did a fsck.ext4, and now streaming movies on iPhone and iPad for hours without any problems. Thanks all for the fix.
