### ISSUE TITLE
5GHz stops working with VHT80

### ISSUE THREAD

**Issue by notnyt** [kaloz/mwlwifi#50]
Using the latest driver, 5Ghz stopped working with VHT80 after a few hours until a power cycle.  A reboot did nothing.

**Comment by notnyt** [comment]
And a few hours later 5GHz is no longer usable.  Nothing in dmesg.

root@ZOMGWTFBBQWIFI:/# iwinfo wlan0 info
wlan0     ESSID: "ZOMG2.4"
          Access Point: 00:25:9C:13:05:56
          Mode: Master  Channel: 3 (2.422 GHz)
          Tx-Power: 30 dBm  Link Quality: 61/70
          Signal: -49 dBm  Noise: -80 dBm
          Bit Rate: 109.8 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: 11AB:2A55 11AB:0000 [Marvell 88W8864]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy0
root@ZOMGWTFBBQWIFI:/# iwinfo wlan1 info
wlan1     ESSID: "ZOMGWTFBBQWIFI"
          Access Point: 00:25:9C:13:05:57
          Mode: Master  Channel: 157 (5.785 GHz)
          Tx-Power: 30 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: -58 dBm
          Bit Rate: unknown
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11nac
          Hardware: 11AB:2A55 11AB:0000 [Marvell 88W8864]
          TX power offset: none
          Frequency offset: none
          Supports VAPs: yes  PHY name: phy1

**Comment by notnyt** [comment]
It seems this works fine when set to VHT40, but once set to VHT80, no devices can connect.

**Comment by yuhhaurlin** [comment]
Use Intel 7260?

**Comment by notnyt** [comment]
@yuhhaurlin  Negative,  using macbook and a lg g4.  I'm wondering fi this is driver issue or hardware failure, since it seemed to work previously.

**Comment by yuhhaurlin** [comment]
Since this one is not clear yet. I will check intel 7260 first. Thanks.

**Comment by notnyt** [comment]
This has nothing to do with 7260, just VHT80 not working, only VHT40

**Comment by yuhhaurlin** [comment]
But you said it is working previously?

**Comment by lantis1008** [comment]
I don't experience this issue 
Latest driver
Ch 149
Vht80
Country AU
No scan is not set (0)

**Comment by notnyt** [comment]
Might be hardware failure since I'm pretty sure it was working before.

**Comment by yuhhaurlin** [comment]
Yes, we had done a lot of Inter operation tests with different clients. I did not receive this kind of test report.

**Comment by notnyt** [comment]
Seems to be a hardware issue.  When temp2 rises above 50C it seems to fail.  And on that note, I no longer have a properly functioning device to debug with.  Good luck w/ the rest of the bugs, I'll be ordering a UAP-AC-LR.  Cheers.

**Comment by yuhhaurlin** [comment]
I will close this one. Thanks.
