### ISSUE TITLE
.16 driver - mutex problem

### ISSUE THREAD

**Issue by trustno1foxm** [kaloz/mwlwifi#59]
hello,

by using .16 I have major problems with my wlan. a nexus 5 device and a surface pro 4 have very high ping times, over 300ms (host 8.8.8.8)
by using .13 everything is fine, times are about 35ms (host 8.8.8.8)
maybe because of a changing from spinlock to mutex?!

pls fix!

thx!

edit: 15.05 final

**Comment by yuhhaurlin** [comment]
How about the throughput you can get?

**Comment by trustno1foxm** [comment]
which device should i test? on the nexus 9 there weren't any issues, but with the devices above the times have been very high.

**Comment by yuhhaurlin** [comment]
I suspect that client entered power save mode. You can disable power save mode of client and ping again.

**Comment by trustno1foxm** [comment]
I'll try again later, but it's useless for me, why should I deactivate power save mode? There are no problems with .13? Battery run-time is more important for me.

**Comment by yuhhaurlin** [comment]
Just check if it is due to pwer save mode. If.13 is all right, .16 should be no problem too.

**Comment by trustno1foxm** [comment]
I have tested it, but with .16 the ping times are ok now. The router was rebootet because of the installation of the driver. Could it be that the problem appears after some runtime?
