### ISSUE TITLE
.16 driver Incompatability with with Dell 1504 wireless card and HP officejet printer 8600

### ISSUE THREAD

**Issue by johnnysl** [kaloz/mwlwifi#61]
Both devices work horrible bad with the current driver. No errors in the logs, but very frequent disconnects on the 2.4ghz interface. 
I've fired up a Linksys EA4500 V2, with an identical Openwrt build (and identical wireless config), and both devices work great with the EA4500. This forces me to believe the issue is related to the current wireless driver.

**Comment by Chadster766** [comment]
What errors are you seeing in the WRT log? You should be able to grep the log for the problem devices MAC Addresses.

**Comment by johnnysl** [comment]
@chadster, what log do you mean? system log and kernel log are not showing any warnings or errors

**Comment by Chadster766** [comment]
Those are the logs. Odd no errors.

**Comment by jsebean** [comment]
and also have this issue with force disconnects on 5GHz for a Nexus Player and an Asus X550Z Broadcom wireless chip. Constantly have to force reconnect to gain connection again but it's driven me up the wall to the point I don't even use the wifi on the WRT1900ACv2 any longer.

**Comment by jsebean** [comment]
Just had it happen to my laptop (Jonah-laptop)... Wifi died completely and had to reset the adapter to reconnect. This is all the log shows from DD-WRT:
http://i.imgur.com/G5hGXEm.png

**Comment by yuhhaurlin** [comment]
How about .17 and new firmware?

**Comment by johnnysl** [comment]
Still frequent disconnects after ~10 minutes on the Dell laptop.

**Comment by yuhhaurlin** [comment]
Can you get log from hostapd? BTW, this is the only problem for.17 and new firmware now?

**Comment by jsebean** [comment]
I can't say whether or not older versions have the issue or not, but... unless this is placebo effect I find setting the transmit power lower than 20dbm seems to help, but doesn't completely mitigate the issue. Eventually it gets bad again where rebooting the router then helps for a while.

**Comment by yuhhaurlin** [comment]
.16 has throughput becomes lower problem. It is fixed by.17.

**Comment by johnnysl** [comment]
stability for the dell laptop has improved greatly, after the firmware change / change back trick.
seems to be solved, but have not tested the printer yet, will report back after this weekend.

**Comment by johnnysl** [comment]
@yuhhaurlin, this issue can be closed. Both devices are now running perfectly stable on .17.

I'm a happy camper now :-) :+1:

**Comment by yuhhaurlin** [comment]
Thanks.
