### ISSUE TITLE
.17 driver limits speed to ~25mbit on V2 hardware

### ISSUE THREAD

**Issue by johnnysl** [kaloz/mwlwifi#68]
Although I see happy people with V1 hardware in combination with the new driver,
the performance of this driver & firmware with the V2 hardware is very poor, and seems "capped" to 20~25mbit.
This is regardless of upload or download (-R option) direction, or using 2.4ghz or 5ghz. Flashing back to the previous .16 driver restores the performance (for a couple of hours, but that is a different story).

All speeds tested with IPERF3 running on the router and iperf3 on various clients. Tried both N and AC clients and router settings, even tried 20, 40 and 80 mhz bandwidth settings to no avail.
As i see reports of people using DD-WRT, with the same issue on V2 hardware, my assumption is that is either driver or firmware related.

Using the hostapd config file in the test section does not show any change, speeds stay similar to the hostapd.conf used by Openwrt.

**Comment by yuhhaurlin** [comment]
1. How about the number between Lan and wireless client?
2. Can you try.17 with previous firmware?

Thanks.

**Comment by yuhhaurlin** [comment]
Please also get information you got via "iw dev" and "iw dev wlan0/wlan1 station dump". Thanks.

**Comment by johnnysl** [comment]
have tried the previous firmware, and it fixed my issue., measuring Iperf3 speeds of ~530mbit.
after that i've put back the new firmware; and to my surprise the issue stays fixed. Really scratching my head over this one... really weird...

Let me test this for another day or two, and see if the speeds stay ok.

**Comment by yuhhaurlin** [comment]
Basically if speed is fixed on 2x Mbps, it looks like it is g rate. You can use "iw dev" to know setting of AP and use "iw dev wlan0/wlan1 station dump" to check tx/rx rate with station. BTW, WMM must be set.

**Comment by Razerwire** [comment]
Problem persists with DD-WRT even after installing a fresh build.

Here's the info you requested:

```
root@DD-WRT:~# iw dev

phy#1
        Interface ath1
                ifindex 15
                wdev 0x100000005
                addr xx:xx:xx:xx:xx:xx
                ssid Stralingsbron2Gh
                type AP
                channel 11 (2462 MHz), width: 20 MHz, center1: 2462 MHz
phy#0
        Interface ath0
                ifindex 14
                wdev 0x5
                addr xx:xx:xx:xx:xx:xx
                ssid Stralingsbron5Gh
                type AP
                channel 116 (5580 MHz), width: 80 MHz, center1: 5610 MHz
```

``

```
root@DD-WRT:~# iw dev ath0 station dump
Station 4c:34:88:a8:93:ff (on ath0)
        inactive time:  0 ms
        rx bytes:       53869
        rx packets:     546
        tx bytes:       24824
        tx packets:     207
        tx retries:     0
        tx failed:      0
        signal:         -33 dBm
        signal avg:     -37 dBm
        tx bitrate:     866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
        rx bitrate:     526.6 MBit/s VHT-MCS 6 80MHz VHT-NSS 2
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
root@DD-WRT:~# 
```

**Comment by jbsky** [comment]
phy#1
        Interface wlan1
                ifindex 5
                wdev 0x100000001
                addr 00:25:9c:13:0f:47
                ssid Hotspot
                type AP
                channel 149 (5745 MHz), width: 80 MHz, center1: 5775 MHz
phy#0
        Interface wlan0
                ifindex 4
                wdev 0x1
                addr 00:25:9c:13:0f:46
                ssid Hotspot_2Ghz
                type AP
                channel 11 (2462 MHz), width: 40 MHz, center1: 2452 MHz


root@WRT1900AC:~# iw dev wlan0 station dump
Station 5c:8d:4e:47:20:44 (on wlan0)
        inactive time:  72320 ms
        rx bytes:       5002718
        rx packets:     9597
        tx bytes:       2773660
        tx packets:     5778
        tx retries:     0
        tx failed:      0
        signal:         -53 dBm
        signal avg:     -54 dBm
        tx bitrate:     72.2 MBit/s MCS 7 short GI
        rx bitrate:     24.0 MBit/s
        authorized:     yes
        authenticated:  yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 00:cd:fe:8f:95:55 (on wlan0)
        inactive time:  60 ms
        rx bytes:       5651678
        rx packets:     42755
        tx bytes:       40239068
        tx packets:     37438
        tx retries:     0
        tx failed:      0
        signal:         -36 dBm
        signal avg:     -36 dBm
        tx bitrate:     144.4 MBit/s MCS 15 short GI
        rx bitrate:     144.4 MBit/s MCS 15 short GI
        authorized:     yes
        authenticated:  yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 8c:29:37:c3:3a:f5 (on wlan0)
        inactive time:  2070 ms
        rx bytes:       69165356
        rx packets:     112681
        tx bytes:       48422719
        tx packets:     75525
        tx retries:     0
        tx failed:      0
        signal:         -40 dBm
        signal avg:     -39 dBm
        tx bitrate:     144.4 MBit/s MCS 15 short GI
        rx bitrate:     24.0 MBit/s
        authorized:     yes
        authenticated:  yes
        preamble:       short
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
root@WRT1900AC:~# iw dev wlan1 station dump
Station c8:69:cd:6b:76:86 (on wlan1)
        inactive time:  2340 ms
        rx bytes:       106965308
        rx packets:     801710
        tx bytes:       2107981794
        tx packets:     1476548
        tx retries:     0
        tx failed:      0
        signal:         -34 dBm
        signal avg:     -29 dBm
        tx bitrate:     866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
        rx bitrate:     24.0 MBit/s
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 1c:1a:c0:a1:f7:d9 (on wlan1)
        inactive time:  8210 ms
        rx bytes:       129105782
        rx packets:     1469422
        tx bytes:       3306472651
        tx packets:     3934420
        tx retries:     0
        tx failed:      0
        signal:         -78 dBm
        signal avg:     -78 dBm
        tx bitrate:     150.0 MBit/s MCS 7 40MHz short GI
        rx bitrate:     150.0 MBit/s MCS 7 40MHz short GI
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 48:51:b7:00:d4:8a (on wlan1)
        inactive time:  10 ms
        rx bytes:       10227005
        rx packets:     57185
        tx bytes:       80861494
        tx packets:     85492
        tx retries:     0
        tx failed:      0
        signal:         -59 dBm
        signal avg:     -57 dBm
        tx bitrate:     650.0 MBit/s VHT-MCS 7 80MHz short GI VHT-NSS 2
        rx bitrate:     325.0 MBit/s VHT-MCS 7 80MHz short GI VHT-NSS 1
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
root@WRT1900AC:~# iw dev wlan1 station dump
Station c8:69:cd:6b:76:86 (on wlan1)
        inactive time:  1010 ms
        rx bytes:       106966284
        rx packets:     801724
        tx bytes:       2107982110
        tx packets:     1476550
        tx retries:     0
        tx failed:      0
        signal:         -33 dBm
        signal avg:     -29 dBm
        tx bitrate:     866.7 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 2
        rx bitrate:     24.0 MBit/s
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 1c:1a:c0:a1:f7:d9 (on wlan1)
        inactive time:  2020 ms
        rx bytes:       129106080
        rx packets:     1469424
        tx bytes:       3306472731
        tx packets:     3934421
        tx retries:     0
        tx failed:      0
        signal:         -80 dBm
        signal avg:     -78 dBm
        tx bitrate:     150.0 MBit/s MCS 7 40MHz short GI
        rx bitrate:     150.0 MBit/s MCS 7 40MHz short GI
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no
Station 48:51:b7:00:d4:8a (on wlan1)
        inactive time:  10 ms
        rx bytes:       10241727
        rx packets:     57259
        tx bytes:       80876729
        tx packets:     85567
        tx retries:     0
        tx failed:      0
        signal:         -63 dBm
        signal avg:     -59 dBm
        tx bitrate:     585.0 MBit/s VHT-MCS 7 80MHz VHT-NSS 2
        rx bitrate:     433.3 MBit/s VHT-MCS 9 80MHz short GI VHT-NSS 1
        authorized:     yes
        authenticated:  yes
        preamble:       long
        WMM/WME:        yes
        MFP:            no
        TDLS peer:      no

**Comment by yuhhaurlin** [comment]
@razerwire  Setting and rate information are correct. Are you sure the same test environment can get good throughput if running .16 driver?

**Comment by yuhhaurlin** [comment]
Please use "cat /var/run/hostapd-phy0.conf" or "cat /var/run/hostapd-phy1.conf" to get content of hostapd configuration file.

**Comment by Razerwire** [comment]
>  Setting and rate information are correct. Are you sure the same test environment can get good throughput if running .16 driver?

No, .16 driver yields the same results slow: throuput with iperf3
The .15 driver with identical WIFI-settings set in the WebIF does not exhibit this problem.
.
.

> BTW, please must use AES only.

I only use WPA-2 / AES encryption.

> Please use "cat /var/run/hostapd-phy0.conf" or "cat /var/run/hostapd-phy1.conf" to get content of hostapd configuration file.

Here you go:
```
root@DD-WRT:/tmp# cat ath0_hostap.conf
driver=nl80211
ctrl_interface=/var/run/hostapd
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
tx_queue_data3_aifs=7
tx_queue_data3_cwmin=15
tx_queue_data3_cwmax=1023
tx_queue_data3_burst=0
tx_queue_data2_aifs=3
tx_queue_data2_cwmin=15
tx_queue_data2_cwmax=63
tx_queue_data1_aifs=1
tx_queue_data1_cwmin=7
tx_queue_data1_cwmax=15
tx_queue_data1_burst=3.0
tx_queue_data0_aifs=1
tx_queue_data0_cwmin=3
tx_queue_data0_cwmax=7
tx_queue_data0_burst=1.5
country_code=US
tx_queue_data2_burst=2.0
wmm_ac_be_txop_limit=64
require_ht=1
ieee80211n=1
dynamic_ht40=0
ht_capab=[HT40+][LDPC][SHORT-GI-20][SHORT-GI-40]
vht_capab=[RXLDPC][SHORT-GI-80][RX-STBC1][SU-BEAMFORMER][SU-BEAMFORMEE][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN][MAX-MPDU-7991][MAX-A-MPDU-LEN-EXP7]
ieee80211ac=1
require_ht=1
ieee80211d=1
ieee80211h=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=122
hw_mode=a
channel=116
frequency=5580
beacon_int=100

dtim_period=2

interface=ath0
disassoc_low_ack=1
wmm_enabled=1
bssid=xx:xx:xx:xx:xx:xx
ignore_broadcast_ssid=0
max_num_sta=256
ssid=Stxxxxxxxxx
bridge=br0
logger_syslog=-1
logger_stdout=-1
logger_stdout_level=2
eapol_version=1
eapol_key_index_workaround=0
wpa=2
wpa_passphrase=xxxxxxxxxxxxx
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_group_rekey=3600

.
root@DD-WRT:/tmp# cat ath1_hostap.conf
driver=nl80211
ctrl_interface=/var/run/hostapd
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
tx_queue_data3_aifs=7
tx_queue_data3_cwmin=15
tx_queue_data3_cwmax=1023
tx_queue_data3_burst=0
tx_queue_data2_aifs=3
tx_queue_data2_cwmin=15
tx_queue_data2_cwmax=63
tx_queue_data1_aifs=1
tx_queue_data1_cwmin=7
tx_queue_data1_cwmax=15
tx_queue_data1_burst=3.0
tx_queue_data0_aifs=1
tx_queue_data0_cwmin=3
tx_queue_data0_cwmax=7
tx_queue_data0_burst=1.5
country_code=US
tx_queue_data2_burst=2.0
wmm_ac_be_txop_limit=64
require_ht=1
ieee80211n=1
dynamic_ht40=0
ht_capab=[HT40-][LDPC][SHORT-GI-20][SHORT-GI-40]
hw_mode=g
channel=11
frequency=2462
beacon_int=100

dtim_period=2

interface=ath1
disassoc_low_ack=1
wmm_enabled=1
bssid=xx:xx:xx:xx:xx:xx
ignore_broadcast_ssid=0
max_num_sta=256
ssid=Sxxxxxxxxxxxxx
bridge=br0
logger_syslog=-1
logger_stdout=-1
logger_stdout_level=2
eapol_version=1
eapol_key_index_workaround=0
wpa=2
wpa_passphrase=xxxxxxxxxxxxxxxxxxxx
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_group_rekey=3600

```

**Comment by johnnysl** [comment]
Can't help much anymore i'm afraid. Mine works pretty decent now for the 3rd day straight.

**Comment by yuhhaurlin** [comment]
@Razerwire  I think your problem is 11n client on 5g band (issue #64 ).

**Comment by yuhhaurlin** [comment]
It looks like .17 does not have problem with V2 hardware, I will close this issue.

**Comment by Razerwire** [comment]
> @Razerwire
 I think your problem is 11n client on 5g band (issue #64 ).

All tests regarding this issue were performed with 802.11AC clients no 802.11N cliënts involved!

**Comment by yuhhaurlin** [comment]
@Razerwire How about stock firmware? Obviously .17 does not have problem with V2 hardware. It looks like you are the only one reported this problem now.

**Comment by Razerwire** [comment]
> @Razerwire How about stock firmware? Obviously .17 does not have problem with V2 hardware. It looks like you are the only one reported this problem now.

Well, there are several reference to this issue over at the DD-WRT forums:
http://dd-wrt.com/phpBB2/viewtopic.php?p=1024842#1024842

http://dd-wrt.com/phpBB2/viewtopic.php?p=1024610#1024610

I'll try OpenWRT once it is pushed to trunk to see if it is limited to DD-WRT.

AFAIK i'm not seeing this problem using stock firmware i'll try that tonight or tomorrow.

**Comment by yuhhaurlin** [comment]
@Razerwire The guy mentioned about v1 hardware. I think this one can be closed. I also reply you on issue #64. I think we can track your problem on issue #64.

**Comment by Razerwire** [comment]
>@Razerwire The guy mentioned about v1 hardware. I think this one can be closed. I also reply you on issue #64. I think we can track your problem on issue #64.

Alright then argeed.
