### ISSUE TITLE
Compatible mwlwifi-10.3.0.17 driver with kernel 4.6?

### ISSUE THREAD

**Issue by ValCher1961** [kaloz/mwlwifi#76]
Hi!
During the installation of modules kernel 4.6 with mwlwifi driver 10.3.0.17-20160324 out warning -
```
drivers/mwlwifi/mac80211.c:746:2: warning: initialization from incompatible pointer type [enabled by default]
  .ampdu_action       = mwl_mac80211_ampdu_action,
  ^
drivers/mwlwifi/mac80211.c:746:2: warning: (near initialization for 'mwl_mac80211_ops.ampdu_action') [enabled by default]

```

**Comment by Chadster766** [comment]
Kernel 4.5.4 seem to be working well.

**Comment by thagabe** [comment]
So no?

**Comment by ValCher1961** [comment]
I did not wait for an answer, but my opinion - is not compatible.
The speed of the wifi was ~ 12-14mbit.

**Comment by jbsky** [comment]
So, yes now.

**Comment by ValCher1961** [comment]
I have not tried.

**Comment by thagabe** [comment]
Yes now bc of the dropping of old mac80211 api's but that means cc mightin the gutter
