### ISSUE TITLE
Use of usleep

### ISSUE THREAD

**Issue by thagabe** [kaloz/mwlwifi#82]
(minus)			mdelay(FW_CHECK_MSECS);
(add)			usleep_range(FW_CHECK_MSECS * 1000,
(add)				     FW_CHECK_MSECS * 2000);

After having talks with the fine folks at the LEDE project they have given a convincing argument for the use of usleep rather than mdelay along with the nand-timeout. The argument states that mdelay will make cpu "waste" time and usleep will allow the CPU to do background tasks.

**Comment by yuhhaurlin** [comment]
Yes. I know the patch. I will check it. Thanks.

**Comment by yuhhaurlin** [comment]
Done. Thanks.

**Comment by thagabe** [comment]
Awesome!
