### ISSUE TITLE
Ways to invoke SetFixRate

### ISSUE THREAD

**Issue by freedomsworder** [kaloz/mwlwifi#90]
Hi,

I'm running the stable relase of Openwrt kernel 3.18 for Linksys wrt1200ac, which uses mwlwifi module for mac80211 API.

But what are the ways to issue fwcmd commands such as:
{ HOSTCMD_CMD_SET_FIXED_RATE, "SetFixedRate" },

Thanks!

**Comment by yuhhaurlin** [comment]
Mwlwifi does not support it. Sorry. I will close this one.

**Comment by freedomsworder** [comment]
Thanks Yuhhaurlin!

What about other fwcmd in the char * array? Looks like ways to invoke these commands are not documented.

**Comment by yuhhaurlin** [comment]
Sorry. No document for these commands.
