### ISSUE TITLE
about Marvell Avastar 88W8897 for surface pro 4 hackintosh

### ISSUE THREAD

**Issue by yninan** [kaloz/mwlwifi#99]
Guys ，I'm not sure is here the right place to ask this question.
but I saw you guys do something about the Marvell Avastar 88W8897 chip ,that also in surface pro 4.
I have installed el capitian on my SP4 but the wifi chip still can't drived all over the world ,so I come here hope you guys can make the first thing over the globe to drive it for hackintosher .

thanks.

**Comment by thagabe** [comment]
@yninan what does "guys can make the first thing over the globe to drive it for hackintosher" mean?

**Comment by lantis1008** [comment]
He's installed Mac OS X onto a surface pro 4 making it a hackintosh. It is notoriously difficult to get reliable/any drivers for hardware that wasn't originally found in an apple product. 
He wants a driver for the wifi chip that will work for him, and it sounds like there is no alternatives available.

**Comment by yuhhaurlin** [comment]
I looks like this item should not be checked here. I will close this one. Thanks.
